'use strict';
/*
 * Builds docs/game-reference.md from the live engine.
 *
 * Every number, name and description in the generated sections is read out of
 * BRANCH_WARS.html at build time, so the reference cannot drift from the game.
 * Prose lives in tools/reference-template.md and is the only part written by hand.
 *
 *   node tools/build_reference.js           rebuild docs/game-reference.md
 *   node tools/build_reference.js --check   fail if the committed file is stale
 *
 * The check runs as part of the test suite, so changing a cost or adding a
 * project without rebuilding the reference is a test failure rather than
 * something to remember.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const GAME = path.join(ROOT, 'BRANCH_WARS.html');
const TEMPLATE = path.join(__dirname, 'reference-template.md');
const OUT = path.join(ROOT, 'docs', 'game-reference.md');

// Normalize before parsing/formatting: sourceOf inserts LF line breaks, so
// normalizing only the final comparison cannot undo mixed-EOL blank lines.
const html = fs.readFileSync(GAME, 'utf8').replace(/\r\n/g, '\n');
const engineSource = html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1];
const context = { console, Math, Date, globalThis: null };
context.globalThis = context;
vm.runInNewContext(engineSource, context, { filename: 'embedded-engine.js' });
const E = context.BWEngine;

// ---------------------------------------------------------------- formatting

const money = (n) => {
  if (!Number.isFinite(n)) return String(n);
  if (n === 0) return '$0';
  if (Math.abs(n) >= 1e6) return '$' + (n / 1e6).toFixed(2).replace(/\.00$/, '') + 'M';
  if (Math.abs(n) >= 1000) return '$' + Math.round(n / 1000) + 'K';
  return '$' + n;
};
const esc = (s) => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
const table = (headers, rows) => {
  if (!rows.length) return '_none_';
  return [
    '| ' + headers.join(' | ') + ' |',
    '|' + headers.map(() => '---').join('|') + '|',
    ...rows.map((r) => '| ' + r.map(esc).join(' | ') + ' |'),
  ].join('\n');
};

/* Pulls a top-level function out of the engine source by brace matching, so the
   reference shows the logic that is actually running rather than a paraphrase. */
function sourceOf(name) {
  const needle = 'function ' + name + '(';
  const start = engineSource.indexOf(needle);
  if (start === -1) return '// not found: ' + name;
  let depth = 0;
  let i = engineSource.indexOf('{', start);
  const open = i;
  for (; i < engineSource.length; i++) {
    if (engineSource[i] === '{') depth++;
    else if (engineSource[i] === '}') {
      depth--;
      if (depth === 0) break;
    }
  }
  const body = engineSource.slice(start, i + 1);
  // The engine is minified onto few lines; break after statements so it reads.
  return body.replace(/;(?![^(]*\))/g, ';\n').replace(/\n{2,}/g, '\n').trim();
}

// ------------------------------------------------------------------- sections

const sections = {};
sections.HOUSEHOLD_WORKLOAD = table(
  ['Household segment', 'Workload per 900 relationships'],
  Object.entries(E.HOUSEHOLD_SERVICE).map(([key, workload]) => [E.CUSTOMER_SEGMENTS[key].name, workload])
);

sections.STAMP =
  '_Generated from `BRANCH_WARS.html` by `tools/build_reference.js`. Do not edit this file by hand — ' +
  'edit `tools/reference-template.md` or the engine, then run `node tools/build_reference.js`._';

sections.CONSTANTS = table(
  ['Constant', 'Value', 'Meaning'],
  [
    ['CAPABILITY_CAP_PER_CYCLE', money(E.CAPABILITY_CAP_PER_CYCLE), 'Most that may be put into any one capability lane in a single cycle'],
    ['RECEIVERSHIP_CYCLES', E.RECEIVERSHIP_CYCLES, 'Consecutive cycles of critical distress before the regulator seizes the bank'],
    ['Base execution capacity', E.executionCapacity({ stats: { staff: 0 }, allocation: { service: 0, business: 0, lending: 0, operations: 0 }, capability: {}, upgrades: {} }), 'Capacity the executive team carries with no Operations bankers'],
    ['Capacity per Operations banker', '2.0', 'Added execution capacity per banker assigned to Operations & Risk'],
    ['Capacity per Operations tier', '1.5', 'Added execution capacity per tier of the Operational Excellence lane'],
    ['Max hires per cycle', E.hireLimit({ stats: { staff: 8 } }), 'Ceiling on recruiting in one cycle'],
    ['Fee income per client-facing banker', '$8,000', 'Earned each cycle by every Service, Business and Lending banker'],
    ['Payroll per banker', '$18,000', 'Recurring cost each cycle, before efficiency multipliers'],
  ]
);

sections.OPENING = table(
  ['Stat', 'Opening value'],
  Object.entries(E.OPENING_STATS)
    .filter(([, v]) => v !== 0)
    .map(([k, v]) => [k, k.match(/deposits|loans|capital|cash|fundingCost|earnings|chargeoffs/) ? money(v) : v])
);

sections.SCOPES = table(
  ['Scope', 'Name', 'Markets', 'Max tier'],
  Object.entries(E.SCOPES).map(([k, s]) => {
    const count = Object.values(E.TERRITORIES).filter((t) => t.tier <= s.maxTier).length;
    return [k, s.name, count, s.maxTier];
  })
);

sections.SCENARIOS = table(['Key', 'Name'], Object.entries(E.SCENARIOS).map(([k, v]) => [k, v]));

sections.REGIMES = table(
  ['Regime', 'Policy rate', 'Loan demand', 'Deposit pressure', 'Credit risk', 'Description'],
  Object.entries(E.MACRO_REGIMES).map(([, r]) => [
    r.name, r.rate + '%', r.demand + 'x', r.deposits + 'x', r.credit + 'x', r.text,
  ])
);

sections.ACTS = table(
  ['Act', 'Name', 'Deposit swing cap', 'Contest pressure', 'Focus'],
  E.CAMPAIGN_ACTS.map((a) => [a.roman, a.name, (a.depositCap * 100).toFixed(1) + '%', a.pressure + 'x', a.text])
);

sections.TERRITORIES = table(
  ['Market', 'Tier', 'Unlocks at cycle', 'Value', 'Specialties', 'Note'],
  Object.entries(E.TERRITORIES).map(([k, t]) => [t.name, t.tier, t.unlock, t.value, (t.specialties || []).join(', '), t.note])
);

sections.ROLES = table(['Role', 'Name', 'What it drives'], Object.entries(E.ROLES).map(([k, r]) => [k, r.name, r.desc]));
sections.SPECIALISTS = table(['Department', 'Specialist', 'Recruiting premium', 'Monthly salary premium', 'Workload effect'],
  Object.entries(E.SPECIALIST_ROLES).map(([k, r]) => [k, r.name, money(r.premium), '$' + r.payroll.toLocaleString('en-US'), r.effect]));

sections.POLICIES = [
  ['Deposit pricing', E.DEPOSIT_POLICIES],
  ['Lending standards', E.LENDING_POLICIES],
  ['Capital strategy', E.CAPITAL_POLICIES],
]
  .map(([label, set]) => '**' + label + '**\n\n' + table(['Key', 'Name', 'Effect'], Object.entries(set).map(([k, v]) => [k, v.name, v.desc])))
  .join('\n\n');

sections.PRODUCTS = Object.entries(E.PRODUCT_PORTFOLIOS)
  .map(([key, group]) => {
    const rows = Object.entries(group.options).map(([ok, o]) => {
      const mods = Object.entries(o)
        .filter(([f]) => !['name', 'desc'].includes(f))
        .map(([f, v]) => f + ' ' + (typeof v === 'number' ? (v >= 1 ? '+' : '') + Math.round((v - 1) * 100) + '%' : v))
        .join(', ');
      return [ok, o.name, mods, o.desc];
    });
    return '**' + group.name + '** (`' + key + '`, persistent until changed)\n\n' + table(['Key', 'Option', 'Modifiers', 'Description'], rows);
  })
  .join('\n\n');

/* Anything gated behind the Regional Rivalry pilot is unreachable in a normal
   campaign, so it is listed separately rather than mixed in with what a standard
   game can actually build. */
const PILOT_KINDS = ['branchUpgrade', 'branchClosure', 'productDeployment', 'contractAdvertising'];
const isPilot = (d) => d.regionalOnly || d.contractOnly || d.serviceOnly || PILOT_KINDS.includes(d.kind);
const liveProjects = Object.entries(E.PROJECTS).filter(([, d]) => !d.legacy && !isPilot(d));
const pilotProjects = Object.entries(E.PROJECTS).filter(([, d]) => !d.legacy && isPilot(d));
const retiredProjects = Object.entries(E.PROJECTS).filter(([, d]) => d.legacy);

const projectRow = ([k, d]) => [k, d.name, money(d.cost), d.cycles, d.capacity, d.kind || '--', d.facility || '--', d.target ? 'yes' : 'no', d.desc];
const projectCols = ['Key', 'Name', 'Cost', 'Cycles', 'Capacity', 'Kind', 'Facility', 'Needs a market', 'Effect'];

sections.PROJECTS = table(projectCols, liveProjects.map(projectRow));
sections.PILOT_PROJECTS = table(projectCols, pilotProjects.map(projectRow));
sections.SERVICE_DESK = table(
  ['Mandate', 'Standard fee / turn', 'Direct cost / turn', 'Capacity points'],
  Object.values(E.SERVICE_TYPES).map(d => [d.name, money(d.fee), money(d.cost), d.load])
) + '\n\n' + table(
  ['Application / route', 'Tier-one prerequisites', 'Base deployment', 'Base work cycles', 'Execution load', 'Active upkeep / turn'],
  Object.values(E.SERVICE_APPLICATIONS).map(d => [d.name, d.requires.map(k => E.STRATEGY_BRANCHES[k].name).join(' + '), money(d.cost), d.cycles, d.capacity, money(d.upkeep)])
);

sections.RETIRED = table(
  ['Key', 'Name', 'Status'],
  retiredProjects.map(([k, d]) => [k, d.name, 'Refused by plan validation. Kept only so saves with this work in flight still resolve it.'])
);

sections.CAPABILITIES = Object.entries(E.STRATEGY_BRANCHES)
  .map(([key, b]) => {
    const tiers = E.CAPABILITY_TIERS[key];
    const rows = b.nodes.map((n, i) => ['Tier ' + (i + 1), n.name, money(n.cost), money(tiers[i]), n.desc]);
    const specs = Object.entries(E.STRATEGY_SPECIALIZATIONS[key] || {}).map(([sk, s]) => [sk, s.name, s.desc]);
    return (
      '**' + b.name + '** (`' + key + '`) — _' + b.promise + '_\n\n' +
      table(['Tier', 'Node', 'Step cost', 'Cumulative', 'Effect'], rows) +
      '\n\nOperating models (choose one on reaching tier 1, permanent):\n\n' +
      table(['Key', 'Model', 'Effect'], specs)
    );
  })
  .join('\n\n');

sections.ACTIONS = table(
  ['Key', 'Name', 'Cost', 'Kind', 'Countered by', 'Effect'],
  Object.entries(E.COMPETITIVE_ACTIONS).map(([k, a]) => [k, a.name, money(a.cost), a.kind, a.counter || '--', a.desc])
);

sections.OPPORTUNITIES = table(
  ['Key', 'Name', 'Department', 'Base value', 'Description'],
  Object.entries(E.OPPORTUNITY_TYPES).map(([k, o]) => [k, o.name, o.dept, money(o.base), o.desc])
);

sections.EVENTS = table(
  ['Key', 'Event', 'Situation', 'Option A', 'Option B'],
  E.EVENTS.map((e) => [e.key, e.name, e.text, e.a ? e.a + ' — ' + e.ad : '--', e.b ? e.b + ' — ' + e.bd : '--'])
);

sections.MANDATES = table(
  ['Key', 'Mandate', 'Bonus', 'Requirement'],
  Object.entries(E.MANDATES).map(([k, m]) => [k, m.name, '+' + m.bonus, m.desc])
);

sections.MILESTONES = table(
  ['Key', 'Milestone', 'Requirement'],
  Object.entries(E.MILESTONES).map(([k, m]) => [k, m.name, m.desc])
);

sections.CAPITAL_TIERS = table(
  ['Tier', 'Name', 'Capital ratio', 'Consequence'],
  E.CAPITAL_TIERS.map((t, i) => [i, t.name, t.min > 0 ? '>= ' + t.min + '%' : 'below all thresholds', t.text])
);

sections.CHARACTERS = table(
  ['Key', 'Character', 'Effect while held'],
  Object.entries(E.DOCTRINES).map(([k, d]) => [k, d.name, d.desc])
);

// Live source embeds -- these are the formulas themselves, not a description of them.
for (const fn of ['doctrineProfile', 'executionCapacity', 'hireCost', 'projectCost', 'projectCycles', 'depositPull', 'advanceProjects', 'baseScore', 'capitalRatio']) {
  sections['SRC_' + fn] = '```js\n' + sourceOf(fn) + '\n```';
}

// -------------------------------------------------------------------- render

let out = fs.readFileSync(TEMPLATE, 'utf8').replace(/\r\n/g, '\n');
const used = new Set();
out = out.replace(/<!--\{\{([A-Za-z_]+)\}\}-->/g, (m, token) => {
  if (!(token in sections)) throw new Error('Template asks for unknown section: ' + token);
  used.add(token);
  return sections[token];
});
const unused = Object.keys(sections).filter((k) => !used.has(k));
if (unused.length) throw new Error('Generated sections never placed in the template: ' + unused.join(', '));




if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current.replace(/\r\n/g, '\n') !== out.replace(/\r\n/g, '\n')) {
    console.error('docs/game-reference.md is out of date with the engine.');
    console.error('Run: node tools/build_reference.js');
    process.exit(1);
  }
  console.log('docs/game-reference.md is current.');
} else {
  fs.writeFileSync(OUT, out);
  const counts = {
    markets: Object.keys(E.TERRITORIES).length,
    initiatives: liveProjects.length,
    'pilot initiatives': pilotProjects.length,
    'capability tiers': Object.values(E.CAPABILITY_TIERS).reduce((n, t) => n + t.length, 0),
    'competitive actions': Object.keys(E.COMPETITIVE_ACTIONS).length - 1,
    events: E.EVENTS.length,
    mandates: Object.keys(E.MANDATES).length,
    milestones: Object.keys(E.MILESTONES).length,
  };
  console.log('Wrote docs/game-reference.md —', Object.entries(counts).map(([k, v]) => v + ' ' + k).join(', '));
}
