'use strict';
// Actual control-click workflow checks in an isolated, network-blocked browser.
// Only fixture generation uses engine calls. Browser evaluate calls inspect state
// and install the explicitly isolated Storage shim; they do not stage UI actions.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm'),{createHash}=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),source=process.argv.includes('--source'),html=source?require('./build_game').assemble().html:fs.readFileSync(path.join(root,'BRANCH_WARS.html'),'utf8');
const browserHtml=html.replace("const E=window.BWEngine","Object.defineProperty(window,'__interfaceReadSnapshot',{value:()=>JSON.parse(JSON.stringify({game,draft,seat,draftOwner}))});\nconst E=window.BWEngine");
assert.notEqual(browserHtml,html,'Browser read-only observation hook was not installed');
const out=process.env.BRANCH_WARS_INTERFACE_REPORT_DIR?path.resolve(process.env.BRANCH_WARS_INTERFACE_REPORT_DIR):path.join(root,'reports/local/interface-rebuild-20260927',source?'browser-workflows-source':'browser-workflows-portable');fs.mkdirSync(out,{recursive:true});
const receipt={started:new Date().toISOString(),build:source?'Assembled current source':'Generated portable BRANCH_WARS.html',htmlSha256:createHash('sha256').update(html).digest('hex'),scope:'Actual browser clicks, isolated in-memory Storage, no file URL navigation, all network blocked',observation:'Harness HTML adds one read-only JSON-copy snapshot accessor inside the private client closure. It cannot return live state references. No browser action calls private handlers or mutates that snapshot.',checks:[],flows:[],screens:[],errors:[],limitations:['In-memory Storage does not verify file-origin autosave persistence.','No live GitHub, LAN or P2P peers are exercised.','Engine-generated mature fixture is not a human-played campaign or a gameplay acceptance claim.']};
async function setup(page,{mode='ai',start=true}={}){
 await page.evaluate(()=>{for(const key of ['localStorage','sessionStorage']){const store=new Map();Object.defineProperty(window,key,{configurable:true,value:{getItem:k=>store.get(String(k))??null,setItem:(k,v)=>store.set(String(k),String(v)),removeItem:k=>store.delete(String(k)),clear:()=>store.clear(),key:i=>[...store.keys()][i]??null,get length(){return store.size;}}});}});
 await page.setContent(browserHtml,{waitUntil:'load'});await page.getByRole('button',{name:'Expanded edition',exact:true}).click();await page.locator('#featureSelectionConfirm').click();
 if(!start)return;
 if(mode==='hotseat'){await page.locator('[data-mode="hotseat"]').click();await page.locator('#hotName1').fill('Workflow Bank One');await page.locator('#hotName2').fill('Workflow Bank Two');await page.locator('#startHotseat').click();}
 else {await page.locator('#aiName').fill('Workflow Acceptance Bank');await page.locator('#startAi').click();}
 await page.locator('#interfaceHeader').waitFor({state:'visible'});
}
async function open(page,key){await page.locator('[data-interface-workspace="'+key+'"]').click();}
async function review(page){await page.locator('[data-interface-review]').click();}
async function snap(page,name){await page.evaluate(()=>new Promise(resolve=>{window.scrollTo({top:0,left:0,behavior:'instant'});requestAnimationFrame(()=>resolve());}));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});receipt.screens.push(name+'.png');}
async function read(page,expression){return page.evaluate('(()=>{const {game,draft,seat,draftOwner}=window.__interfaceReadSnapshot();return ('+expression+');})()');}
async function row(page,title){const item=page.locator('#interfaceReview .interface-plan-list>li').filter({hasText:title});assert.equal(await item.count(),1,'one review row for '+title);return item;}
async function remove(page,title){const item=await row(page,title);await item.locator('[data-interface-remove]').click();}
async function stageFinance(page){assert.equal(await page.locator('#financeStage').isEnabled(),true,await page.locator('#financeQuote').innerText());await page.locator('#financeStage').click();}
async function stageIps(page){assert.equal(await page.locator('#ipsAdd').isEnabled(),true,await page.locator('#ipsQuote').innerText());await page.locator('#ipsAdd').click();}
function matureFixture(){
 const c={console};vm.runInNewContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1],c);const E=c.BWEngine;
 const g=E.createGame({...E.previewCampaignEdition({},'expanded',{currentReporting:true,currentEconomics:true,currentResearch:true,currentRivalry:true,currentLending:true,currentMonetaryPolicy:true}).options,startingWorkforce:'covered',mode:'hotseat',seed:'interface-browser-mature-dividends',created:1,name1:'Engine Fixture Bank',name2:'Engine Fixture Rival'}),trail=[];
 for(let n=0;n<16&&!g.gameOver&&g.players[0].financialGroup.parent.accounts.cash<160000;n++){
  const plans=g.players.map((p,i)=>{const plan=E.chooseBot(g,i);plan.newProjects=[];plan.newProject=null;delete plan.projectTargets;plan.investments={};plan.hires=0;plan.specialistHires=E.emptySpecialistOrders();plan.capitalAction=false;plan.companyShareOrders=[];plan.companyControlPolicy=E.defaultCompanyControlPlan(p);plan.agencyPolicy=E.defaultAgencyPlan(p);plan.investmentPolicy=E.defaultInvestmentPlan(p);plan.groupPolicy=E.defaultGroupPlan(p);if(i===0)plan.groupPolicy.bankDividend=Math.min(100000,E.groupCapitalQuote(p).dividendLimit);return plan;});
  trail.push({cycle:g.cycle,requestedDividend:plans[0].groupPolicy.bankDividend,parentBefore:g.players[0].financialGroup.parent.accounts.cash});E.submit(g,0,plans[0]);E.submit(g,1,plans[1]);
 }
 E.validatePilot(g);E.validateLedger(g);const restored=E.migrateCampaign(JSON.parse(JSON.stringify(g)));assert(restored.players[0].financialGroup.parent.accounts.cash>=120000,'Mature dividend fixture did not earn sufficient parent cash.');
 const file=path.join(out,'engine-generated-dividend-campaign.json');fs.writeFileSync(file,JSON.stringify(restored,null,2));receipt.fixture={file:path.basename(file),version:g.version,cycle:g.cycle,parentCash:g.players[0].financialGroup.parent.accounts.cash,trail,method:'Source/portable engine createGame and simultaneous settlement using generated plans; zero extra research/hiring/projects and explicit safeguarded bank dividends. No cash injection or imported private user save.'};return file;
}
async function run(){
 const browser=await chromium.launch({headless:true});let context;
 try{
  context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('**/*',request=>request.abort());
  async function flow(name,fn){const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>receipt.errors.push({flow:name,error:e.stack}));const entry={name,started:new Date().toISOString()};receipt.flows.push(entry);try{await fn(page);entry.passed=true;}catch(error){entry.passed=false;entry.error=error.stack;entry.visible=await page.locator('body').innerText().catch(()=>'<unavailable>');await snap(page,'failure-'+name).catch(()=>{});}finally{entry.completed=new Date().toISOString();await page.close();}}
  await flow('deposit-draft-edit-return',async page=>{
   await setup(page);await open(page,'banking');
   await page.locator('#financeRecord0').focus();await page.locator('#financeRecord0').press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'financeInspectorTitle');const original=await read(page,'JSON.stringify(draft)'),bank=await read(page,'JSON.stringify(game)');
   await page.locator('#financeField0Choice2').click();assert.equal(await read(page,'JSON.stringify(draft)'),original,'working price must not stage');
   await open(page,'markets');await review(page);assert((await page.locator('#interfaceReview').innerText()).includes('Working values have not been added'));
   await open(page,'banking');await page.locator('#financeRecord0').click();assert.equal(await page.locator('#financeField0Choice2').getAttribute('aria-pressed'),'true');await snap(page,'deposit-pending-terms');await stageFinance(page);
   assert.equal(await read(page,'draft.productProgramPolicy.pricingBp.essential'),25);assert.equal(await read(page,'JSON.stringify(game)'),bank);
   await review(page);const pricing=await row(page,'Deposit pricing ·');await pricing.locator('[data-interface-edit]').click();assert(await page.locator('#financeInspectorTitle').innerText().then(t=>t.includes('Essential')));assert(await page.locator('#interfaceReturnBar').isVisible());
   await page.locator('#financeField0Choice0').click();await stageFinance(page);assert.equal(await read(page,'draft.productProgramPolicy.pricingBp.essential'),-25);await page.locator('#interfaceBack').click();await remove(page,'Deposit pricing ·');assert.equal(await read(page,'draft.productProgramPolicy.pricingBp.essential'),0);
   await open(page,'banking');await page.setViewportSize({width:480,height:900});await page.locator('#financeRecord0').press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'financeInspectorTitle');await page.locator('#financeBackToRecords').press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'financeRecord0');await page.setViewportSize({width:1440,height:1000});await review(page);receipt.checks.push('Keyboard Enter opens a finance record and focuses its heading; narrow Back restores record-list focus.');
   receipt.checks.push('Deposit terms: typed choice survives cross-workspace navigation, remains unstaged until Add, Review Edit opens exact product, Update and object-only Remove work without changing books.');await snap(page,'deposit-review-after-remove');
  });
  await flow('people-research-add-remove',async page=>{
   await setup(page);const bank=await read(page,'JSON.stringify(game)');await open(page,'people');await page.locator('[data-ips-view="recruitment"]').click();await page.locator('[data-ips-item="generalist"]').click();await page.locator('#ips-field-generalist').fill('1');await stageIps(page);assert.equal(await read(page,'draft.hires'),1);
   await open(page,'strategy');await page.locator('[data-ips-item]').first().click();const selected=page.locator('[data-rt-node][aria-pressed="true"]'),node=await selected.getAttribute('data-rt-node'),nodeName=await selected.locator('b').innerText(),researchBefore=await read(page,'JSON.stringify(draft.nodeFunding)');await page.locator('#ips-field-amount').fill('1000');assert.equal(await read(page,'JSON.stringify(draft.nodeFunding)'),researchBefore,'working node funding must not stage');await stageIps(page);assert.equal(await read(page,'draft.nodeFunding['+JSON.stringify(node)+']'),1000);await snap(page,'research-staged-inspector');
   await review(page);await remove(page,nodeName);assert.equal(await read(page,'JSON.stringify(draft.nodeFunding)'),researchBefore);assert.equal(await read(page,'draft.hires'),1,'research removal retains recruitment');
   const hire=page.locator('#interfaceReview .interface-plan-list>li').filter({hasText:/Recruit|Hiring/i});assert.equal(await hire.count(),1,await page.locator('#interfaceReview').innerText());await hire.locator('[data-interface-remove]').click();assert.equal(await read(page,'draft.hires'),0);assert.equal(await read(page,'JSON.stringify(game)'),bank);
   receipt.checks.push('People recruitment and Research contributions add through actual editors; separate Review removals retain the other instruction and preserve simulation state.');await snap(page,'people-research-review');
  });
  await flow('office-staff-build-remove',async page=>{
   await setup(page);await open(page,'markets');const bank=await read(page,'JSON.stringify(game)');await page.locator('.im-directory [data-im-view="office"]').first().click();await page.locator('.im-inspector [data-im-view="staff"]').click();const field=page.locator('.im-inspector [data-im-field]').first(),before=Number(await field.inputValue()),fieldPath=JSON.parse(await field.getAttribute('data-im-field'));assert(before>=.25,'opening covered office should have staff');await field.fill(String(before-.25));await page.locator('[data-im-action="save"]').click();assert.equal(await read(page,'draft.facilityLifecyclePolicy.offices['+JSON.stringify(fieldPath[2])+'].staffQuarters['+JSON.stringify(fieldPath[4])+']'),(before-.25)*4);await snap(page,'office-staff-staged');
   await review(page);await remove(page,'local '+fieldPath[4]+' time');assert.equal(await read(page,'draft.facilityLifecyclePolicy.offices['+JSON.stringify(fieldPath[2])+'].staffQuarters['+JSON.stringify(fieldPath[4])+']'),before*4);
   await open(page,'markets');await page.locator('.im-inspector .im-tabs [data-im-view="build"]').click();const groups=await page.locator('.im-build-groups [data-im-view="build"]').count();assert(groups>0,'office construction categories must be reachable');let staged=null;
   for(let group=0;group<groups&&!staged;group++){await page.locator('.im-build-groups [data-im-view="build"]').nth(group).click();const choices=await page.locator('.im-selection nav [data-im-view="build"]').count();for(let i=0;i<choices;i++){if(i>0)await page.locator('.im-selection nav [data-im-view="build"]').nth(i).click();const button=page.locator('[data-im-action="project"]');if(await button.isEnabled()){staged=await page.locator('.im-selection section h3').innerText();await button.click();break;}}}
   assert(staged,'No office build fits the opening bank; '+await page.locator('.im-inspector').innerText());assert.equal(await read(page,'draft.newProjects.length'),1);await snap(page,'office-build-staged');await review(page);await remove(page,staged);assert.equal(await read(page,'draft.newProjects.length'),0);assert.equal(await read(page,'JSON.stringify(game)'),bank);
   receipt.checks.push('Markets: actual local staff reduction and office build add to one plan; Review removes each instruction without assigning staff, constructing a site or spending cash early.');
  });
  await flow('agency-formation-shared-employer',async page=>{
   const fixture=matureFixture();await setup(page,{start:false});await page.locator('#importFile').setInputFiles(fixture);await page.locator('#interfaceHeader').waitFor({state:'visible'});const bank=await read(page,'JSON.stringify(game)'),opening=await read(page,'JSON.stringify(draft.agencyPolicy)');await open(page,'group');await page.locator('#financeView1').click();assert((await page.locator('#interfaceGroup').innerText()).includes('Locked'));await page.locator('#financePrepareExpansion').click();await page.locator('#financeField1').fill('120000');assert.equal(await read(page,'draft.agencyPolicy.capital'),0);
   await page.locator('#financeAgencyPeople').click();assert((await page.locator('#interfaceGroup').innerText()).includes('Insurance agency - expansion people'));const producer=page.getByLabel('Property & casualty producer - $6,000/month each',{exact:true}),credentials=page.getByRole('group',{name:'Registration and staff credentials',exact:true});await producer.fill('2');await credentials.getByRole('button',{name:'Allow to expire',exact:true}).click();assert.equal(await page.locator('#financeStage').innerText(),'Review expansion');await stageFinance(page);assert.equal(await read(page,'JSON.stringify(draft.agencyPolicy)'),opening,'People preparation is not a standalone hire instruction');
   assert.equal(await page.locator('#financeField1').inputValue(),'120000');assert.equal(await page.locator('#financeField0Choice1').getAttribute('aria-pressed'),'true');await page.locator('#financeAgencyPeople').click();assert.equal(await producer.inputValue(),'2');assert.equal(await credentials.getByRole('button',{name:'Allow to expire',exact:true}).getAttribute('aria-pressed'),'true');await stageFinance(page);await snap(page,'agency-formation-working-with-people');await stageFinance(page);assert.equal(await read(page,'draft.agencyPolicy.capital'),120000);assert.equal(await read(page,'draft.agencyPolicy.staff'),2);assert.deepEqual(await read(page,'draft.agencyPolicy.roles'),{propertyProducer:2,benefitsProducer:0,servicing:0});assert.equal(await read(page,'draft.agencyPolicy.maintainCredentials'),false);assert.equal(await read(page,'game.players[seat].agency.status'),'unopened');assert.equal(await read(page,'JSON.stringify(game)'),bank);
   await review(page);assert.equal(await page.locator('.interface-plan-list>li').filter({hasText:'Open insurance agency expansion'}).count(),1);assert.equal(await page.locator('.interface-plan-list>li').filter({hasText:'Insurance agency · employees and credentials'}).count(),0);await remove(page,'Open insurance agency expansion');assert.equal(await read(page,'JSON.stringify(draft.agencyPolicy)'),opening);receipt.checks.push('Engine-generated earned-dividend fixture imported through UI: locked agency preparation retains shared professional-role and credential choices across funding navigation; one explicit Add stages the complete launch; one Review Remove restores funding and dependent staff together.');await snap(page,'agency-shared-policy-review');
  });
  await flow('hotseat-ready-lock',async page=>{
   await setup(page,{mode:'hotseat'});await page.locator('[data-interface-month="decision"]').click();await page.locator('[data-interface-decision="b"]').click();await page.locator('#interfaceDecisionAdd').click();await review(page);assert.equal(await page.locator('#readyBtn').isEnabled(),true,await page.locator('#interfaceReview').innerText());await page.locator('#readyBtn').click();await page.locator('#privacyScreen').waitFor({state:'visible'});assert(await read(page,'!!game.players[0].submitted'));assert.equal(await read(page,'!!game.players[1].submitted'),false);await snap(page,'hotseat-sealed-privacy');await page.locator('#privacyContinue').click();assert.equal(await read(page,'seat'),1);assert.equal(await read(page,'draftOwner'),await read(page,'game.players[1].id'));assert.equal(await read(page,'draft.decision'),null);await review(page);assert.equal(await page.locator('#readyBtn').isEnabled(),false);receipt.checks.push('Hotseat Ready seals first bank, privacy transition changes owner, and rival starts with an independent required decision.');receipt.limitations.push('Hotseat UI hands control to the rival after sealing and exposes no route back to the sealed seat. Recall could not be exercised by actual UI clicks; no direct handler invocation was substituted.');await snap(page,'hotseat-rival-review');
  });
  receipt.completed=new Date().toISOString();receipt.passed=receipt.flows.every(x=>x.passed)&&receipt.errors.length===0;
 }finally{fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));await browser.close();}
 console.log(JSON.stringify({passed:receipt.passed,flows:receipt.flows.map(x=>({name:x.name,passed:x.passed,error:x.error?.split('\n')[0]})),checks:receipt.checks.length,screens:receipt.screens.length,receipt:path.join(out,'receipt.json')}));if(!receipt.passed)process.exitCode=1;
}
run().catch(error=>{receipt.fatal=error.stack;fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));console.error(error);process.exitCode=1;});
