// Static, owner-scoped help. Searching never quotes a plan, reconstructs a
// public view, reads rival information, or retains the campaign's large books.
const GAME_HELP_TOPICS=[
 {id:'investment-notes',title:'Fixed-term notes: commitment, coupons and issuer cash',words:'note term maturity fixed coupon principal lockup subscription dealer issuer liquidity',requires:['investmentNotesVersion'],tab:'group',groupDesk:'investments',target:'#investmentTitle',text:'Investment services → Client accounts → select an account → Fixed-term notes. Choose six or 24 months using existing account cash. The longer term is unavailable to near-term liquidity mandates. Review and stage the subscription; the coupon locks at monthly settlement. A filled subscription costs $5 and requires qualified service and operations work. Notes cannot be redeemed early. The outside dealer owes principal and coupons; payments require its actual cash, with due principal paid before coupons. Unpaid amounts remain claims, not spendable cash. Note claims count toward the customer investment limit and serviced assets. These are unsecured game investments, not insured bank deposits or a guaranteed market value. Remove working subscription also requires review and staging to cancel an existing staged instruction.'},
 {id:'investment-services',title:'Investment business: qualified people, funding and client assets',words:'advice adviser brokerage carrying custody parent capital permissions provider migration fees support',requires:['investmentBusiness'],tab:'group',groupDesk:'investments',target:'#investmentTitle',text:'Open Financial Group → Investment services. Edit the business model, qualified team and funding in Business & team; Review complete instruction shows upfront costs, monthly bills and permission dates before Stage. The parent contribution uses existing parent cash, not bank deposits. Ordinary bankers do not replace advisers, representatives, principals or custody operations. Client accounts has a separate target market and one-time transfers from existing unlocked savings. Final liquidity and service checks can refuse those transfers. Results separates business costs, client fees and customer assets. Available securities, cash arrangements and portfolio controls depend on this campaign’s saved rules. Existing campaigns are not upgraded automatically.'},
 {id:'investment-trading',title:'Client portfolio: buy with account cash or sell existing holdings',words:'trade buy sell securities cash execution fee portfolio mandate suitability orders',requires:['investmentTradingVersion'],tab:'group',groupDesk:'investments',target:'#investmentTitle',text:'Investment services → Client accounts → select an account. Buy uses its existing cash; Sell returns proceeds to that account, not to the bank. Enter the trade value before the $5 execution fee. Review complete instruction, then Stage; no money moves before both banks submit. A qualified attempt uses five adviser/broker slots and one operations slot after servicing and migration. Dealer cash, inventory and customer investment limits may reduce the fill. No fill means no execution fee. Remove working order also needs review and staging to cancel an already-staged trade. Discard returns to the staged instructions. One order per account per month; never use client assets as subsidiary capital.'},
 {id:'opportunities',title:'Inspect opportunities and reserve pursuit capacity',words:'business bankers commercial acquisition pipeline bid pursue people staff contractor resources',tab:'markets',target:'#pipeline',text:'Open an opportunity in Markets to inspect its potential balances, fees and required work. Inspection changes no orders. Expanded campaigns require unused capacity after existing customer work; review an existing-staff reservation or contracted capacity directly on the opportunity, then confirm the whole change. These department reservations are standing instructions and continue until revised. Removing the pursuit does not cancel them. A service-agreement bid uses the same pursuit slot. The Operating Company Relationship award does not automatically open a commercial loan or separate treasury mandate. Use Review all work commitments to open the exact affected function.'},
 {id:'commercial-loans',title:'Commercial loan requests: principal, fees and funding',words:'business bankers commercial loan mandate mortgage consumer fee withheld advance middle market',requires:['creditBook'],tab:'markets',target:'#pipeline',text:'Inspect a Commercial Loan Request to see its actual product and terms. The current Expanded candidate originates it as a 48-month middle-market loan, without changing ordinary lending allocations. Its origination fee is withheld from the advance: the borrower owes full principal, but only the net advance leaves the bank. Historical campaigns retain their earlier portfolio routing, which the inspector identifies. Winning is uncertain; repayment, credit deterioration and losses continue afterward. Staffing a pursuit does not itself provide money. Funding occurs after monthly operations and can trigger existing asset sales or emergency funding. The quotation assumes current conditions and is not a borrower-specific credit assessment.'},
 {id:'planning',title:'Monthly planning and required decisions',words:'turn ready submit executive event blockers',tab:'operations',desk:'monthly',target:'#decisionGrid',text:'Choose the executive decision and review every required item in the monthly review. Optional opportunities and initiatives are not prerequisites for a turn. Mark Ready commits your plan; the month resolves only when both institutions are ready.'},
 {id:'value',title:'Enterprise value: how the campaign is scored',words:'score win winning value points lead result mandate bonus ranking',tab:'overview',target:'#myScore',text:'Enterprise value is the single number the campaign is judged on. It blends the balance sheet (deposits, loans and cash), the franchise (customers, business and merchant relationships, branch levels and market share) and the institution itself (capital, retained earnings, reputation, morale, staff, influence and completed research), then subtracts recorded risk, executive attention and accumulated credit losses. Career milestones each add a fixed amount. Your confidential mandate adds its bonus only at the end, and only if it is met, so a trailing score can still finish ahead. Every figure it uses is already visible on your own desks; nothing about the rival is inferred.'},
 {id:'changes',title:'Current policy, form edits and staged orders',words:'draft save apply preview undo cancel active commitment',tab:'overview',target:'#monthlyChangesDrawer',text:'Current policy is already in effect. Unfinished form edits are not orders: use their Preview and Stage controls where provided. Staged instructions belong to this month’s shared draft. Monthly changes compares that draft with its opening plan and offers individual undo where dependencies allow. Undo cannot cancel work completed in a previous month.'},
 {id:'funds',title:'Cash versus available spending room',words:'money budget discretionary reserve protected capital afford',tab:'overview',target:'#financialFundingDetails',text:'Bank cash is a balance, not a spending allowance. Planned commitments, protected reserves and capital constraints can make spendable funds much smaller. The shared monthly budget and financial explanation use the current draft; a subsidiary or parent balance is not automatically available to the bank.'},
 {id:'earnings',title:'Operating profit versus retained earnings',words:'income loss revenue equity capital accounting balance sheet results',tab:'overview',target:'#financialEarningsDetails',text:'Operating profit reports a month’s operating result. Retained earnings accumulate results and other equity-affecting movements; they are not cash. Where the campaign records a complete earnings bridge, it explains opening earnings, operating profit, other net changes and closing earnings. Missing historical detail is not reconstructed.'},
 {id:'forecasts',title:'Read bank and commercial forecasts',words:'prediction estimate profit cost preview uncertainty outcome business deposits loans treasury merchant growth',tab:'operations',desk:'forecast',target:'#operatingPreview',text:'Choose Bank forecast, Commercial banking or Balances & books. Commercial banking compares business/merchant relationship growth, fee income, commercial loan vintages and delivered treasury run rate. New Expanded campaigns also show funded business operating deposits; older saves do not gain that book automatically. Account wins, withdrawals and company cash changes occur at month-end, outside the operating estimate. Core has no product-level loan attribution or treasury contracts. Rival actions, executive events and new bids can change the outcome. Product and treasury fees are already included in bank income; do not add them twice.'},
 {id:'business-accounts',title:'Win and service a business operating account',words:'company business deposits cash qualification pursuit bankers treasury withdrawal staff',requires:['commercialAccounts'],tab:'markets',target:'#commercialClientWorkspace',text:'Select a named Business client, then Pursue operating account and reserve shared Business time in 0.25 employee-month steps. Existing accounts use 0.25 each first. One remaining step advances the selected company; two pursued months qualify an offer. A local office is required. Reputation, Commercial capability, serviced treasury and an incumbent relationship affect selection. A won account holds half the company’s actual closing cash, not new income. Three missed service months cause withdrawal. Shared time reduces ordinary commercial sales; no employee is hired here. Loans and treasury agreements remain separate choices.'},
 {id:'allocation',title:'Allocate employees to departments',words:'staff headcount pool banker retail business lending operations unassigned',tab:'operations',desk:'monthly',target:'#staffGrid',text:'Allocation divides the existing shared staff pool among departments. Assigning every employee does not prove all work is covered. Where workforce and department work are enabled, training, reserves and other commitments reduce productive time; expertise affects particular work rather than creating extra people.'},
 {id:'coverage',title:'People: employees versus work coverage',words:'workforce staff capacity reservations quarter units shortage uncovered bottleneck service',requires:['workforce'],tab:'workforce',peopleDesk:'overview',target:'#peopleOverview',text:'People Overview separates headcount from available employee time and delivered work. Four quarter-time units equal one employee-month. Reservations and teaching time are not spare employees. Where department work is enabled, review uncovered tasks and their business consequences before deciding whether to reassign, recruit or reduce commitments.'},
 {id:'department-work',title:'Department work priorities and uncovered demand',words:'staff service capacity dispatch task objectives shortage',requires:['workforce','departmentFunctions'],tab:'workforce',peopleDesk:'coverage',target:'#departmentPanel',text:'Select a function from the directory, or open its shortage from People Overview. Its inspector shows affected work, forecast coverage, additional staff and vendor costs. Enter employee-months in 0.25 steps: one full-time banker is 1.00. Preview, then Adopt to stage reviewed changes; Discard removes the preview, not existing orders. Moving time can uncover other work. Bank-wide accounting and bounded proposals remain below the inspector.'},
 {id:'recruitment',title:'Recruitment: signing cost and arrival timing',words:'hire generalist specialist salary payroll employee new banker',requires:['workforce'],tab:'workforce',peopleDesk:'recruitment',target:'#peopleRecruitment',text:'Generalists and specialists share the monthly hiring limit and spending room. The next-recruit quote is the extra signing cost, not the full future payroll. Staged recruits arrive next month; they cannot cover the work being settled now. Specialist expertise and recurring salary premiums differ from headcount.'},
 {id:'training',title:'Training, reserves and productive time',words:'workforce expertise development skill course teaching budget preview',requires:['workforce'],tab:'workforce',peopleDesk:'development',target:'#workforcePanel',text:'Choose a specialist department to inspect its skills and recurring training. Preview compares all edited training amounts against the staged plan, including requested and effective limits. Department ceilings and shared reserves can restrict spending. Switching departments retains unfinished entries but does not stage them. Training uses cash and sometimes teaching time now for later benefits; bank-wide costs and morale remain below the inspector.'},
 {id:'leadership',title:'Leadership, budgets and bounded delegation',words:'manager department leader compensation objectives training caps reserve automate',requires:['workforce','departmentOffice'],tab:'workforce',peopleDesk:'leadership',target:'#departmentPanel',text:'Leadership and budgets set organizational commitments and spending ceilings, not a second pool of employees or money. Review proposal changes and their whole-plan costs. Delegation works within supported limits; it does not authorize a manager to submit turns or make major strategic transactions for you.'},
 {id:'deployment',title:'Deposits fund lending; lending is most of the balance sheet',words:'loan deposit ratio deployment origination capacity lending staff balance sheet cash idle',requires:['researchProgramVersion'],tab:'operations',target:'#productPortfolio',text:'Your lending desk no longer caps the book on headcount alone. Each cycle the bank deploys part of the gap between its deposits and its loan book, at a pace your Lending bankers set: with nobody assigned to Lending nothing is deployed. A healthy bank runs most of its deposits as loans rather than holding them as cash, and loans are roughly a quarter of final standing. Cash still matters for projects, research and hiring, so the judgement is how much to keep spare.'},
 {id:'relationships',title:'Commercial relationships need somewhere to be served from',words:'business merchant relationships branches capacity fees commercial saturation',requires:['researchProgramVersion'],tab:'markets',target:'#marketMap',text:'Business and merchant relationships are won against your physical presence. Past what your branch network can carry, new relationships arrive far more slowly however many Business bankers you assign, and fee income per relationship is already throttled by servicing capacity. Building offices raises the ceiling; staffing alone does not.'},
 {id:'combinations',title:'Two capabilities together unlock what neither grants alone',words:'combination combined capability cross branch digital treasury structured credit deposit franchise integration straight through',requires:['researchProgramVersion'],tab:'strategy',target:'#strategyTree',text:'Six capability branches each carry three permanent operating models, and certain pairs of branches unlock a combined capability once both reach the required tier. Combined capabilities apply automatically and are listed under COMBINED CAPABILITIES in Research. Stronger products are also gated: the first option on every line is always available, and the rest are earned by research.'},
 {id:'research',title:'Research is not the same as implementation',words:'strategy capability tree unlock specialization operating model build buy license partner',tab:'strategy',target:'#strategyTree',text:'Choose a capability in the directory. Fund research shows its next milestone, paid versus staged progress and full roadmap. Operating model compares permanent choices; review and confirm before staging, or remove an uncommitted choice. Deployment & use shows related products and service platforms, their prerequisites, actual delivery and ongoing costs. Product links open the exact offer. Research alone does not activate a platform, assign staff or win customers. All five capabilities and historical campaign rules remain available.'},
 {id:'projects',title:'Project progress and Operations capacity',words:'initiative stalled timing duration completion queue execution work units',tab:'operations',desk:'projects',target:'#activeProject',text:'Base work units are not a guaranteed number of calendar months. Shared Operations capacity, active commitments and campaign capabilities affect delivery. Review active progress and new initiative capacity together. Hiring for next month does not repair this month’s execution shortage.'},
 {id:'deposit-policy',title:'Deposit strategy and rate-sensitive funding',words:'pricing interest margin growth runoff cost savings bank funding',tab:'operations',desk:'funding',target:'#depositPolicies',text:'Aggressive deposit pricing trades funding cost and rate-sensitive exposure for acquisition strength. Repricing toward margin can cause runoff. Compare your current-book funding profile with the draft forecast; attracting deposits adds a liability as well as cash, not free profit.'},
 {id:'lending-policy',title:'Lending standards, return and delayed risk',words:'loan underwriting conservative growth credit loss risk appetite',tab:'operations',desk:'funding',target:'#lendingPolicies',text:'Lending standards change production and risk. More volume is not automatically better: loans consume funding and capital and can create future losses. The exact portfolio and credit controls depend on the campaign’s enabled systems. Use Credit when available to inspect recorded deterioration and collections.'},
 {id:'products',title:'Product development, deployment and retirement',words:'research build buy license lifecycle maintenance offer launch catalogue catalog',requires:['productPrograms'],tab:'products',productDesk:'development',target:'#productProgramsPanel',text:'Choose a product in the catalogue, then use Delivery, Pricing or Local sales in its inspector. Delivery compares exact upfront cost, shared execution needs and ongoing vendor charges. The research shortcut opens its prerequisite capability. Retirement first reviews the cost, every affected market and existing account promises; nothing changes until confirmed. Canceling an already-staged retirement does not reopen its sales targets. Reopening a retired product requires paid rollout.'},
 {id:'targeting',title:'Product sales targets by market and audience',words:'segment emphasis customers fit local product share demand',requires:['productPrograms'],tab:'products',productDesk:'targets',target:'#productProgramsPanel',text:'Select one product, market and audience, then its sales emphasis. The complete audience mix remains visible for comparison. Edits stage immediately for that selection only; at least one available fallback must stay open. Fit measures acquisition strength, not a win probability. Market inspection never changes action focus, existing products or locked rates.'},
 {id:'pricing',title:'Product pricing and protected balances',words:'tariff basis points interest variable guarantee locked annual rate statement',requires:['productPrograms'],version:['productPrograms',2],tab:'products',productDesk:'pricing',target:'#productProgramsPanel',text:'Choose a product and compare the current tariff with its staged offer on existing balances. The 0.25-percentage-point adjustment is 25 basis points, not a 25% change. Protected guarantees remain distinct from variable accounts. Direct funding cost is interest plus service and platform costs minus fees, not product profit. Compare this price plan is a pure bank-wide estimate with explicit assumptions. Statements contains actual billed months and the deposit movement bridge.'},
 {id:'advertising',title:'Advertising, acquisition and attribution',words:'marketing channel campaign awareness spending budget funnel conversion saturation',requires:['productPrograms','advertising'],tab:'products',productDesk:'advertising',target:'#productProgramsPanel',text:'Manage the same standing campaign here or select a market and choose Manage local campaign. Compare budgets: extra spending can buy no extra reach. The desk shows application targeting, processing capacity and a direct staffing shortcut. Ordinary intake can shift without total growth increasing; awareness is not an owned customer, deposit or proof of additional profit. Pausing stages a real zero budget for the next resolution.'},
 {id:'offers',title:'Compete for existing customer relationships',words:'share wallet retention relationship offer cross sell',requires:['productPrograms','relationshipOffers'],tab:'products',productDesk:'relationships',target:'#productProgramsPanel',text:'Existing-customer offers compete for supported relationships already in the market. Keep the offered benefit, cost and delivery capacity in view. Winning one product relationship does not establish ownership of every part of a customer’s finances. Campaigns without this preview do not provide this desk.'},
 {id:'onboarding',title:'Applications are not yet activated accounts',words:'pending intake queue expiry abandonment delay staff service customer deposit',requires:['productPrograms','onboarding'],tab:'products',productDesk:'onboarding',target:'#productProgramsPanel',text:'Pending applications are requests, not bank-owned customers or deposits. Activation requires eligible work and capacity; requests can expire or be abandoned. Review the queue, staffing and actual activation results before increasing intake. Do not count pending principal as available bank funding.'},
 {id:'customers',title:'Service and retention of existing households',words:'relationships churn loyalty wallet deposits service coverage',requires:['householdBook'],tab:'customers',householdDesk:'service',target:'#householdPanel',text:'Customers shows the supported household relationships and retention controls in your campaign. Service capacity and commitments affect the existing book, not just acquisition. Review market-level exposure and the actual recorded customer effects instead of assuming influence means ownership.'},
 {id:'credit',title:'Arrears, collections and credit history',words:'delinquency vintages cohort cure recover charge off losses loans small business commercial property collateral concentration',requires:['creditPerformance'],tab:'credit',target:'#creditPanel',text:'Follow the recorded loan portfolio and supported collections actions. Amounts entering arrears, cured, recovered and lost are different flows; subtracting only two of them is not a complete delinquency bridge. New Expanded lending rules add 36-month small-business and 120-month commercial-property portfolios. Their existing terms, balances and arrears are shown in Loan terms, existing exposure & arrears. Concentration raises future distress; property risk and collateral recoveries worsen in a credit downturn. Changing allocation does not rewrite old loans or end servicing. A strong current profit can coexist with deteriorating future credit quality.'},
 {id:'facilities',title:'Facilities: local reach and operating commitments',words:'branch network office location micro retail commercial hub wealth upgrade capacity staff',requires:['facilityNetwork'],tab:'markets',target:'#facilityNetworkPanel',text:'Compare the available facility types, local capacity and operating commitments. Physical capacity is not a supply of employees. A larger location can need additional staff or department support to use its potential. Existing campaign options determine which facility types and controls are available.'},
 {id:'maintenance',title:'Facility condition, renovation and conversion',words:'repair upkeep maintenance wear branch office upgrade closure',requires:['facilityLifecycle'],tab:'markets',target:'#facilityLifecyclePanel',text:'Inspect the location’s condition and ongoing work before staging maintenance or a conversion. These choices have costs and persistent consequences; a conversion is not an instant free upgrade. Review shared protected spending and the facility’s staffing needs along with its proposed new role.'},
 {id:'office-suite',title:'Add commercial services inside an existing office',words:'extension fitout suite business lending premises staffing construction capacity',requires:['facilityExtensions'],tab:'markets',target:'#facilityLifecyclePanel',text:'Select an eligible office in Markets and expand Add a commercial banking suite. Stage its paid fit-out without replacing the original service. Construction uses shared execution capacity and opens next month after completion. The combined staffing reference divides existing employee time between the host and suite; neither creates customers or funding. Upkeep and maintenance begin after opening. Canceling unfinished work returns no fit-out payment. Existing campaigns without this system keep their original facilities.'},
 {id:'influence',title:'Inspect markets and stage local actions',words:'map conquered territory district control share domination competition focus construction build office project',tab:'markets',target:'#marketInspector',text:'Selecting a district only inspects it. The inspector shows local balances, influence and owned offices; influence is not deposit ownership. Use as monthly focus explicitly changes the target. Local construction uses the same project rules as Operations. If it changes focus, review and confirm all affected staged projects and competitive actions. Cancel changes nothing. Office buttons open that exact location’s staffing, maintenance or conversion controls without leaving Markets.'},
 {id:'renewals',title:'Corporate service contracts and renewals',words:'treasury merchant pricing bid client agreement company service expiry',requires:['serviceDesk'],tab:'markets',target:'#commercialClientWorkspace',text:'Choose a company in Business clients to inspect one agreement and compare real staff or paid delivery. Review the combined proposal before confirming; any extra technology support and recurring bills are listed. Future contests allow capacity preparation, not an early bid. Incumbents defend automatically unless you decline renewal. Desk-wide pricing and advanced controls remain below the directory. Company ownership is separate from its banking-provider relationship.'},
 {id:'competition',title:'Concealed actions, defenses and public intelligence',words:'rival attack raid deposit campaign poach counter target',tab:'competition',target:'#competitiveActions',text:'Choose among the actions supported by your campaign and review their target, cost and counter. Plans resolve simultaneously; a rival’s last revealed action is not their next plan. Neither this help nor the forecast reveals private rival instructions. No action is selected merely by opening this desk.'},
 {id:'group',title:'Financial Group: parent versus bank resources',words:'subsidiary capital dividend injection cash equity consolidated transfer',requires:['financialGroup'],tab:'group',groupDesk:'capital',target:'#financialGroupPanel',text:'Parent, bank and subsidiary resources are separate. Capital shows the direction of each transfer. Preview checks existing parent commitments; Stage changes the monthly plan, not actual cash. Unstaged entries survive desk changes; Discard restores the staged amounts. Company statements belong to clients, not your bank. Consolidation removes internal investments to avoid double-counting. Transfers remain subject to safeguards and settlement timing; parent cash is not automatic bank spending room.'},
 {id:'company-control',title:'Company shares, controlling offers and consent',words:'takeover acquisition diligence shares auction parent borrowing integration rival consent tender defense',requires:['companyControl'],tab:'group',groupDesk:'companies',target:'#financialGroupPanel',text:'Select an operating company to inspect its actual finances, trade minority shares or plan control. Diligence is a paid review usable next month; it expires. A controlling offer needs more than 50% ownership, existing parent funding, purchase fees and reserved integration work. Borrowing uses a funded outside lender and requires distributable-cash coverage. An offer waits at least one month before closing. Rival-owned shares require that shareholder’s explicit consent; refusing does not cost money. Outside tenders require a premium. Six funded integration stages consume shared execution capacity after closing. Pausing or selling the stake does not erase debt. Banking contracts and customer relationships are separate from share ownership. Opponents see published offers, not your sealed plan.'},
 {id:'company-consolidation',title:'Your group’s equity versus outside ownership',words:'goodwill consolidated company equity outside shareholders investment basis internal deposits dividends earnings',requires:['companyConsolidation'],tab:'group',groupDesk:'capital',target:'#financialGroupPanel',text:'Open Reconciled balance sheets on Group capital. Controlled companies contribute their assets and liabilities after the parent’s investment is removed. Outside shareholders retain their portion; Your group’s equity excludes it. Only your share of post-acquisition earnings is included, and paid dividends are not counted twice. Deposits and unpaid service claims between your bank and a controlled company cancel in these totals. Goodwill is a noncash acquisition amount, not bank capital or spendable money. Losing control removes the company from consolidation without forgiving debt. This is a fictional book-value worksheet, not a full legal reporting standard.'},
 {id:'agency',title:'Insurance agency is not underwriting',words:'subsidiary carrier commission insurance premium policies coverage group staff outreach launch licensed qualified producer credentials servicing registration',requires:['financialGroup','agency'],tab:'group',groupDesk:'agency',target:'#financialGroupPanel',text:'The agency distributes third-party carrier products and earns commissions, not underwriting profit. Funding & launch manages actual parent capital, distributions and a capped safety net. People & sales shows dedicated employee costs, product focus and outreach prices. New Group10 campaigns distinguish property/casualty and benefits producers from servicing staff; paid registration takes two months, and maintaining credentials costs money and work time. Ordinary bank staff supply no agency credential. Older campaigns keep their generic staffing rules. Results & covers shows settled performance and renewable relationships. These views share one working form: Preview checks it, Stage applies the whole agency instruction, and Discard removes unstaged edits. Requested bank dividends cannot pre-fund this month’s launch.'},
 {id:'history',title:'Actual results, history and public scorecard',words:'last month debrief log trend performance intelligence milestones',tab:'intelligence',target:'#lastResolution',text:'Read recorded outcomes after resolution and compare them with your planning estimates. Available history is limited by the campaign version and retained records; absent periods are not synthesized. Public rival metrics do not include their private pending orders or customer queues.'},
 {id:'connection',title:'Connection health, readiness and safe recovery',words:'multiplayer github lan intranet direct link reconnect acknowledgement yellow retry sync',tab:'overview',target:'#linkState',text:'A connection indicator and the two readiness states describe different things. A local click alone is not proof that a remote plan was acknowledged. Follow the current transport’s recovery message and keep one tab per player. Do not start a replacement campaign to repair an interrupted room; preserve the existing checkpoint and use supported reconnect/resume controls.'},
 {id:'export',title:'Export, Continue and private session recovery',words:'save backup download import persistence storage token credentials',tab:'overview',target:'#exportBtn',text:'Use the supported Export control for a portable campaign snapshot when available. Continue uses this browser’s local campaign; it is not a substitute for the room’s multiplayer checkpoint. Keep credentials and private campaign files private. A download is not verified until you can reopen the intended campaign from it.'},
 {id:'optional',title:'Core, Expanded and historical campaign rules',words:'feature checkbox complexity settings prerequisites modular disabled lobby',tab:'overview',target:'#scopeName',text:'New campaigns choose Core or Expanded. Expanded enables its connected systems together and currently uses the six-market regional pilot; it is not National Empire. The host applies shared lobby settings and both players confirm readiness. Historical campaigns retain their supported selections and versions; help cannot add a missing system or upgrade a save. Presentation changes do not change campaign rules.'}
];
const gameHelpBound=new WeakSet();
let gameHelpSession=null;
GAME_HELP_TOPICS.push({id:'shared-premises',title:'Shared offices and qualified subsidiary time',words:'visiting adviser desk wealth insurance agency suite extension premises rent space occupancy',requires:['sharedPremises'],tab:'markets',target:'#sharedPremisesDesk',text:'In an office inspector, open Shared service rooms. Inspect one existing room or review an extension. Fit-out uses bank cash and shared execution; rooms open after construction. They supply space, not employees or licenses. Assign investment or agency employees in 0.25 employee-month steps; their local time is taken from existing central capacity. The bank pays outside upkeep and occupied subsidiaries reimburse their actual share, so internal rent is not new group profit. Refresh estimate shows qualified time and costs; Stage changes the monthly draft only. Discard removes editor changes; Reset premises draft restores standing allocations. Cancellation or removal gives no refund. Staffing and funding shortcuts lead to the employing business. Historical campaigns do not gain these rooms automatically.'});
function gameHelpProfile(v){
 const features={};
 for(const topic of GAME_HELP_TOPICS)for(const key of topic.requires||[])features[key]=!!v.me[key];
 return {features,productPricingVersion:v.me.productPrograms?.version||0};
}
function gameHelpAvailable(topic,profile){return (topic.requires||[]).every(key=>profile.features[key])&&(!topic.version||profile.productPricingVersion===topic.version[1]);}
function searchGameHelp(query,profile,tab){
 const terms=String(query).slice(0,200).toLocaleLowerCase('en-US').trim().split(/\s+/).filter(Boolean);
 return GAME_HELP_TOPICS.map((topic,index)=>({topic:topic.id==='research'&&profile.features.researchProgramVersion?{...topic,text:topic.text.replace('All five capabilities','All six capabilities')}:topic,index,available:gameHelpAvailable(topic,profile)})).filter(({topic})=>{
  const haystack=(topic.id+' '+topic.title+' '+topic.words+' '+topic.text).toLocaleLowerCase('en-US');return terms.every(term=>haystack.includes(term));
 }).sort((a,b)=>Number(b.available)-Number(a.available)||Number(b.topic.tab===tab)-Number(a.topic.tab===tab)||a.index-b.index);
}
function gameHelpCurrent(){
 return !!gameHelpSession&&(game||view)===gameHelpSession.campaign&&draftOwner===gameHelpSession.owner&&lastCycle===gameHelpSession.cycle&&seat===gameHelpSession.seat&&featureConnectionGeneration===gameHelpSession.connection;
}
function closeGameHelp(restore=true){
 const dialog=$('#gameHelp'),session=gameHelpSession,current=gameHelpCurrent();gameHelpSession=null;
 if(dialog?.open)dialog.close();
 if(restore&&current){const target=session?.opener?.isConnected?session.opener:$('#gameHelpOpen');target?.focus?.({preventScroll:true});}
}
function renderGameHelp(){
 if(!gameHelpCurrent()){closeGameHelp(false);return;}
 const results=searchGameHelp($('#gameHelpSearch').value,gameHelpSession.profile,gameHelpSession.tab),mount=$('#gameHelpResults');
 $('#gameHelpCount').textContent=results.length+' '+(results.length===1?'topic':'topics')+'. Explanations and navigation only; no orders are changed.';
 mount.innerHTML=results.length?results.map(({topic,available})=>'<article class="game-help-topic"><h3>'+esc(topic.title)+'</h3><p>'+esc(topic.text)+'</p><p class="micro muted">'+(available?'Available in this campaign.':'Not enabled in this campaign version. This explanation does not add the system.')+'</p><button type="button" class="btn" data-help-open="'+topic.id+'" '+(available?'':'disabled')+' aria-label="Open controls: '+esc(topic.title)+'">'+(available?'Open controls':'Unavailable in this campaign')+'</button></article>').join(''):'<p>No matching topics. Try “staff”, “cash”, “research”, “applications” or “connection”. Search uses all entered words.</p>';
 mount.scrollTop=0;
}
function openGameHelp(topicId,opener){
 const v=currentView(),dialog=$('#gameHelp');if(!v||!dialog||draftOwner!==v.me.id||lastCycle!==v.cycle)return;
 gameHelpSession={campaign:game||view,owner:v.me.id,cycle:v.cycle,seat,connection:featureConnectionGeneration,profile:gameHelpProfile(v),tab:workspaceTab,opener:opener||document.activeElement};
 const topic=GAME_HELP_TOPICS.find(x=>x.id===topicId);$('#gameHelpSearch').value=topic?topic.title:'';
 renderGameHelp();if(!dialog.open)dialog.showModal();$('#gameHelpSearch').focus();$('#gameHelpSearch').select();
}
function navigateGameHelp(id){
 if(!gameHelpCurrent()){closeGameHelp(false);return false;}
 const topic=GAME_HELP_TOPICS.find(x=>x.id===id);if(!topic||!gameHelpAvailable(topic,gameHelpSession.profile))return false;
 closeGameHelp(false);
 if(topic.productDesk)productDeskView=topic.productDesk;
 navigateBankOverview(topic);if(topic.groupDesk)setFinancialGroupDesk(topic.groupDesk,{focus:true});return true;
}
function reconcileGameHelp(){
 const dialog=$('#gameHelp'),screen=$('#gameScreen');if(!dialog||!screen)return;
 if(gameHelpSession&&!gameHelpCurrent())closeGameHelp(false);
 if(gameHelpBound.has(dialog))return;gameHelpBound.add(dialog);
 $('#gameHelpOpen').addEventListener('click',event=>openGameHelp(null,event.currentTarget));
 $('#gameHelpClose').addEventListener('click',()=>closeGameHelp());
 $('#gameHelpSearch').addEventListener('input',renderGameHelp);
 $('#gameHelpResults').addEventListener('click',event=>{const button=event.target.closest('[data-help-open]');if(button&&!button.disabled)navigateGameHelp(button.dataset.helpOpen);});
 dialog.addEventListener('cancel',event=>{event.preventDefault();closeGameHelp();});
 // Native search inputs otherwise consume the first Escape to clear their
 // text. The dialog consistently closes in one press, without a second key.
 dialog.addEventListener('keydown',event=>{
  if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeGameHelp();return;}
  if(event.key!=='Tab')return;
  const controls=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),[tabindex="0"]')].filter(x=>!x.hidden&&x.getClientRects().length);
  const first=controls[0],last=controls.at(-1),active=document.activeElement;
  const next=event.shiftKey&&(active===first||!controls.includes(active))?last:!event.shiftKey&&(active===last||!controls.includes(active))?first:null;
  if(next){event.preventDefault();next.focus();}
 },true);
 dialog.addEventListener('close',()=>{if(!dialog.open)gameHelpSession=null;});
 screen.addEventListener('click',event=>{const button=event.target.closest('[data-help-topic]');if(button)openGameHelp(button.dataset.helpTopic,button);});
}
