// Static, owner-scoped help. Searching never quotes a plan, reconstructs a
// public view, reads rival information, or retains the campaign's large books.
const GAME_HELP_TOPICS=[
 {id:'planning',title:'Monthly planning and required decisions',words:'turn ready submit executive event blockers',tab:'operations',desk:'monthly',target:'#decisionGrid',text:'Choose the executive decision and review every required item in the monthly review. Optional opportunities and initiatives are not prerequisites for a turn. Mark Ready commits your plan; the month resolves only when both institutions are ready.'},
 {id:'value',title:'Enterprise value: how the campaign is scored',words:'score win winning value points lead result mandate bonus ranking',tab:'overview',target:'#myScore',text:'Enterprise value is the single number the campaign is judged on. It blends the balance sheet (deposits, loans and cash), the franchise (customers, business and merchant relationships, branch levels and market share) and the institution itself (capital, retained earnings, reputation, morale, staff, influence and completed research), then subtracts recorded risk, executive attention and accumulated credit losses. Career milestones each add a fixed amount. Your confidential mandate adds its bonus only at the end, and only if it is met, so a trailing score can still finish ahead. Every figure it uses is already visible on your own desks; nothing about the rival is inferred.'},
 {id:'changes',title:'Current policy, form edits and staged orders',words:'draft save apply preview undo cancel active commitment',tab:'overview',target:'#monthlyChangesDrawer',text:'Current policy is already in effect. Unfinished form edits are not orders: use their Preview and Stage controls where provided. Staged instructions belong to this month’s shared draft. Monthly changes compares that draft with its opening plan and offers individual undo where dependencies allow. Undo cannot cancel work completed in a previous month.'},
 {id:'funds',title:'Cash versus available spending room',words:'money budget discretionary reserve protected capital afford',tab:'overview',target:'#financialFundingDetails',text:'Bank cash is a balance, not a spending allowance. Planned commitments, protected reserves and capital constraints can make spendable funds much smaller. The shared monthly budget and financial explanation use the current draft; a subsidiary or parent balance is not automatically available to the bank.'},
 {id:'earnings',title:'Operating profit versus retained earnings',words:'income loss revenue equity capital accounting balance sheet results',tab:'overview',target:'#financialEarningsDetails',text:'Operating profit reports a month’s operating result. Retained earnings accumulate results and other equity-affecting movements; they are not cash. Where the campaign records a complete earnings bridge, it explains opening earnings, operating profit, other net changes and closing earnings. Missing historical detail is not reconstructed.'},
 {id:'forecasts',title:'Read the forecast without mistaking it for a result',words:'prediction estimate profit cost preview uncertainty outcome',tab:'operations',desk:'forecast',target:'#operatingPreview',text:'The operating forecast estimates the current draft under today’s economy. Rival actions, executive events and settlement conditions can change the outcome. Compare estimates with the next recorded result; do not add narrow product run rates to a whole-bank forecast that already includes them.'},
 {id:'allocation',title:'Allocate employees to departments',words:'staff headcount pool banker retail business lending operations unassigned',tab:'operations',desk:'monthly',target:'#staffGrid',text:'Allocation divides the existing shared staff pool among departments. Assigning every employee does not prove all work is covered. Where workforce and department work are enabled, training, reserves and other commitments reduce productive time; expertise affects particular work rather than creating extra people.'},
 {id:'coverage',title:'People: employees versus work coverage',words:'workforce staff capacity reservations quarter units shortage uncovered bottleneck service',requires:['workforce'],tab:'workforce',peopleDesk:'overview',target:'#peopleOverview',text:'People Overview separates headcount from available employee time and delivered work. Four quarter-time units equal one employee-month. Reservations and teaching time are not spare employees. Where department work is enabled, review uncovered tasks and their business consequences before deciding whether to reassign, recruit or reduce commitments.'},
 {id:'department-work',title:'Department work priorities and uncovered demand',words:'staff service capacity dispatch task objectives shortage',requires:['workforce','departmentFunctions'],tab:'workforce',peopleDesk:'coverage',target:'#departmentPanel',text:'Work coverage compares planned delivery with task demand. Moving time toward one task can leave another uncovered. Review the task’s actual consequence and shared time limit; the priority controls do not hire people or create capacity.'},
 {id:'recruitment',title:'Recruitment: signing cost and arrival timing',words:'hire generalist specialist salary payroll employee new banker',requires:['workforce'],tab:'workforce',peopleDesk:'recruitment',target:'#peopleRecruitment',text:'Generalists and specialists share the monthly hiring limit and spending room. The next-recruit quote is the extra signing cost, not the full future payroll. Staged recruits arrive next month; they cannot cover the work being settled now. Specialist expertise and recurring salary premiums differ from headcount.'},
 {id:'training',title:'Training, reserves and productive time',words:'workforce expertise development skill course teaching budget preview',requires:['workforce'],tab:'workforce',peopleDesk:'development',target:'#workforcePanel',text:'Training can improve skills but consumes funding and teaching time. Compare the staged plan with the form preview, including requested and effective limits, before staging it. Department ceilings and shared funding protection can restrict spending. Moving to another desk does not turn an unfinished form into an order.'},
 {id:'leadership',title:'Leadership, budgets and bounded delegation',words:'manager department leader compensation objectives training caps reserve automate',requires:['workforce','departmentOffice'],tab:'workforce',peopleDesk:'leadership',target:'#departmentPanel',text:'Leadership and budgets set organizational commitments and spending ceilings, not a second pool of employees or money. Review proposal changes and their whole-plan costs. Delegation works within supported limits; it does not authorize a manager to submit turns or make major strategic transactions for you.'},
 {id:'research',title:'Research is not the same as implementation',words:'strategy capability tree unlock specialization operating model build buy license partner',tab:'strategy',target:'#strategyTree',text:'Read each capability’s requirements, current level and available choices. Research can unlock a rollout or operating-model decision; it does not mean every related product is selling. Follow through to the relevant initiative or product route, then check completion and activation. Existing campaign versions retain their own strategy rules.'},
 {id:'projects',title:'Project progress and Operations capacity',words:'initiative stalled timing duration completion queue execution work units',tab:'operations',desk:'projects',target:'#activeProject',text:'Base work units are not a guaranteed number of calendar months. Shared Operations capacity, active commitments and campaign capabilities affect delivery. Review active progress and new initiative capacity together. Hiring for next month does not repair this month’s execution shortage.'},
 {id:'deposit-policy',title:'Deposit strategy and rate-sensitive funding',words:'pricing interest margin growth runoff cost savings bank funding',tab:'operations',desk:'funding',target:'#depositPolicies',text:'Aggressive deposit pricing trades funding cost and rate-sensitive exposure for acquisition strength. Repricing toward margin can cause runoff. Compare your current-book funding profile with the draft forecast; attracting deposits adds a liability as well as cash, not free profit.'},
 {id:'lending-policy',title:'Lending standards, return and delayed risk',words:'loan underwriting conservative growth credit loss risk appetite',tab:'operations',desk:'funding',target:'#lendingPolicies',text:'Lending standards change production and risk. More volume is not automatically better: loans consume funding and capital and can create future losses. The exact portfolio and credit controls depend on the campaign’s enabled systems. Use Credit when available to inspect recorded deterioration and collections.'},
 {id:'products',title:'Product development, deployment and retirement',words:'research build buy license lifecycle maintenance offer launch catalogue catalog',requires:['productPrograms'],tab:'products',productDesk:'development',target:'#productProgramsPanel',text:'Compare in-house development with licensing, including upfront cost, shared execution needs and ongoing vendor charges. Deployment opens supported sales choices; it does not create customer demand. Retirement closes new sales but does not erase existing balances or promises. Reopening can require another paid rollout.'},
 {id:'targeting',title:'Product sales targets by market and audience',words:'segment emphasis customers fit local product share demand',requires:['productPrograms'],tab:'products',productDesk:'targets',target:'#productProgramsPanel',text:'Local sales emphasis chooses which available offers compete for new demand. Fit is an acquisition-strength measure, not a win probability. Inspecting a product market does not change your action focus. Existing products and locked rates do not change merely because you edit sales emphasis.'},
 {id:'pricing',title:'Product pricing and protected balances',words:'tariff basis points interest variable guarantee locked annual rate',requires:['productPrograms'],version:['productPrograms',2],tab:'products',productDesk:'pricing',target:'#productProgramsPanel',text:'Pricing compares the current tariff with the staged offer on today’s account balances. Protected guarantees are distinct from variable balances. Direct product costs exclude shared bank expenses and loan income; the complete operating forecast is elsewhere. Basis-point adjustments are not percentage-point changes.'},
 {id:'advertising',title:'Advertising, acquisition and attribution',words:'marketing channel campaign awareness spending budget funnel conversion',requires:['productPrograms','advertising'],tab:'products',productDesk:'advertising',target:'#productProgramsPanel',text:'Advertising competes for finite outside demand; awareness is not an owned customer or deposit. Review spending, target audience and the attribution records available in this campaign. Product availability, service and acquisition capacity can constrain the response. Recorded attribution is not proof that every new account came from advertising.'},
 {id:'offers',title:'Compete for existing customer relationships',words:'share wallet retention relationship offer cross sell',requires:['productPrograms','relationshipOffers'],tab:'products',productDesk:'relationships',target:'#productProgramsPanel',text:'Existing-customer offers compete for supported relationships already in the market. Keep the offered benefit, cost and delivery capacity in view. Winning one product relationship does not establish ownership of every part of a customer’s finances. Campaigns without this preview do not provide this desk.'},
 {id:'onboarding',title:'Applications are not yet activated accounts',words:'pending intake queue expiry abandonment delay staff service customer deposit',requires:['productPrograms','onboarding'],tab:'products',productDesk:'onboarding',target:'#productProgramsPanel',text:'Pending applications are requests, not bank-owned customers or deposits. Activation requires eligible work and capacity; requests can expire or be abandoned. Review the queue, staffing and actual activation results before increasing intake. Do not count pending principal as available bank funding.'},
 {id:'customers',title:'Service and retention of existing households',words:'relationships churn loyalty wallet deposits service coverage',requires:['householdBook'],tab:'customers',householdDesk:'service',target:'#householdPanel',text:'Customers shows the supported household relationships and retention controls in your campaign. Service capacity and commitments affect the existing book, not just acquisition. Review market-level exposure and the actual recorded customer effects instead of assuming influence means ownership.'},
 {id:'credit',title:'Arrears, collections and credit history',words:'delinquency vintages cohort cure recover charge off losses loans',requires:['creditPerformance'],tab:'credit',target:'#creditPanel',text:'Follow the recorded loan portfolio and supported collections actions. Amounts entering arrears, cured, recovered and lost are different flows; subtracting only two of them is not a complete delinquency bridge. A strong current profit can coexist with deteriorating future credit quality.'},
 {id:'facilities',title:'Facilities: local reach and operating commitments',words:'branch network office location micro retail commercial hub wealth upgrade capacity staff',requires:['facilityNetwork'],tab:'markets',target:'#facilityNetworkPanel',text:'Compare the available facility types, local capacity and operating commitments. Physical capacity is not a supply of employees. A larger location can need additional staff or department support to use its potential. Existing campaign options determine which facility types and controls are available.'},
 {id:'maintenance',title:'Facility condition, renovation and conversion',words:'repair upkeep maintenance wear branch office upgrade closure',requires:['facilityLifecycle'],tab:'markets',target:'#facilityLifecyclePanel',text:'Inspect the location’s condition and ongoing work before staging maintenance or a conversion. These choices have costs and persistent consequences; a conversion is not an instant free upgrade. Review shared protected spending and the facility’s staffing needs along with its proposed new role.'},
 {id:'influence',title:'Market influence is not deposit ownership',words:'map conquered territory district control share domination competition focus',tab:'markets',target:'#marketMap',text:'The map’s influence/control measure is distinct from actual customer and deposit books. Check the available market books before treating a controlled area as exclusive ownership. In the current map, selecting a district sets the plan’s focus; check that target again before staging a local action.'},
 {id:'renewals',title:'Corporate service contracts and renewals',words:'treasury merchant pricing bid client agreement company service expiry',requires:['serviceDesk'],tab:'markets',target:'#servicePricing',text:'Review your owned agreements, service capacity, renewal timing and bids. An incumbent can defend a renewal without manually bidding in every month; new orders should be deliberate. Company ownership is separate from its banking-provider relationship.'},
 {id:'competition',title:'Concealed actions, defenses and public intelligence',words:'rival attack raid deposit campaign poach counter target',tab:'competition',target:'#competitiveActions',text:'Choose among the actions supported by your campaign and review their target, cost and counter. Plans resolve simultaneously; a rival’s last revealed action is not their next plan. Neither this help nor the forecast reveals private rival instructions. No action is selected merely by opening this desk.'},
 {id:'group',title:'Financial Group: parent versus bank resources',words:'subsidiary capital dividend injection cash equity consolidated transfer',requires:['financialGroup'],tab:'group',target:'#financialGroupPanel',text:'Parent, bank and subsidiary resources are separate. Group consolidation removes internal investments to avoid double-counting. Explicit transfers remain subject to safeguards and settlement timing; parent cash is not automatic bank spending room. Review each subsidiary’s supported operating results and funding needs.'},
 {id:'agency',title:'Insurance agency is not underwriting',words:'subsidiary carrier commission insurance premium policies coverage group',requires:['financialGroup','agency'],tab:'group',groupDesk:'agency',target:'#financialGroupPanel',text:'The agency distributes third-party carrier products and earns commissions; it does not assume insurance underwriting risk. Review its own staffing, expenses, relationships and cash requirements. Agency and bank resources are not interchangeable without supported explicit transfers.'},
 {id:'history',title:'Actual results, history and public scorecard',words:'last month debrief log trend performance intelligence milestones',tab:'intelligence',target:'#lastResolution',text:'Read recorded outcomes after resolution and compare them with your planning estimates. Available history is limited by the campaign version and retained records; absent periods are not synthesized. Public rival metrics do not include their private pending orders or customer queues.'},
 {id:'connection',title:'Connection health, readiness and safe recovery',words:'multiplayer github lan intranet direct link reconnect acknowledgement yellow retry sync',tab:'overview',target:'#linkState',text:'A connection indicator and the two readiness states describe different things. A local click alone is not proof that a remote plan was acknowledged. Follow the current transport’s recovery message and keep one tab per player. Do not start a replacement campaign to repair an interrupted room; preserve the existing checkpoint and use supported reconnect/resume controls.'},
 {id:'export',title:'Export, Continue and private session recovery',words:'save backup download import persistence storage token credentials',tab:'overview',target:'#exportBtn',text:'Use the supported Export control for a portable campaign snapshot when available. Continue uses this browser’s local campaign; it is not a substitute for the room’s multiplayer checkpoint. Keep credentials and private campaign files private. A download is not verified until you can reopen the intended campaign from it.'},
 {id:'optional',title:'Optional previews and fixed campaign rules',words:'feature checkbox complexity settings prerequisites modular disabled lobby',tab:'overview',target:'#scopeName',text:'Optional systems and their dependencies are chosen before play. The host applies shared lobby settings and both players confirm readiness. Existing campaigns retain their supported rules; help cannot enable a missing preview or upgrade a save. Changing presentation is different from changing simulation rules.'}
];
const gameHelpBound=new WeakSet();
let gameHelpSession=null;
function gameHelpProfile(v){
 const features={};
 for(const topic of GAME_HELP_TOPICS)for(const key of topic.requires||[])features[key]=!!v.me[key];
 return {features,productPricingVersion:v.me.productPrograms?.version||0};
}
function gameHelpAvailable(topic,profile){return (topic.requires||[]).every(key=>profile.features[key])&&(!topic.version||profile.productPricingVersion===topic.version[1]);}
function searchGameHelp(query,profile,tab){
 const terms=String(query).slice(0,200).toLocaleLowerCase('en-US').trim().split(/\s+/).filter(Boolean);
 return GAME_HELP_TOPICS.map((topic,index)=>({topic,index,available:gameHelpAvailable(topic,profile)})).filter(({topic})=>{
  const haystack=(topic.id+' '+topic.title+' '+topic.words+' '+topic.text).toLocaleLowerCase('en-US');return terms.every(term=>haystack.includes(term));
 }).sort((a,b)=>Number(b.available)-Number(a.available)||Number(b.topic.tab===tab)-Number(a.topic.tab===tab)||a.index-b.index);
}
function gameHelpCurrent(){
 return !!gameHelpSession&&(game||view)===gameHelpSession.campaign&&draftOwner===gameHelpSession.owner&&lastCycle===gameHelpSession.cycle&&seat===gameHelpSession.seat&&featureConnectionGeneration===gameHelpSession.connection;
}
function closeGameHelp(restore=true){
 const dialog=$('#gameHelp'),session=gameHelpSession,current=gameHelpCurrent();gameHelpSession=null;
 if(dialog?.open)dialog.close();
 if(restore&&current){const target=session?.opener?.isConnected?session.opener:$('#gameHelpOpen');target?.focus?.({preventScroll:true});}
}
function renderGameHelp(){
 if(!gameHelpCurrent()){closeGameHelp(false);return;}
 const results=searchGameHelp($('#gameHelpSearch').value,gameHelpSession.profile,gameHelpSession.tab),mount=$('#gameHelpResults');
 $('#gameHelpCount').textContent=results.length+' '+(results.length===1?'topic':'topics')+'. Explanations and navigation only; no orders are changed.';
 mount.innerHTML=results.length?results.map(({topic,available})=>'<article class="game-help-topic"><h3>'+esc(topic.title)+'</h3><p>'+esc(topic.text)+'</p><p class="micro muted">'+(available?'Available in this campaign.':'Not enabled in this campaign version. This explanation does not add the system.')+'</p><button type="button" class="btn" data-help-open="'+topic.id+'" '+(available?'':'disabled')+' aria-label="Open controls: '+esc(topic.title)+'">'+(available?'Open controls':'Unavailable in this campaign')+'</button></article>').join(''):'<p>No matching topics. Try “staff”, “cash”, “research”, “applications” or “connection”. Search uses all entered words.</p>';
 mount.scrollTop=0;
}
function openGameHelp(topicId,opener){
 const v=currentView(),dialog=$('#gameHelp');if(!v||!dialog||draftOwner!==v.me.id||lastCycle!==v.cycle)return;
 gameHelpSession={campaign:game||view,owner:v.me.id,cycle:v.cycle,seat,connection:featureConnectionGeneration,profile:gameHelpProfile(v),tab:workspaceTab,opener:opener||document.activeElement};
 const topic=GAME_HELP_TOPICS.find(x=>x.id===topicId);$('#gameHelpSearch').value=topic?topic.title:'';
 renderGameHelp();if(!dialog.open)dialog.showModal();$('#gameHelpSearch').focus();$('#gameHelpSearch').select();
}
function navigateGameHelp(id){
 if(!gameHelpCurrent()){closeGameHelp(false);return false;}
 const topic=GAME_HELP_TOPICS.find(x=>x.id===id);if(!topic||!gameHelpAvailable(topic,gameHelpSession.profile))return false;
 closeGameHelp(false);
 if(topic.productDesk)productDeskView=topic.productDesk;
 navigateBankOverview(topic);if(topic.groupDesk)setFinancialGroupDesk(topic.groupDesk,{focus:true});return true;
}
function reconcileGameHelp(){
 const dialog=$('#gameHelp'),screen=$('#gameScreen');if(!dialog||!screen)return;
 if(gameHelpSession&&!gameHelpCurrent())closeGameHelp(false);
 if(gameHelpBound.has(dialog))return;gameHelpBound.add(dialog);
 $('#gameHelpOpen').addEventListener('click',event=>openGameHelp(null,event.currentTarget));
 $('#gameHelpClose').addEventListener('click',()=>closeGameHelp());
 $('#gameHelpSearch').addEventListener('input',renderGameHelp);
 $('#gameHelpResults').addEventListener('click',event=>{const button=event.target.closest('[data-help-open]');if(button&&!button.disabled)navigateGameHelp(button.dataset.helpOpen);});
 dialog.addEventListener('cancel',event=>{event.preventDefault();closeGameHelp();});
 // Native search inputs otherwise consume the first Escape to clear their
 // text. The dialog consistently closes in one press, without a second key.
 dialog.addEventListener('keydown',event=>{
  if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeGameHelp();return;}
  if(event.key!=='Tab')return;
  const controls=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),[tabindex="0"]')].filter(x=>!x.hidden&&x.getClientRects().length);
  const first=controls[0],last=controls.at(-1),active=document.activeElement;
  const next=event.shiftKey&&(active===first||!controls.includes(active))?last:!event.shiftKey&&(active===last||!controls.includes(active))?first:null;
  if(next){event.preventDefault();next.focus();}
 },true);
 dialog.addEventListener('close',()=>{if(!dialog.open)gameHelpSession=null;});
 screen.addEventListener('click',event=>{const button=event.target.closest('[data-help-topic]');if(button)openGameHelp(button.dataset.helpTopic,button);});
}
