// One ownership editor over the current monthly draft. Quotes use parent books;
// neither the cosmetic score ticker nor customer custody funds shares.
function renderHoldingCapital(v,route,mount){
 if(v.expandedBusinessVersion!==1){mount.innerHTML=financeNote('Holding-company issuance and repurchases require a new Expanded 9.36 campaign. This save retains its existing ownership rules.');return;}
 const rows=v.holdingCapitalSnapshot.issuers,own=rows.find(i=>i.id===v.me.id),rival=rows.find(i=>i.id===v.rival.id),context=financeContext(route),records=[{id:'capital',name:'Your holding company',detail:'Issue capital or repurchase outstanding shares'},{id:'rival',name:'Rival holding-company shares',detail:'Voluntary purchases and sales; parent funds only'}];
 financeLayout(v,route,mount,records,context.objectId||'capital','Ownership & capital',(record,detail)=>{
  const issuer=record.id==='capital'?own:rival,prices=E.HoldingCapital.quotes(issuer),policy=draft.holdingCapitalOrders||E.HoldingCapital.defaults(v.me),isOwn=record.id==='capital';
  const title=isOwn?v.me.name+' holding company':v.rival.name+' holding company',pct=n=>(100*n/issuer.issued).toFixed(2)+'%';
  const body=financeTable(['Holder','Shares','Ownership'],[['Founder',issuer.founderShares,pct(issuer.founderShares)],['Outside investors',issuer.outsideShares,pct(issuer.outsideShares)],[isOwn?'Rival holding company':'Your holding company',issuer.rivalShares,pct(issuer.rivalShares)]])+financeNote('Shares belong to the parent holding company. They are separate from bank deposits, customer investment accounts and the securities held in Treasury. Founder voting control stays at least 51%.')+financeNote('Outside liquidity is limited to '+E.HoldingCapital.RULES.outsideMonthly.toLocaleString()+' shares per issuer per month, with a spread. Human holders sell only through an explicit sell order. No guaranteed fill or reversal at an old price.');
  const editor=financeInspector(detail,v,{title,subtitle:isOwn?'Fund the parent or retire willingly sold shares. Bank capital changes only through a separate reviewed support instruction.':'Trade the rival parent’s shares using unreserved parent cash.',facts:[['Issued shares',issuer.issued.toLocaleString()],['Current reference',financePrice(issuer.referenceCents)],['Outside buy quote',financePrice(prices.sell)],['Outside sell / repurchase quote',financePrice(prices.buy)],['Your parent cash',financeMoney(v.me.financialGroup.parent.accounts.cash)],['Bank cash · unchanged by shares',financeMoney(v.me.stats.cash)]],body});
  const initial=financeCopy(isOwn?policy.capital:policy.rival);if((isOwn?initial.action:initial.side)==='none')initial.limitCents=isOwn?prices.issue:prices.buy;initial.price=initial.limitCents/100;delete initial.limitCents;
  financeEdit(v,editor,{key:'holding-'+record.id,initial,fields:[{path:isOwn?'action':'side',label:isOwn?'Capital instruction':'Your voluntary order',choices:isOwn?[['none','No capital order'],['issue','Issue new shares'],['repurchase','Repurchase and retire']]:[['none','No trade'],['buy','Buy rival shares'],['sell','Sell your holding']]},{path:'shares',label:'Whole shares (zero for no order)',min:0,max:E.HoldingCapital.RULES.monthlyShares},{path:'price',label:'Limit dollars per share',min:.01,max:E.HoldingCapital.RULES.maxPriceCents/100,step:.01}],build:(now,f,candidate)=>{
   if(Math.abs(f.price*100-Math.round(f.price*100))>1e-7)throw Error('Use a share price with at most two decimal places.');
   candidate.holdingCapitalOrders=candidate.holdingCapitalOrders||E.HoldingCapital.defaults(now.me);candidate.holdingCapitalOrders[isOwn?'capital':'rival']={...f,limitCents:Math.round(f.price*100)};delete candidate.holdingCapitalOrders[isOwn?'capital':'rival'].price;
   if((isOwn?f.action:f.side)==='none')candidate.holdingCapitalOrders[isOwn?'capital':'rival'].shares=0;
   const q=E.HoldingCapital.quote(now,now.me,candidate);
   return {candidate,facts:[['Protected parent cash / other commitments',financeMoney(q.protectedCash)],['Maximum purchase reservation',financeMoney(q.spend)],['Available after reservations',financeMoney(q.remaining)],['Parent cash · conditional share orders',financeMoney(q.parentCash)+' → '+financeMoney(q.parentCashAfter)],['Parent equity · conditional share orders',financeMoney(q.parentEquity)+' → '+financeMoney(q.parentEquityAfter)],...(isOwn?[['Founder voting ownership if fully filled',q.founderBefore.toFixed(2)+'% → '+q.founderAfter.toFixed(2)+'%'],['Outstanding shares if fully filled',q.own.issued.toLocaleString()+' → '+q.issuedAfter.toLocaleString()]]:[['Your rival holding if filled',q.rivalSharesBefore.toLocaleString()+' → '+q.rivalSharesAfter.toLocaleString()],['Rival ownership at current share count',q.rivalOwnershipBefore.toFixed(2)+'% → '+q.rivalOwnershipAfter.toFixed(2)+'%'],['Realized gain / loss if sold',financeMoney(q.realizedGain)]]),['Bank capital · unchanged',financeMoney(q.bankCapital)]],notes:[q.note,q.conditionalEffects.note,...(q.conditionalEffects.rivalPrimaryOnly?['This limit requires a voluntary matching rival capital instruction; outside quotes alone cannot fill it.']:[]),'Exact receipts appear after settlement. Future sale proceeds and newly issued capital cannot fund other purchases in this same plan.']};
  }});
  const stage=$('#financeStage');if(stage)stage.textContent=isOwn?'Stage capital instruction':'Stage voluntary share order';
 });
}
