$('#regionalGrowthPreview').addEventListener('change',()=>{if($('#regionalGrowthPreview').checked)for(const id of ['#advertisingPreview','#productPrograms','#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#advertisingPreview','#productPrograms','#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#regionalGrowthPreview').checked=false});

$('#advertisingPreview').addEventListener('change',()=>{if($('#advertisingPreview').checked)for(const id of ['#productPrograms','#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#productPrograms','#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#advertisingPreview').checked=false});
$('#productPrograms').addEventListener('change',()=>{if($('#productPrograms').checked)for(const id of ['#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#segmentDeposits','#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#productPrograms').checked=false});
$('#serviceExpansion').addEventListener('change',()=>{if($('#serviceExpansion').checked)$('#rivalryPilot').checked=true;else $('#institutionManagement').checked=false});
$('#customerNeeds').addEventListener('change',()=>{if($('#customerNeeds').checked){$('#institutionManagement').checked=true;$('#serviceExpansion').checked=true;$('#rivalryPilot').checked=true}});
$('#institutionManagement').addEventListener('change',()=>{if($('#institutionManagement').checked){$('#serviceExpansion').checked=true;$('#rivalryPilot').checked=true}});
$('#specialistWorkforce').addEventListener('change',()=>{if($('#specialistWorkforce').checked){$('#customerNeeds').checked=true;$('#institutionManagement').checked=true;$('#serviceExpansion').checked=true;$('#rivalryPilot').checked=true}});
for(const id of ['#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#specialistWorkforce').checked=false});
$('#householdOwnership').addEventListener('change',()=>{if($('#householdOwnership').checked)for(const id of ['#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#householdOwnership').checked=false});
$('#creditPerformance').addEventListener('change',()=>{if($('#creditPerformance').checked)for(const id of ['#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#creditPerformance').checked=false});
$('#segmentDeposits').addEventListener('change',()=>{if($('#segmentDeposits').checked)for(const id of ['#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).checked=true});
for(const id of ['#creditPerformance','#householdOwnership','#specialistWorkforce','#customerNeeds','#institutionManagement','#serviceExpansion','#rivalryPilot'])$(id).addEventListener('change',()=>{if(!$(id).checked)$('#segmentDeposits').checked=false});
function startLocal(which){try{game=which==='ai'?E.createGame({regionalGrowthVersion:$('#regionalGrowthPreview').checked?1:0,advertisingVersion:$('#advertisingPreview').checked?1:0,productProgramsVersion:$('#productPrograms').checked?1:0,segmentDepositsVersion:$('#segmentDeposits').checked?1:0,creditPerformanceVersion:$('#creditPerformance').checked?1:0,customerOwnershipVersion:$('#householdOwnership').checked?1:0,workforceVersion:$('#specialistWorkforce').checked?1:0,customerDemandVersion:$('#customerNeeds').checked?2:0,managementVersion:$('#institutionManagement').checked?2:0,serviceExpansionVersion:$('#serviceExpansion').checked?1:0,campaignRulesVersion:$('#rivalryPilot').checked?1:undefined,color1:$('#bankColor1').value,color2:$('#bankColor2').value,mode:'ai',name1:validName('#aiName'),name2:'Synergy Holdings AI',scope:$('#aiScope').value,scenario:$('#aiScenario').value,difficulty:$('#aiDifficulty').value}):E.createGame({regionalGrowthVersion:$('#regionalGrowthPreview').checked?1:0,advertisingVersion:$('#advertisingPreview').checked?1:0,productProgramsVersion:$('#productPrograms').checked?1:0,segmentDepositsVersion:$('#segmentDeposits').checked?1:0,creditPerformanceVersion:$('#creditPerformance').checked?1:0,customerOwnershipVersion:$('#householdOwnership').checked?1:0,workforceVersion:$('#specialistWorkforce').checked?1:0,customerDemandVersion:$('#customerNeeds').checked?2:0,managementVersion:$('#institutionManagement').checked?2:0,serviceExpansionVersion:$('#serviceExpansion').checked?1:0,campaignRulesVersion:$('#rivalryPilot').checked?1:undefined,color1:$('#bankColor1').value,color2:$('#bankColor2').value,mode:'hotseat',name1:validName('#hotName1'),name2:validName('#hotName2'),scope:$('#hotScope').value,scenario:$('#hotScenario').value,difficulty:'vp'});mode=which;seat=0;draft=null;lastCycle=0;lastResolutionId=0;saveLocal();enterGame(true)}catch(e){setStartMessage(e.message)}}
function continueSave(){try{game=migrateGame(savedGame());if(['lan','p2p'].includes(game.mode))game.mode='hotseat';mode=game.mode;seat=0;draft=null;lastCycle=0;lastResolutionId=game.resolutionId||0;saveLocal();if(game.mode==='hotseat'&&game.players[0].submitted&&!game.players[1].submitted){show('#gameScreen');showPrivacy(1,`PASS COMPUTER TO ${game.players[1].name}`,`${game.players[0].name}'s saved plan is sealed.`)}else enterGame(true)}catch(e){setStartMessage(e.message)}}
function importSave(file){const r=new FileReader;r.onload=()=>{try{const g=migrateGame(JSON.parse(r.result));if(['p2p','lan'].includes(g.mode))g.mode='hotseat';game=g;mode=g.mode;seat=0;draft=null;lastCycle=0;lastResolutionId=g.resolutionId||0;saveLocal();enterGame(true);toast('Campaign imported.')}catch(e){setStartMessage(e.message)}};r.readAsText(file)}
function exportSave(){if(p2pRole==='guest'){toast('Only the multiplayer host can export the authoritative save.');return}if(!game)return;const blob=new Blob([JSON.stringify(game,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Branch_Wars_Cycle_${game.cycle}_Save.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function enterGame(suppressReplay=false){show('#gameScreen');const v=currentView();if(suppressReplay&&v)lastResolutionId=v.resolutionId||0;render()}
function leaveGame(){resetLink();clearTimeout(gh.retryTimer);gh=emptyGh();lan.active=false;clearTimeout(lan.retryTimer);lan=emptyLan();game=null;view=null;p2pRole='';draft=null;draftOwner='';lastCycle=0;lastResolutionId=0;show('#startScreen');updateContinue()}
