let managementNotes=[];
function renderManagement(v){
 const old=$('#institutionControls'),open=old?.open;if(old)old.remove();if(!v.me.management)return;
 if(!draft.management)draft.management=JSON.parse(JSON.stringify(v.me.management));
 const m=draft.management,r=m.research,d=m.delivery,disabled=v.me.submitted?'disabled':'';
 const select=(id,label,value,choices)=>{const options=choices.some(([k])=>String(k)===String(value))?choices:[...choices,[value,'Saved value: '+value]];return '<label class="micro">'+label+' <select id="'+id+'" '+disabled+'>'+options.map(([k,n])=>'<option value="'+k+'" '+(String(value)===String(k)?'selected':'')+'>'+esc(n)+'</option>').join('')+'</select></label>'};
 const rows=r.priority.map(k=>'<tr><th>'+esc(E.STRATEGY_BRANCHES[k].name)+'</th><td>'+select('target-'+k,'Stop at',r.targets[k],[[0,'Do not fund'],[1,'Tier 1'],[2,'Tier 2'],[3,'Tier 3'],[4,'Tier 4']])+'</td><td>'+money(draft.investments[k]||0)+'</td></tr>').join('');
 $('#strategyTree').insertAdjacentHTML('beforebegin','<details id="institutionControls"><summary>RECURRING RESEARCH & SERVICE MANAGER</summary><p class="micro">Standing mandates prepare the next turn draft. Nothing is spent until you approve that draft. Manual edits win; managers never change a locked plan. Saving limits below affects future drafts; use Prepare draft to apply them now.</p><div class="pipeline">'+select('research-enabled','Recurring research',r.enabled?'on':'off',[['off','Paused'],['on','Enabled']])+select('research-budget','Total monthly budget',r.budget,[0,25000,50000,100000,150000,250000].map(x=>[x,money(x)]))+select('research-reserve','Minimum cash after commitments',r.reserve,[0,250000,500000,1000000,2000000].map(x=>[x,money(x)]))+select('research-priority','First priority',r.priority[0],Object.entries(E.STRATEGY_BRANCHES).map(([k,x])=>[k,x.name]))+'</div><div class="table-scroll"><table class="regional-table"><thead><tr><th>Priority order</th><th>Milestone ceiling</th><th>Staged this turn</th></tr></thead><tbody>'+rows+'</tbody></table></div><p class="micro muted">Uses the total budget in displayed priority order, stops at each selected tier, and preserves existing commitments plus the cash and advisory capital reserves. Unspent money stays in the bank. Amounts round down to $1K. Research does not deploy or activate applications.</p><h3>SERVICE DEPARTMENT MANDATE</h3><div class="pipeline">'+select('manager-mode','Capacity priority',d.mode,[['manual','Manual'],['profit','Current bank profit'],['inhouse','Minimize vendor use']])+select('manager-staff','Maximum reserved bankers',d.staffLimit,Array.from({length:Math.max(8,d.staffLimit)+1},(_,x)=>[x,String(x)]))+select('manager-vendor','Maximum vendor points',d.vendorLimit,[0,1,2,3,4].map(x=>[x,x+' points · '+money(x*6000)+'/turn']))+select('manager-sales','Keep Business bankers in sales',d.salesFloor,Array.from({length:Math.max(8,d.salesFloor)+1},(_,x)=>[x,String(x)]))+'</div><p class="micro muted">Only allocates existing Business staff and vendors to the signed service book. No hiring, bidding, price changes or platform activation. If no feasible mix fits, current capacity is retained and an exception is shown. An explicit bid pauses delivery automation. Limits govern new suggestions, not forced cancellation of existing obligations. Compare economics in Markets.</p><button type="button" id="prepareManagement" class="btn" '+disabled+'>Prepare draft within these limits</button><p class="micro" id="managementNotes">'+managementNotes.map(esc).join('<br>')+'</p></details>');
 if(open)$('#institutionControls').open=true;
 const update=()=>{r.enabled=$('#research-enabled').value==='on';r.budget=Number($('#research-budget').value);r.reserve=Number($('#research-reserve').value);const first=$('#research-priority').value;r.priority=[first,...r.priority.filter(k=>k!==first)];for(const k of r.priority)r.targets[k]=Number($('#target-'+k).value);d.mode=$('#manager-mode').value;d.staffLimit=Number($('#manager-staff').value);d.vendorLimit=Number($('#manager-vendor').value);d.salesFloor=Number($('#manager-sales').value);managementNotes=['Limits staged. Prepare the current draft explicitly, or they will apply to the next turn after you lock this plan.'];renderProjects(v);renderReady(v)};
 $$('#institutionControls select').forEach(el=>el.addEventListener('change',update));
 $('#prepareManagement').addEventListener('click',()=>{const prepared=E.managementPlan({...v.me,focus:draft.focus},draft,v.economy);draft=prepared.plan;managementNotes=prepared.notes.length?prepared.notes:['No automatic changes: mandates are paused or existing commitments already fill the budget.'];renderProjects(v);renderReady(v)});
}
const institutionProjectsUI=renderProjects;
renderProjects=function(v){institutionProjectsUI(v);renderManagement(v)};


function renderRelationshipDossiers(v){
 if(!v.relationshipRecords)return;
 const owner=id=>id===v.me.id?v.me.name:id===v.rival.id?v.rival.name:'Outside providers';
 const details=v.serviceAgreements.map(c=>{
  const r=v.relationshipRecords[c.id],f=E.clientProfile(c),bonus=E.relationshipBonus(v,{id:c.owner},c);
  return '<details><summary>'+esc(f.name)+' · '+esc(v.territories[c.market].name)+' · '+esc(E.SERVICE_TYPES[c.kind].name)+'</summary><p class="micro">Current provider: '+esc(owner(c.owner))+' · '+r.streak+'/8 consecutive serviced turns · earned incumbent strength +'+bonus.toFixed(2)+'. Next renewal '+c.due+'.</p><div class="table-scroll"><table class="regional-table"><thead><tr><th>Month</th><th>Servicing provider</th><th>Delivery</th><th>Signed fee then</th><th>Provider after contest</th></tr></thead><tbody>'+r.history.slice().reverse().map(e=>'<tr><td>'+e.cycle+'</td><td>'+esc(owner(e.from))+'</td><td>'+(e.served===null?'Outside record unavailable':e.served?'Serviced':'Missed')+'</td><td>'+money(e.fee)+'</td><td>'+esc(owner(e.to))+(e.renewal?' · renewal':'')+'</td></tr>').join('')+'</tbody></table></div>'+(r.history.length?'':'<p class="micro">No completed service month yet.</p>')+'</details>';
 }).join('');
 $('#pipeline').insertAdjacentHTML('beforeend','<section style="grid-column:1/-1"><details id="clientDossiers"><summary>CLIENT RELATIONSHIPS · LAST 12 MONTHS</summary><p class="micro">Reliable delivery earns +0.25 incumbent bid strength per consecutive month, capped at +2. A missed month or provider change resets it. This is additional to the existing incumbent and client-preference adjustments. Rivals can counter with price, capability, local presence and advertising; renewal is never guaranteed. Histories are public in this pilot. Fees shown are signed service terms, not deposit balances or guaranteed profit.</p>'+details+'</details></section>');
}
function renderDepartmentScorecard(v){
 if(!v.me.serviceDesk)return;
 const issue=departmentForecastIssue(v);
 if(issue){$('#pipeline').insertAdjacentHTML('beforeend',departmentForecastNotice(issue));return;}
 const s=E.departmentScorecard({...v.me,focus:draft.focus},draft,v.economy),load=s.service,latest=v.operatingEvents?.at(-1),actual=latest?.report;
 const rows=s.departments.map(d=>'<tr><th>'+esc(d.name)+'</th><td>'+d.current+'</td><td>'+d.planned+'</td></tr>').join('');
 $('#pipeline').insertAdjacentHTML('beforeend','<section style="grid-column:1/-1"><details id="departmentScorecard"><summary>DEPARTMENT WORKLOAD & DELIVERY ECONOMICS</summary><div class="table-scroll"><table class="regional-table"><thead><tr><th>Department</th><th>Standing staff</th><th>Draft staff</th></tr></thead><tbody>'+rows+'</tbody></table></div><p class="micro">Service desk: '+load.demand+' required points / '+load.capacity+' available · '+load.served+'/'+load.count+' mandates fully supported · '+load.sales+' Business bankers left in sales.</p><p class="micro">Draft desk fees '+money(load.fees)+' − direct service '+money(load.direct)+' − vendors '+money(load.vendors)+' − platforms '+money(load.platform)+' = <b>'+money(load.net)+'</b> before shared payroll.</p><p class="micro">Executive project load '+s.execution.load.toFixed(1)+' / '+s.execution.capacity.toFixed(1)+' · research commitments '+money(s.research)+' · recruitment '+money(s.recruiting)+'. Project-delivery capacity is separate from service capacity.</p><p class="micro">Bank-wide operating forecast after funding-sale losses: '+money(s.bankProfit)+'. Includes desk economics: do not add desk net again. Does not include discretionary commitments, executive events or rival actions.</p>'+(actual?'<p class="micro">Last completed month '+latest.cycle+': realized desk fees '+money(actual.contractFees||0)+' − delivery costs '+money(actual.contractServicing||0)+' = '+money((actual.contractFees||0)-(actual.contractServicing||0))+' before shared payroll. The latest result and the new draft cover different months; this is not a forecast-error comparison.</p>':'<p class="micro">Realized delivery economics appear after the first completed month.</p>')+'<p class="micro muted">No fabricated departmental profit allocation: shared payroll, central costs and credit losses remain bank-wide. '+(v.me.workforce?'Specialist premiums and training are bank-wide expenses; inspect the Workforce workspace. Named department leaders remain future work.':'Training budgets, specialist workloads and named department leaders are still future work.')+'</p></details></section>');
}
const relationshipPipelineUI=renderPipeline;
renderPipeline=function(v){const dossier=$('#clientDossiers')?.open,score=$('#departmentScorecard')?.open;relationshipPipelineUI(v);renderRelationshipDossiers(v);renderDepartmentScorecard(v);if(dossier&&$('#clientDossiers'))$('#clientDossiers').open=true;if(score&&$('#departmentScorecard'))$('#departmentScorecard').open=true};
