// Scenario and review state are presentation-only. Only Stage changes the one
// shared draft; callbacks are tied to the owner, month and connection identity.
let monetaryDesk={context:null,change:50,review:null,open:false};
function monetaryDeskCurrent(context,v=currentView()){
 return !!(context&&v&&context.campaign===presentationCampaignIdentity(v)&&context.owner===v.me.id&&context.cycle===v.cycle&&context.attempt===connectionAttempt&&context.connection===featureConnectionGeneration&&context.link===linkSession&&context.repository===gh&&context.lan===lan);
}
function renderMonetaryPolicy(v){
 const mount=$('#monetaryPolicyDesk');if(!mount)return;
 mount.hidden=v.monetaryPolicyVersion!==1;if(mount.hidden){mount.innerHTML='';monetaryDesk.context=null;return;}
 if(!monetaryDeskCurrent(monetaryDesk.context,v))monetaryDesk={context:{campaign:presentationCampaignIdentity(v),owner:v.me.id,cycle:v.cycle,attempt:connectionAttempt,connection:featureConnectionGeneration,link:linkSession,repository:gh,lan},change:50,review:null,open:false};
 const context=monetaryDesk.context,m=v.monetaryPolicy,p=v.me,locked=!!(p.submitted||v.gameOver),q=E.MonetaryPolicy.quote(p,v,monetaryDesk.change,draft),last=m.history.at(-1),fmt=overviewDollars;
 const rate=bp=>(bp/100).toFixed(2)+'%',range=bp=>rate(bp-25)+'–'+rate(bp),signed=n=>(n>0?'+':'')+fmt(n);
 const outlook={expansion:'Growth raises the chance of a hike.',steady:'A hold is the most likely decision.',tight:'Inflation pressure favors hikes.',downturn:'Weak conditions favor cuts.',recovery:'A hold is most likely, with cuts still possible.'}[v.economy.key];
 const rows=[['Loan interest','loanInterest'],['Securities interest','securitiesInterest'],['Deposit expense','depositExpense'],['Emergency borrowing expense','borrowingExpense'],['Net interest income','netInterest']];
 mount.innerHTML=`<header class="section-head"><div><h2>FEDERAL FUNDS & YOUR BANK</h2><p class="small">Target range <b>${range(m.upperBp)}</b> · next decision <b>month ${m.nextDecision}</b></p></div><span class="micro">${last?'Last decision: month '+last.cycle+' · '+(last.changeBp===0?'held':(last.changeBp>0?'+':'')+last.changeBp+' bp'):'Opening rate · no decisions yet'}</span><button type="button" class="btn" id="inspectRateImpact" aria-expanded="${monetaryDesk.open}" aria-controls="rateImpactWorkspace">${monetaryDesk.open?'Close rate desk':'Inspect bank impact'}</button></header>
  <p class="small muted">${esc(outlook)} The decision is published before planning and stays fixed throughout the month. One basis point (bp) is 0.01 percentage point.</p>
  <div id="rateImpactWorkspace" ${monetaryDesk.open?'':'hidden'}><div class="rate-desk-grid"><div><h3>IF RATES CHANGE</h3><div class="rate-scenarios" role="group" aria-label="Rate comparison">${[-50,0,50,100].map(n=>`<button type="button" class="btn ${monetaryDesk.change===n?'active':''}" data-rate-scenario="${n}" aria-pressed="${monetaryDesk.change===n}">${n===0?'Current':(n>0?'+':'')+n+' bp'}</button>`).join('')}</div>
  <p class="micro">Scenario anchor ${rate(q.scenarioBp)} · hypothetical comparison, not a Fed instruction.</p>
  <div class="rate-table-scroll"><table class="rate-table"><caption>Monthly interest on your current balances and draft deposit prices</caption><thead><tr><th scope="col">Bank income / expense</th><th scope="col">Current</th><th scope="col">Scenario</th><th scope="col">Change</th></tr></thead><tbody>${rows.map(([label,key])=>`<tr${key==='netInterest'?' class="rate-total"':''}><th scope="row">${label}</th><td>${fmt(q.current[key])}</td><td>${fmt(q.scenario[key])}</td><td>${signed(q.difference[key])}</td></tr>`).join('')}</tbody></table></div>
  <p class="micro muted">Current-book sensitivity holds principal and remaining contracts constant. It excludes new business, repayments, defaults, fees and changes in customer behavior. Compare the full operating forecast before marking Ready.</p>
  <div class="rate-links"><button type="button" class="btn" data-rate-link="pricing">Edit deposit pricing</button><button type="button" class="btn" data-rate-link="portfolio">View lending portfolio</button><button type="button" class="btn" data-rate-link="policies">Bank policies</button></div></div>
  <div><h3>YOUR RATE EXPOSURE</h3><dl class="rate-exposure"><div><dt>Liquid / repricing investments</dt><dd>${fmt(q.exposure.liquid)}</dd></div><div><dt>Fixed-coupon investments</dt><dd>${fmt(q.exposure.fixed)}</dd></div><div><dt>Variable customer deposits</dt><dd>${fmt(q.exposure.floatingDeposits)}</dd></div><div><dt>Protected deposit contracts</dt><dd>${fmt(q.exposure.protectedDeposits)}</dd></div></dl>
  <p class="small">Estimated securities sale value: <b>${fmt(q.current.securitiesValue)}</b> now → <b>${fmt(q.scenario.securitiesValue)}</b> in this scenario (${signed(q.difference.securitiesValue)}).</p>
  <p class="micro muted">Fixed coupons keep paying their agreed rate. Higher market yields reduce their early-sale value; lower yields increase it. These value changes affect earnings only when sold. This game uses a simplified yield curve with term spreads.</p>
  <p class="micro">Emergency funding: ${rate(m.upperBp+825)} annual, charged on ${fmt(q.exposure.openingDebt)} of opening debt. New borrowing starts costing interest next month. This is the game’s emergency facility.</p>
  <h3>NEXT SIX MONTHS</h3><div class="rate-table-scroll"><table class="rate-table"><caption>Existing contracts only · principal, not income; loan schedule assumes payment</caption><thead><tr><th scope="col">Month</th><th scope="col">Investments mature</th><th scope="col">Loan principal due</th><th scope="col">Deposit protection ends</th></tr></thead><tbody>${q.maturities.map(row=>`<tr><th scope="row">${row.cycle}</th><td>${fmt(row.securities)}</td><td>${fmt(row.loans)}</td><td>${fmt(row.deposits)}</td></tr>`).join('')}</tbody></table></div></div></div>
  <div class="rate-treasury"><h3>INVESTMENT POLICY</h3><p class="small">Staged: <b>${esc(E.MonetaryPolicy.choices[q.policy].name)}</b>. At month end, surplus cash is invested after keeping 15% of deposits plus payables in cash. No new cash is invested while emergency debt remains.</p>
  <div class="rate-policy-options">${Object.entries(E.MonetaryPolicy.choices).map(([key,def])=>`<button type="button" class="policy ${q.policy===key?'selected':''}" data-treasury-review="${key}" ${locked?'disabled':''}><b>${esc(def.name)}</b><span>${esc(def.description)}</span></button>`).join('')}</div>
  <p class="micro muted">Balanced uses equal 6- and 24-month purchases; Longer fixed puts three quarters of fixed purchases into 24-month terms. Switching toward liquid lets existing fixed holdings mature. New purchases earn from the following month. Funding needs sell liquid holdings first, then fixed holdings at estimated market value.</p>
  ${monetaryDesk.review&&!locked?`<div class="notice" id="treasuryPolicyReview"><b>Review: ${esc(E.MonetaryPolicy.choices[monetaryDesk.review].name)}</b><p class="small">${esc(E.MonetaryPolicy.choices[monetaryDesk.review].description)} This replaces your draft treasury instruction. Existing fixed holdings retain their coupons and maturity dates.</p><button type="button" class="btn primary" id="stageTreasuryPolicy">Stage policy</button> <button type="button" class="btn" id="cancelTreasuryPolicy">Cancel</button></div>`:''}</div>
  ${m.history.length?`<p class="micro rate-history">Recent Fed decisions: ${m.history.map(h=>'M'+h.cycle+' '+range(h.upperBp)+' ('+(h.changeBp===0?'held':(h.changeBp>0?'+':'')+h.changeBp+' bp')+')').join(' · ')}</p>`:''}</div>`;
 $('#inspectRateImpact').onclick=()=>{const next=currentView();if(!monetaryDeskCurrent(context,next))return;monetaryDesk.open=!monetaryDesk.open;renderMonetaryPolicy(next);};
 $$('[data-rate-scenario]').forEach(b=>b.onclick=()=>{const next=currentView();if(!monetaryDeskCurrent(context,next))return;monetaryDesk.change=Number(b.dataset.rateScenario);renderMonetaryPolicy(next);});
 $$('[data-rate-link]').forEach(b=>b.onclick=()=>{if(monetaryDeskCurrent(context))openBankingContext(b.dataset.rateLink);});
 $$('[data-treasury-review]').forEach(b=>b.onclick=()=>{const next=currentView();if(!monetaryDeskCurrent(context,next)||next.me.submitted||next.gameOver)return;monetaryDesk.review=b.dataset.treasuryReview;renderMonetaryPolicy(next);});
 $('#cancelTreasuryPolicy')?.addEventListener('click',()=>{if(!monetaryDeskCurrent(context))return;monetaryDesk.review=null;renderMonetaryPolicy(currentView());});
 $('#stageTreasuryPolicy')?.addEventListener('click',()=>{const next=currentView();if(!monetaryDeskCurrent(context,next)||next.me.submitted||next.gameOver||!monetaryDesk.review)return;E.MonetaryPolicy.validatePlan(next.me,{treasuryPolicy:monetaryDesk.review});draft.treasuryPolicy=monetaryDesk.review;monetaryDesk.review=null;renderReady(next);});
}
