function renderPartnerCards(v,route,mount){
 const C=E.PartnerCards,R=C.rules(v.me),b=v.me.cardProgram,c=financeContext(route),records=[{id:'program',name:'Cedar Reserve partner cards',detail:b.status==='unlaunched'?'Expansion · requires research and paid setup':b.status+' · '+b.accounts.filter(a=>!a.closed&&!a.chargedOff).length+' active accounts'},{id:'terms',name:'Terms & delivery',detail:'Customer pricing, capacity and exit'}, {id:'customers',name:'Card customers',detail:'Statements, payments and available credit'},{id:'results',name:'Results & issuer risk',detail:'Your earnings separate from Cedar’s loans'}];
 financeLayout(v,route,mount,records,c.objectId,'Cards',(record,detail)=>{
  const editor=financeInspector(detail,v,{title:record.name,subtitle:'Issuer and receivable owner: Cedar Reserve Bank. Your bank distributes the card and supports the relationship.'});
  if(record.id==='customers'){
   editor.innerHTML='<label class="finance-input" for="cardCustomerSearch">Find card customer<input id="cardCustomerSearch" type="search" placeholder="Customer number or payment profile"></label><div id="cardCustomerRows"></div>'+financeNote('Amounts belong to Cedar Reserve’s card portfolio. These are individual card accounts in a separate simulated customer pool; they are not new deposits or bank-owned loans.');
   const guard=financeGuard(v),draw=()=>{const search=$('#cardCustomerSearch').value.trim().toLowerCase(),rows=b.accounts.filter(a=>(a.id+' '+a.profile).toLowerCase().includes(search));$('#cardCustomerRows').innerHTML=rows.length?financeTable(['Customer','Status','Limit','Principal','Interest due','Available credit','Statement due','Due month','Missed payments'],rows.map(a=>[a.id.split(':').at(-1)+' · '+a.profile,a.closed?'Closed':a.chargedOff?'Charged off':a.late?'Overdue':'Current',financeMoney(a.limit),financeMoney(a.principal),financeMoney(a.interest),financeMoney(a.late||a.chargedOff||a.closed||b.status==='windingDown'?0:Math.max(0,a.limit-a.principal-a.interest-a.hold)),financeMoney(a.statement),a.due,a.late])):financeNote('No matching card accounts.');};$('#cardCustomerSearch').oninput=()=>{if(guard(false))draw();};draw();return;
  }
  if(record.id==='results'){
   const r=b.history.at(-1),performance=C.performance(v.me);editor.innerHTML='<h3>Your bank · last completed month</h3>'+(r?financeFacts([['Fees received',financeMoney(r.feesPaid)],['License expense',financeMoney(r.setup)],['Platform and processor expense',financeMoney(r.costs)],['Acquisition campaign',financeMoney(r.marketing)],['Contribution before shared payroll',financeMoney(r.contribution)],['New accounts',r.acquired],['Local risk / technology coverage',(r.coverageBp/100).toFixed(0)+'%']]):financeNote('Complete a month to see earned results.'))+financeNote('No customer principal is included in your revenue. Shared employee payroll and central overhead remain in bank-wide expenses and are not allocated here. Card fees and expenses are posted at month end and appear in the retained-earnings bridge outside the ordinary operating subtotal.')+cardContributionExplanation(performance,r)+'<h3>Cedar Reserve · this bank’s card customers</h3>'+(r?financeFacts([['Settled purchases',financeMoney(r.purchases)],['Purchase reversals',financeMoney(r.reversed)],['Funding declines',financeMoney(r.failedSettlement)],['Principal collected',financeMoney(r.principalPaid)],['Interest accrued',financeMoney(r.interestAccrued)],['Interest collected',financeMoney(r.interestPaid)],['Refunds',financeMoney(r.refunds)],['Returned payments',r.returnedPayments],['New loss provision',financeMoney(r.provision)],['Charge-offs',financeMoney(r.chargeoffs)],['Post-charge-off recoveries',financeMoney(r.recoveries)],['Dispute losses',financeMoney(r.disputeLoss)]]):'')+financeNote('Cedar bears credit and merchant dispute losses. Its acquisition loans, outside advances and card purchases share one finite cash balance. A funding decline creates no loan and pays no merchant.')+'<h3>Recent monthly contribution</h3>'+financeTable(['Month','Fees received','Direct costs','Contribution'],b.history.map(x=>[x.month,financeMoney(x.feesPaid),financeMoney(x.setup+x.costs+x.marketing),financeMoney(x.contribution)]));return;
  }
  if(record.id==='terms'){editor.innerHTML='<h3>Customer terms</h3>'+financeNote('$5,000 limit; 24% annual purchase APR using a monthly 2% convention. No annual fee, late fee, cash advances or rewards in this product. Statements fall due next month: pay the lesser of the balance or the greater of $25 and 5%. Paying the statement in full preserves grace; otherwise interest applies to unpaid opening principal. No interest on interest, new purchases or disputed amounts. Two missed minimums suspend accrual; four trigger charge-off. Returned payments never credit cash. Disputes freeze the contested amount until next month’s merchant refund or Cedar-funded credit.')+'<h3>Delivery and exit</h3>'+financeNote('Central Technology and Risk each need '+(v.me.cardEconomicsVersion===1?'2.5% of one employee’s time, plus 0.125% per live account.':'25% of one employee’s time, plus 1.25% per live account.')+' They share real bank-wide capacity: shortfalls reduce covered purchases and intake. Cedar services the bounded portfolio’s collections. New accounts need at least $2,500 of outside cash and start spending next month. Marketing affects applications, not guaranteed profit. Closing intake retains existing cards; wind-down permanently stops new purchases and continues collections. Platform service is prepaid: insufficient protected cash pauses purchases without creating unpaid vendor debt.');return;}
  editor.insertAdjacentHTML('beforebegin',financeFacts([['Program',b.status],['Setup',financeMoney(R.setup)+' · available following month'],['Recurring platform',financeMoney(R.monthly)+'/active month'],['Processor and support',financeMoney(R.perAccount)+'/live account/month'],['Your purchase compensation','1.5% of settled purchases'],['Your interest compensation','25% of interest actually collected']])+financeNote('Cedar is issuer, funder and collections servicer. The contracted Card Network processor receives your license, platform and processing payments. Licensing requires completed Digital Architecture and Relationship Planning. Ordinary cards need no local digital building.'));
  const initial=financeCopy(draft.cardPolicy||C.defaults(v.me));
  const choices=b.status==='unlaunched'?[['none','Keep locked'],['launch','License partner cards']]:['windingDown','closed'].includes(b.status)?[['none','Continue wind-down']]:[['none','Continue program'],['windDown','Wind down permanently']];
  financeEdit(v,editor,{key:'partner-cards',initial,stageLabel:'Stage card instruction',fields:[{path:'action',label:'Program instruction',choices},{path:'intake',label:'New applications',choices:[[false,'Closed'],[true,'Open']]},{path:'marketing',label:'Monthly acquisition budget ($)',min:0,max:R.maxMarketing,step:R.marketingStep||500}],build:(now,f,candidate)=>{
   candidate.cardPolicy=f;C.validatePlan(now,now.me,candidate);const q=C.quote(now,now.me,candidate),checked=financeValidate(now,candidate);
   return {...checked,facts:[['Maximum card spending this month',financeMoney(q.cost)],['Quoted central work coverage',(q.coverage*100).toFixed(0)+'%'],['Live accounts',q.accounts+' / '+R.maxAccounts],['Monthly acquisition ceiling',R.maxIntake+' accounts at full coverage'],['Cedar-owned principal',financeMoney(q.principal)],...financeBudgetFacts(now,candidate,checked.budget)],notes:['Quoted capacity and protected cash are rechecked at settlement. Research, licensing and marketing do not guarantee customers or profit.','Launch with intake closed and zero marketing; open applications after deployment. Wind-down requires closed intake and zero marketing.','The intake ceiling, shared capacity and remaining eligible customers limit acquisition. Spending continues until you lower the budget; a full book does not pause it automatically.']};
  }});
 });
}

function cardContributionExplanation(p,r){
 if(!p||!r)return '';
 const reason=!p.launched?'The card program has not launched.':r.suspended?'Protected cash was insufficient, so new purchases paused.':r.coverageBp<10000?'Shared Technology or Risk capacity limited card activity.':p.operating>0?'Collected fees covered this month’s delivery and marketing costs.':p.operating===0?'Collected fees matched this month’s delivery and marketing costs.':'Collected fees did not cover this month’s delivery and marketing costs.';
 const facts=[['Operating contribution before shared payroll',financeMoney(p.operating)],['Marketing spend per new account',p.acquisitionCost===null?'No new accounts':financeMoney(p.acquisitionCost)]];
 if(p.totals)facts.push(['Total fees received since launch',financeMoney(p.totals.feesPaid)],['Total direct costs since launch',financeMoney(p.totals.setup+p.totals.costs+p.totals.marketing)],['Cumulative contribution',financeMoney(p.contribution)],['Direct costs still unrecovered',financeMoney(p.unrecovered)]);
 const payback=!p.launched?'There is no launch investment to recover yet.':p.unrecovered===0?'Recorded card fees have recovered the program’s direct costs.':p.paybackMonths!==null?'If this month’s operating contribution repeated unchanged, recovering the remaining direct costs would take '+p.paybackMonths+' more months. This is a scenario, not a forecast.':'There is no payback estimate while current operating contribution is zero or negative.';
 return '<h3>Why the program made or lost money</h3>'+financeFacts(facts)+financeNote(reason+(p.unconvertedMarketing?' Marketing was charged but produced no new accounts. Review intake capacity and your budget.':''))+financeNote(p.totals?payback+' Shared research ($150,000 of prerequisites), payroll and central overhead are excluded; this is not whole-bank investment payback.':'Lifetime payback is unavailable for this older campaign. The table contains only retained monthly records.')+financeNote('Marketing spend per new account divides advertising by all accounts acquired that month, including organic intake. It does not measure incremental advertising returns.');
}
