// Retained base-render alias for existing integration entry points. Service
// deployments now belong to the selected capability's deployment inspector.
const serviceProjectsUI=renderProjects;
function serviceDraftPlayer(v,plan=draft){
 if(v.me.departmentFunctions)return E.departmentCustomerPreview(v.me,v,plan).owner;
 const policy=JSON.parse(JSON.stringify(plan.servicePolicy||v.me.serviceDesk.policy));
 policy.staff=Math.min(policy.staff,plan.allocation.business);
 return {...v.me,allocation:{...plan.allocation},serviceDesk:{...v.me.serviceDesk,policy}};
}
function renderExpandedServices(v){
 let p;try{p=serviceDraftPlayer(v);}catch(error){$('#pipeline').insertAdjacentHTML('beforeend','<section class="notice" style="grid-column:1/-1"><h3>Commercial service forecast unavailable</h3><p>'+esc(error.message)+'</p><button type="button" class="btn" id="serviceCapacityIssue">Review work commitments</button></section>');$('#serviceCapacityIssue')?.addEventListener('click',()=>setPeopleDesk('coverage',{focus:true}));return;}
 const policy=draft.servicePolicy,load=E.serviceLoad(p),token=opportunityToken(v),disabled=!opportunityCurrent(token)?'disabled':'',selected=selectedServiceAgreement(v);
 const toolsOpen=!!$('#servicePricing')?.open;
 const clients=v.serviceAgreements.map(c=>{const profile=E.clientProfile(c),type=E.SERVICE_TYPES[c.kind],own=c.owner===v.me.id;
  return '<button type="button" class="object-row" data-service-inspect="'+esc(c.id)+'" aria-pressed="'+(selected?.id===c.id)+'" '+(c.companyClosed?'disabled':'')+'><span><b>'+esc(profile.name)+'</b><small>'+esc(type.name)+' · '+esc(v.territories[c.market].name)+'</small></span><span class="object-tag">'+(c.companyClosed?'Closed':draft.contractBid===c.id?'Bid staged':own?'Your client':c.due===v.cycle?'Open this month':'Month '+c.due)+'</span></button>';
 }).join('');
 const number=(key,label,max)=>'<label>'+label+' <select data-service-number="'+key+'" '+disabled+'>'+Array.from({length:max+1},(_,i)=>'<option value="'+i+'" '+(policy[key]===i?'selected':'')+'>'+i+'</option>').join('')+'</select></label>';
 const prices=Object.entries(E.SERVICE_TYPES).map(([key,type])=>'<label>'+esc(type.name)+' renewal price<select data-service-price="'+key+'" '+disabled+'>'+Object.entries(E.SERVICE_PRICING).map(([k,d])=>'<option value="'+k+'" '+(policy.pricing[key]===k?'selected':'')+'>'+esc(d.name)+' · '+money(Math.round(type.fee*d.mult))+'</option>').join('')+'</select></label>').join('');
 $('#pipeline').insertAdjacentHTML('beforeend','<section id="commercialClientWorkspace" class="object-workspace" style="grid-column:1/-1"><div class="section-head"><div><h3>Business clients</h3><p class="small muted">Inspect a client. Compare delivery. Review a bid.</p></div><span class="small">'+load.served+'/'+load.count+' signed mandates served · '+money(load.fees-load.cost)+'/month desk net before shared payroll</span></div><div class="object-columns"><nav class="object-directory" aria-label="Commercial clients">'+clients+'</nav><div id="serviceInspectorMount">'+(!selected?'<div class="workbench-empty"><h3>Choose a client</h3><p>See what they need, when you can compete, and the staff and recurring costs required. Looking does not change your plan.</p></div>':'')+'</div></div>'+
  '<details id="servicePricing" class="service-desk-tools" '+(toolsOpen?'open':'')+'><summary>Desk-wide prices, platforms & manual capacity</summary><p class="small">These standing settings affect the entire service desk. The client workspace already proposes a supported capacity mix when you review a bid; use these controls for deliberate desk-wide changes.</p><div class="office-controls-row">'+number('staff','Business bankers reserved',draft.allocation.business)+number('outsourcing','Outsourced service points',4)+'</div><p class="micro">Reserved staff leave other business production. Outsourcing costs $6K per point each month, including unused points; technology coverage can still constrain delivery.</p><div class="office-controls-row">'+prices+'</div><p class="micro">Signed prices stay fixed until renewal. Relationship pricing lowers fees by 20% for bid strength; premium pricing raises fees by 25% but weakens bids.</p>'+
  ['payroll','treasury'].map(k=>'<label><input type="checkbox" data-service-active="'+k+'" '+(policy[k]?'checked':'')+' '+(!v.me.serviceDesk.applications[k]||disabled?'disabled':'')+'> '+(k==='payroll'?'Payroll Automation · $4K/month':'Corporate Treasury · '+(v.me.serviceDesk.applications.treasury==='partner'?'$18K':'$6K')+'/month')+' '+(!v.me.serviceDesk.applications[k]?'(deploy in Strategy first)':'')+'</label>').join('<br>')+
  '<p class="micro">Contracted fees '+money(load.fees)+' − direct service '+money(load.direct)+' − outsourcing '+money(load.outsourced)+' − platforms '+money(load.platform)+' = '+money(load.fees-load.cost)+' before shared payroll. New awards earn from next month. Two missed service months reopen competition.</p></details></section>');
 $$('[data-service-inspect]').forEach(el=>el.addEventListener('click',()=>{if(opportunityCurrent(token,false))inspectServiceAgreement(currentView(),el.dataset.serviceInspect);}));
 const refresh=()=>{const candidate=v.serviceAgreements.find(c=>c.id===draft.contractBid);if(candidate&&!E.serviceBidStatus(serviceDraftPlayer(v),candidate).eligible)draft.contractBid=null;renderReady(v);};
 $$('[data-service-number]').forEach(el=>el.addEventListener('change',()=>{if(!opportunityCurrent(token)||token.stamp!==JSON.stringify(draft))return;policy[el.dataset.serviceNumber]=Number(el.value);refresh();}));
 $$('[data-service-price]').forEach(el=>el.addEventListener('change',()=>{if(!opportunityCurrent(token)||token.stamp!==JSON.stringify(draft))return;policy.pricing[el.dataset.servicePrice]=el.value;refresh();}));
 $$('[data-service-active]').forEach(el=>el.addEventListener('change',()=>{if(!opportunityCurrent(token)||token.stamp!==JSON.stringify(draft))return;policy[el.dataset.serviceActive]=el.checked;refresh();}));
 renderServiceAgreementInspector(v,$('#serviceInspectorMount'));
 renderCommercialAccountPanel(v,selected,$('#serviceInspectorMount'));
 renderServicePlanning(v);
}
let serviceQuoteTarget='';
function renderServicePlanning(v){
 const issue=departmentForecastIssue(v);
 if(issue){$('#pipeline').insertAdjacentHTML('beforeend',departmentForecastNotice(issue));return;}
 // Comparison prepares each candidate itself. Passing an already prepared
 // owner would subtract vendor/leadership costs twice in these forecasts.
 const p=v.me,review=E.servicePlanReview(p,draft,v.economy,v),mandates=v.serviceAgreements.filter(c=>!c.companyClosed&&c.owner!==v.me.id);
 const target=mandates.find(c=>c.id===serviceQuoteTarget)||null,options=E.serviceDeliveryOptions(p,draft,v.economy,target,v),disabled=v.me.submitted?'disabled':'';
 const targetOptions='<option value="">Existing signed book only</option>'+mandates.map(c=>'<option value="'+c.id+'" '+(target&&target.id===c.id?'selected':'')+'>'+esc(E.SERVICE_TYPES[c.kind].name+' · '+v.territories[c.market].name)+'</option>').join('');
 const rows=options.map((o,i)=>'<tr><td>'+o.staff+'</td><td>'+o.outsourcing+' points</td><td>'+money(o.serviceNet)+'</td><td>'+money(o.bankProfit)+'</td><td><button type="button" class="btn" data-delivery-option="'+i+'" '+disabled+'>Use capacity mix</button></td></tr>').join('');
 $('#pipeline').insertAdjacentHTML('beforeend','<section style="grid-column:1/-1"><details id="servicePlanning"><summary>DELIVERY COMPARISON & PLAN RESILIENCE</summary><p class="micro">Draft operating profit <b>'+money(review.profit)+'</b> − funding-sale losses <b>'+money(review.fundingLoss)+'</b> − initiatives, research, hiring and competitive spend <b>'+money(review.nonOperatingSpend)+'</b> = <b class="'+(review.netAfterSpend<0?'bad':'good')+'">'+money(review.netAfterSpend)+' estimated equity change</b>. Advertising/training/offer conversion reserved within the total plan: '+money(review.includedOperatingSpend)+'; their quoted operating expense is already included in profit, not subtracted twice.</p><p class="micro">Headroom after this estimate versus a 10% current-exposure reserve plus $200K: <b class="'+(review.headroom<0?'bad':'good')+'">'+money(review.headroom)+'</b>. This is advisory, not an additional spending rule or a guarantee. Excludes executive events, rival actions, opportunities, regulatory sales and new-project benefits. New-hire payroll begins next turn.</p><label class="micro">Compare delivery for <select id="serviceQuoteTarget">'+targetOptions+'</select></label><p class="micro">'+(target?'Hypothetical next-turn book IF you win '+esc(E.SERVICE_TYPES[target.kind].name)+'. Your quoted fee: '+money(Math.round(E.SERVICE_TYPES[target.kind].fee*E.SERVICE_PRICING[draft.servicePolicy.pricing[target.kind]].mult))+'/turn. Contest cycle '+target.due+'. No guaranteed award.':'Current signed terms; no new contract revenue assumed.')+'</p><div class="table-scroll"><table class="regional-table"><thead><tr><th>Reserved bankers</th><th>Outsourcing</th><th>Desk net / turn</th><th>Bank profit estimate</th><th>Stage change</th></tr></thead><tbody>'+rows+'</tbody></table></div>'+(rows?'':'<p class="micro warn">No fully supported mix: assign more Business bankers or activate the required treasury platform first.</p>')+'<p class="micro muted">Ranked by current-cycle operating profit under the same economy. Desk net is stated before shared payroll. Bank profit adds payroll and the immediate cost of moving bankers off sales, though not the relationships that move may cost you later. Another mix may still be worth more over time, or bid more strongly. Applying a mix sets staffing and outsourcing only — it places no bid and activates no platform. Quoted capacity costs start this turn even though a new award earns next turn.</p></details></section>');
 $('#serviceQuoteTarget').addEventListener('change',el=>{serviceQuoteTarget=el.target.value;renderReady(v)});
 $$('[data-delivery-option]').forEach(el=>el.addEventListener('click',()=>{const o=options[Number(el.dataset.deliveryOption)];draft.servicePolicy.staff=o.staff;draft.servicePolicy.outsourcing=o.outsourcing;const bid=v.serviceAgreements.find(c=>c.id===draft.contractBid);if(bid&&!E.serviceBidStatus(serviceDraftPlayer(v),bid).eligible)draft.contractBid=null;renderReady(v)}));
}
function renderServiceContracts(v){
 if(v.me.serviceDesk){renderExpandedServices(v);return}
 if(!v.serviceAgreements)return;
 const c=E.contractIncome(v.me),ad=v.me.contractAds;
 const cards=v.serviceAgreements.map(c=>{
  const due=c.due===v.cycle,owner=c.owner===v.me.id?v.me.name:c.owner===v.rival.id?v.rival.name:'Outside providers',incumbent=c.owner===v.me.id;
  return '<button type="button" class="opportunity '+(draft.contractBid===c.id?'selected':'')+'" data-contract="'+esc(c.id)+'" '+(!due||incumbent||v.me.submitted||draft.allocation.business<1?'disabled':'')+'><b>'+esc(v.territories[c.market].name)+'</b><div class="micro">Provider: '+esc(owner)+'</div><div class="opp-value">'+(due?'CONTEST THIS TURN':'Renewal: cycle '+c.due)+'</div><div class="micro">'+(incumbent?'Automatic renewal defense uses your current staffing.':due?'Select to pursue instead of a new opportunity this turn.':'Returns to competition even in a mature market.')+'</div></button>';
 }).join('');
 $('#pipeline').insertAdjacentHTML('beforeend','<section style="grid-column:1/-1"><h3>RENEWABLE SERVICE AGREEMENTS</h3><p class="micro muted">One six-turn fee agreement per market. Each serviced agreement earns '+money(E.CONTRACT_FEE)+'/turn and costs '+money(E.CONTRACT_SERVICE)+'/turn. One Business banker supports one agreement; excess agreements earn no fee but retain their service cost. These are service mandates, not new deposits or loans.</p><p class="micro">Current book: '+c.count+' held · '+c.served+' staffed · '+money(c.fees-c.cost)+' net fees/turn before shared payroll. New awards start earning next turn. Incumbents receive a modest defense bonus only when fully staffed; outside providers also bid.</p><div class="pipeline">'+cards+'</div><p class="micro muted">Bid strength: Business staffing ×2 + Operations staffing ×0.5 + local branches (up to 3) ×1.5 + Commercial tier + reputation /40. Fully staffed incumbent +2; understaffed incumbent −3. Targeted advertising adds +3 locally. Each contender adds 0–4 uncertainty; outside providers start at 10. No guaranteed win.</p><p class="micro">Targeted advertising: '+(ad&&ad.expires>=v.cycle?esc(v.territories[ad.market].name)+' through cycle '+ad.expires:'inactive')+'. Start its '+money(v.projects.contractAdvertising.cost)+' initiative in Operations using your selected focus market. It lasts four future turns and replaces your previous targeted campaign.</p></section>');
 $$('[data-contract]').forEach(b=>b.addEventListener('click',()=>{draft.contractBid=draft.contractBid===b.dataset.contract?null:b.dataset.contract;if(draft.contractBid)draft.opportunity=null;renderPipeline(v);renderReady(v)}));
}
function renderPipeline(v){renderOpportunityPipeline(v);}
const servicePipeline=renderPipeline;
renderPipeline=function(v){const expanded=$('#servicePricing')?.open,planning=$('#servicePlanning')?.open;servicePipeline(v);renderServiceContracts(v);if(expanded&&$('#servicePricing'))$('#servicePricing').open=true;if(planning&&$('#servicePlanning'))$('#servicePlanning').open=true};
