async function acceptGhReveal(m){const session=gh;try{if(m.cycle<game.cycle||game.players[1].submitted){syncPeers();return}if(!ghIncomingCommit)throw Error('The rival revealed a plan without first locking a commitment.');if(m.cycle!==game.cycle||m.cycle!==ghIncomingCommit.cycle)throw Error('The rival revealed a plan for the wrong cycle.');if(typeof m.nonce!=='string'||!/^[0-9a-f]{48}$/.test(m.nonce))throw Error('The rival plan seal is malformed.');const activeGame=game,commit=ghIncomingCommit;const hash=await ghPlanHash(m.plan,m.nonce);if(gh!==session||!session.active||game!==activeGame)return;if(ghIncomingCommit!==commit)throw Error('Commitment changed during verification.');if(hash!==ghIncomingCommit.hash||hash!==m.hash)throw Error('The rival plan changed after it was marked ready.');ghIncomingCommit=null;E.submit(game,1,m.plan);syncPeers()}catch(e){if(gh!==session||!session.active)return;ghIncomingCommit=null;try{send({type:'error',code:'plan_rejected',message:e.message})}catch{}toast(`The rival plan was rejected: ${e.message}`);syncPeers()}}
function handleMessage(m){
 if(!m||typeof m!=='object')return;
 if(p2pRole==='host'){
  if(m.type==='hello'){
   if(((game&&game.relationshipOffersVersion)||(!game&&p2pConfig.relationshipOffersVersion))&&m.relationshipOffersSupported!==1){send({type:'error',message:'Relationship offers preview requires the updated game on both computers.'});setConnection('RELATIONSHIP OFFERS LINK REFUSED','bad');return}
   if(((game&&game.regionalGrowthVersion)||(!game&&p2pConfig.regionalGrowthVersion))&&m.regionalGrowthSupported!==1){send({type:'error',message:'Regional growth preview requires the updated game on both computers.'});setConnection('REGIONAL GROWTH LINK REFUSED','bad');return}
   if(((game&&game.advertisingVersion)||(!game&&p2pConfig.advertisingVersion))&&m.advertisingSupported!==1){send({type:'error',message:'Advertising preview requires the updated game on both computers.'});setConnection('ADVERTISING LINK REFUSED','bad');return}
   if(((game&&game.productProgramsVersion)||(!game&&p2pConfig.productProgramsVersion))&&m.productProgramsSupported!==1){send({type:'error',message:'Product programmes requires the updated game on both computers.'});setConnection('PRODUCT PROGRAMMES LINK REFUSED','bad');return}
   if(((game&&game.segmentDepositsVersion)||(!game&&p2pConfig.segmentDepositsVersion))&&m.segmentDepositsSupported!==1){send({type:'error',message:'Segment deposits requires the updated game on both computers.'});setConnection('SEGMENT DEPOSITS LINK REFUSED','bad');return}
   if(((game&&game.creditPerformanceVersion)||(!game&&p2pConfig.creditPerformanceVersion))&&m.creditPerformanceSupported!==1){send({type:'error',message:'Credit performance requires the updated game on both computers.'});setConnection('CREDIT LINK REFUSED','bad');return}
   if(((game&&game.customerOwnershipVersion)||(!game&&p2pConfig.customerOwnershipVersion))&&m.customerOwnershipSupported!==1){send({type:'error',message:'Household ownership requires the updated game on both computers.'});setConnection('HOUSEHOLD LINK REFUSED','bad');return}
   if(((game&&game.workforceVersion)||(!game&&p2pConfig.workforceVersion))&&m.workforceSupported!==1){send({type:'error',message:'Specialist workforce requires the updated game on both computers.'});setConnection('WORKFORCE LINK REFUSED','bad');return}
   if(((game&&game.customerDemandVersion)||(!game&&p2pConfig.customerDemandVersion))&&(![1,2].includes(m.customerDemandSupported)||m.customerDemandSupported<(game?game.customerDemandVersion:p2pConfig.customerDemandVersion))){send({type:'error',message:'Customer needs requires the updated game on both computers.'});setConnection('CUSTOMER NEEDS LINK REFUSED','bad');return}
   if(((game&&game.managementVersion===2)||(!game&&p2pConfig.managementVersion===2))&&m.relationshipSupported!==1){send({type:'error',message:'Relationship operations requires the updated game on both computers.'});setConnection('RELATIONSHIP LINK REFUSED','bad');return}
   if(((game&&game.managementVersion>=1)||(!game&&p2pConfig.managementVersion>=1))&&m.managementSupported!==1){send({type:'error',message:'Living institution requires the updated game on both computers.'});setConnection('LIVING INSTITUTION LINK REFUSED','bad');return}
   if(((game&&game.campaignRulesVersion===1)||(!game&&p2pConfig.campaignRulesVersion===1))&&m.pilotSupported!==11){send({type:'error',message:'Regional Rivalry requires the updated game on both computers.'});setConnection('PILOT LINK REFUSED // Update the rival game file.','bad');return}
   if(!game){try{openLobby(m)}catch(e){setConnection('LOBBY REFUSED // '+e.message,'bad');send({type:'error',code:'lobby_required',message:e.message})}return}
   linkReady=true;stopHandshake();syncPeers();return
  }
  if(m.type==='lobby_update'&&!game){applyLobbyUpdate(1,m);return}
  if(!game){try{send({type:'hello_request'})}catch{}return}
  if(m.type==='plan_commit'&&gh.active){try{if(m.cycle<game.cycle||game.players[1].submitted){syncPeers();return}if(!/^[0-9a-f]{64}$/.test(String(m.hash||''))||m.cycle!==game.cycle)throw Error('The rival sent an invalid plan commitment.');if(ghIncomingCommit&&ghIncomingCommit.hash!==m.hash)throw Error('The rival tried to replace a locked plan commitment.');ghIncomingCommit={hash:m.hash,cycle:m.cycle};syncPeers()}catch(e){try{send({type:'error',message:e.message})}catch{}toast(`The rival commitment was rejected: ${e.message}`)}return}
  if(m.type==='plan_reveal'&&gh.active)return acceptGhReveal(m);
  if(m.type==='plan'){if(gh.active){try{send({type:'error',message:'This Repository Link client is outdated and did not seal its plan. Both players must use the current game file.'})}catch{}return}try{E.submit(game,1,m.plan);syncPeers()}catch(e){try{send({type:'error',message:e.message})}catch{}toast(`The rival plan was rejected: ${e.message}`)}return}
  if(m.type==='recall'){try{if(gh.active&&ghIncomingCommit&&!game.players[0].submitted)ghIncomingCommit=null;if(game.players[1].submitted&&!game.players[0].submitted)game.players[1].submitted=null;syncPeers()}catch(e){try{send({type:'error',message:e.message})}catch{}}return}
  if(m.type==='rematch'){try{E.rematch(game,1);syncPeers()}catch(e){try{send({type:'error',message:e.message})}catch{}}return}
  return
 }
 if(m.type==='hello_request'){try{send({type:'hello',lobbySupported:1,pilotSupported:11,managementSupported:1,relationshipSupported:1,customerDemandSupported:2,relationshipOffersSupported:1,regionalGrowthSupported:1,advertisingSupported:1,productProgramsSupported:1,segmentDepositsSupported:1,creditPerformanceSupported:1,customerOwnershipSupported:1,workforceSupported:1,color:p2pConfig.color,name:p2pConfig.guestName,doctrine:p2pConfig.doctrine})}catch(e){setConnection(`DIRECT LINK SEND FAILED // ${e.message}`,'bad')}return}
 if(m.type==='lobby'){receiveLobby(m);return}
 if(m.type==='state'){if(!view&&p2pConfig&&p2pConfig.lobbyRequired&&!lobby){$('#connectHint').textContent='The host skipped the lobby. Both players need this updated game file.';setConnection('LOBBY REQUIRED // Update the host game before starting.','bad');toast('The host skipped the lobby. Both players need this updated build.');return}linkReady=true;stopHandshake();clearTimeout(planAckTimer);planAckTimer=null;view=m.state;if(ghPendingPlan&&(view.gameOver||view.cycle!==ghPendingPlan.cycle))ghPendingPlan=null;if(ghPendingPlan&&ghPendingPlan.recallRequested&&!view.me.submitted&&!view.rival.submitted)ghPendingPlan=null;if(gh.active&&ghPendingPlan&&view.rival.submitted)ghRevealPlan();if(ghPendingPlan)view.me.submitted=true;if(!lan.active&&!gh.active)mode='p2p';setConnection(gh.active?`REPOSITORY ROOM ${gh.room} // LINKED`:lan.active?`ROOM ${lan.room} // CONNECTED`:'DIRECT LINK CONNECTED','good');if($('#gameScreen').classList.contains('hidden')&&$('#gameOver').classList.contains('hidden'))enterGame(true);else render();return}
 if(m.type==='error'){if(!game&&!view){$('#connectHint').textContent=m.message;setConnection(m.message,'bad');if($('#lobbyError'))$('#lobbyError').textContent=m.message;toast(m.message);return}if(gh.active&&m.code==='plan_rejected')ghPendingPlan=null;clearTimeout(planAckTimer);planAckTimer=null;if(view&&view.me&&view.me.submitted){view.me.submitted=false;render()}if($('#submitMsg'))$('#submitMsg').textContent=`THE HOST REJECTED THAT PLAN // ${m.message}`;toast(m.message);return}
}

function syncPeers(){if(game&&game.mode==='lan')saveLocal();const mine=E.publicState(game,0),theirs=E.publicState(game,1);if(gh.active&&ghIncomingCommit){mine.rival.submitted=true;theirs.me.submitted=true}let sendErr=null;try{send({type:'state',state:theirs})}catch(e){sendErr=e}view=mine;try{render()}catch(e){console.error('Branch Wars failed to redraw the host view',e);toast(`Display error: ${e.message}`)}if(sendErr){setConnection(`LINK SEND FAILED // ${sendErr.message}`,'bad');toast(`The rival did not receive the update: ${sendErr.message}`)}}
