function opportunityPower(p,o){const a=p.allocation,branch=p.branches[o.market]||0,focus=p.focus===o.market?4:0,dept=p.departmentFunctions?(departmentOpportunityQuote(p,o).available||0)/4:a[o.dept]||0,policy=o.type==='deposit'||o.type==='wealth'?p.policies.deposit==='aggressive'?2:0:o.type==='loan'&&p.policies.lending==='growth'?2:0,strategy=(['business','loan','payroll','public'].includes(o.type)?strategyLevel(p,'commercial')*.8:strategyLevel(p,'digital')*.45);return dept*2.4+branch*3+focus+policy+p.stats.reputation/22+p.stats.morale/35+p.upgrades.training+p.upgrades.analytics*1.5+strategy}
function bankColor(value,seat=0){return typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value.toLowerCase():seat===1?'#e1505c':'#2878e0'}
function resolveDepartmentOpportunities(g,plans){
 const lines=[],chosen=plans.map((plan,i)=>{
  const o=g.opportunities.find(row=>row.id===plan.opportunity);if(!o)return null;
  const quote=reserveDepartmentOpportunity(g,g.players[i],o);
  if(!quote.eligible){lines.push(g.players[i].name+' paused its pursuit of '+o.name+': insufficient unused department delivery capacity.');return null;}
  return o;
 });
 const conclude=(index,won)=>{
  const p=g.players[index],o=chosen[index];p.departmentFunctionDelivery.opportunity.result=won?'won':'lost';
  if(won){awardOpportunity(p,o);lines.push(p.name+' won '+o.name+' in '+g.territories[o.market].name+'.');}
  else lines.push(p.name+' lost '+o.name+' after a lengthy follow-up sequence.');
 };
 if(chosen[0]&&chosen[1]&&chosen[0].id===chosen[1].id){
  const a=opportunityPower(g.players[0],chosen[0])+simulationRandom()*5,b=opportunityPower(g.players[1],chosen[1])+simulationRandom()*5;
  conclude(0,a>=b);conclude(1,b>a);
 }else for(let i=0;i<2;i++)if(chosen[i])conclude(i,simulationRandom()<clamp(.32+opportunityPower(g.players[i],chosen[i])/38,.42,.9));
 return lines;
}
function opportunityTerms(o){
 if(!o||!['deposit','business','loan','wealth','payroll','public'].includes(o.type)||!Number.isSafeInteger(o.value)||o.value<0)throw new Error('Invalid opportunity terms');
 return {deposits:o.type==='loan'?0:o.value,loans:o.type==='loan'?o.value:0,feeIncome:o.type==='business'?85000:o.type==='loan'?Math.round(o.value*.018):0};
}
function acquisitionTerms(g,p,target){
 const buyer=g.players.indexOf(p),seller=1-buyer,rival=g.players[seller],market=g.territories[target];
 if(buyer<0||!market||!rival)throw new Error('Invalid acquisition target');
 const deal=strategyLevel(p,'acquisition'),share=market.shares[seller]/100;
 return {buyer,seller,deal,depositTake:Math.round(Math.min(rival.stats.deposits*(.045+deal*.012)*Math.max(.45,share),4200000)),loanTake:Math.round(Math.min(rival.stats.loans*(.025+deal*.007)*Math.max(.4,share),1900000)),customerTake:Math.round(Math.min(rival.stats.customers*(.035+deal*.008),420))};
}
function awardOpportunity(p,o){if(!authorizeDepartmentOpportunityAward(p,o))return;const terms=opportunityTerms(o);switch(o.type){case'deposit':delta(p,'deposits',terms.deposits);delta(p,'customers',18);break;case'business':delta(p,'deposits',terms.deposits);delta(p,'business',5);delta(p,'merchant',6);delta(p,'cash',terms.feeIncome);break;case'loan':delta(p,'loans',terms.loans);delta(p,'cash',terms.feeIncome);delta(p,'compliance',4);break;case'wealth':delta(p,'deposits',terms.deposits);delta(p,'wealth',4);delta(p,'influence',3);break;case'payroll':delta(p,'deposits',terms.deposits);delta(p,'customers',75);delta(p,'business',4);delta(p,'merchant',5);break;case'public':delta(p,'deposits',terms.deposits);delta(p,'influence',5);delta(p,'attention',2)}delta(p,'opportunityWins',1);delta(p,'reputation',3);delta(p,'momentum',4)}
function resolveOpportunities(g,plans){if([6,7].includes(g.financialGroupVersion))return resolveDepartmentOpportunities(g,plans);const L=[],byId=id=>g.opportunities.find(o=>o.id===id),o0=byId(plans[0].opportunity),o1=byId(plans[1].opportunity);if(o0&&o1&&o0.id===o1.id){const a=opportunityPower(g.players[0],o0)+simulationRandom()*5,b=opportunityPower(g.players[1],o1)+simulationRandom()*5,w=a>=b?0:1;awardOpportunity(g.players[w],o0);L.push(`${g.players[w].name} defeated its rival for ${o0.name} in ${g.territories[o0.market].name}.`)}else{[[0,o0],[1,o1]].forEach(([i,o])=>{if(!o)return;const chance=clamp(.32+opportunityPower(g.players[i],o)/38,.42,.9);if(simulationRandom()<chance){awardOpportunity(g.players[i],o);L.push(`${g.players[i].name} won ${o.name} in ${g.territories[o.market].name}.`)}else L.push(`${g.players[i].name} lost ${o.name} after a lengthy follow-up sequence.`)})}return L}
function marketFacilities(p,k){return p.facilityMarkets&&Array.isArray(p.facilityMarkets[k])?p.facilityMarkets[k]:[]}
function depositPull(p,k,t){const a=p.allocation,competitive=(p.focus===k?(p.turnEffects.depositAttack||0):0)+(p.turnEffects.depositDefense||0),models=marketFacilities(p,k),retail=models.filter(x=>x==='retail').length,digital=models.filter(x=>x==='digital').length;return (p.branches[k]||0)*(1.5+strategyLevel(p,'network')*.12)+retail*1.5+digital*.55+(p.focus===k?1.8:0)+a.service*.9+p.stats.reputation/22+p.stats.digital/55+strategyLevel(p,'digital')*.1+(p.doctrine==='community'?.375:0)+(p.doctrine==='commercial'?.25:0)+(p.doctrine==='efficiency'?.775:0)+(p.doctrine==='people'?.6:0)+(p.policies.deposit==='aggressive'?.75:p.policies.deposit==='margin'?-.4:0)+(p.marketingTurns>0?1.2:0)+(t.specialties.includes('service')?1:0)+competitive-(tierRank(p)>=3?2.5:0)}
function competitionScale(g){const markets=activeTerritories(g).length;return markets>=12?.6:markets>=8?.86:1}
function depositContest(g){
 let net=0;const hot=[],act=campaignAct(g),territories=activeTerritories(g),scopeScale=competitionScale(g);
 for(const[k,t]of territories){if(!unlocked(g,t))continue;const edge=depositPull(g.players[0],k,t)-depositPull(g.players[1],k,t);if(Math.abs(edge)<.5)continue;const moved=clamp(edge*.1,-1,1)*t.value*4200*act.pressure*scopeScale;net+=moved;if(Math.abs(moved)>18000)hot.push([t.name,moved])}
 if(Math.abs(net)<10000)return{lines:[],outflow:[0,0]};const win=net>0?0:1,lose=1-win,winner=g.players[win],loser=g.players[lose],before=Math.max(1,loser.stats.deposits),liquidity=loser.stats.cash/before,run=act.key==='consolidation'&&winner.policies.deposit==='aggressive'&&(liquidity<.03||tierRank(loser)>=2),cap=run?.12:act.depositCap,amount=Math.round(Math.min(Math.abs(net)*(run?2.25:1),before*cap));if(amount<10000)return{lines:[],outflow:[0,0]};
 const hotLost=Math.round(amount*Math.min(1,(loser.stats.rateSensitiveDeposits||0)/before)),hotWon=Math.round(amount*({margin:.08,balanced:.25,aggressive:.7}[winner.policies.deposit]));delta(loser,'rateSensitiveDeposits',-hotLost);delta(winner,'rateSensitiveDeposits',hotWon);delta(loser,'deposits',-amount);delta(winner,'deposits',amount);if(!winner.accounting)delta(winner,'cash',amount);winner.stats.rateSensitiveDeposits=Math.min(winner.stats.rateSensitiveDeposits,winner.stats.deposits);loser.stats.rateSensitiveDeposits=Math.min(loser.stats.rateSensitiveDeposits,loser.stats.deposits);if(loser.fundingRulesVersion!==2)delta(loser,'capital',-Math.round(amount*.05));delta(winner,'customers',Math.round(amount/9000));delta(loser,'customers',-Math.round(amount/9000));const where=hot.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))[0],outflow=[0,0];outflow[lose]=loser.accounting?0:amount;return{lines:[`${winner.name} ${run?'triggered a DEPOSIT RUN and pulled':'pulled'} $${amount.toLocaleString()} of deposits away from ${loser.name}${where?`, led by ${where[0]}`:''}; $${hotWon.toLocaleString()} entered as rate-sensitive funding.`],outflow}
}
function settleFundingLegacy(g,p,outflow){const L=[];let need=(p.fundingGap||0)+outflow;p.fundingGap=0;if(need<=0)return L;const fromCash=Math.min(p.stats.cash,need);delta(p,'cash',-fromCash);need-=fromCash;if(need<1000)return L;const sellable=Math.min(p.stats.loans,Math.round(need/.94));if(sellable>0){const haircut=Math.round(sellable*.06);delta(p,'loans',-sellable);delta(p,'capital',-haircut);need-=sellable-haircut;L.push(`${p.name} liquidated $${sellable.toLocaleString()} of loans to fund deposit outflow, realizing a $${haircut.toLocaleString()} loss.`)}if(need>1000){delta(p,'capital',-Math.round(need));L.push(`${p.name} drew $${Math.round(need).toLocaleString()} directly from capital to stay funded.`)}return L}
function settleFunding(g,p,outflow){
 if(p.fundingRulesVersion!==2)return settleFundingLegacy(g,p,outflow);
 if(!Number.isFinite(outflow)||outflow<0)throw Error('Invalid funding outflow.');
 const L=[];let need=Math.round((p.fundingGap||0)+outflow);p.fundingGap=0;if(need<=0){const reserve=Math.round(p.stats.deposits*({liquid:.10,balanced:.05,reinvest:.02}[p.policies.capital]||.05)),repaid=Math.min(p.stats.emergencyDebt||0,Math.max(0,p.stats.cash-reserve));if(repaid){delta(p,'cash',-repaid);delta(p,'emergencyDebt',-repaid);L.push(`${p.name} repaid ${repaid.toLocaleString()} of emergency funding from cash above its policy reserve.`)}return L}
 const fromCash=Math.min(p.stats.cash,need);delta(p,'cash',-fromCash);need-=fromCash;
 // Sell the minimum whole-dollar loan amount that covers the gap after the haircut.
 if(need>0&&p.stats.loans>0){const sold=Math.min(p.stats.loans,Math.ceil(need/.94)),haircut=Math.round(sold*.06),proceeds=sold-haircut,used=Math.min(need,proceeds);delta(p,'loans',-sold);delta(p,'capital',-haircut);need-=used;if(proceeds>used)delta(p,'cash',proceeds-used);L.push(`${p.name} sold $${sold.toLocaleString()} of loans to fund outflows and booked a $${haircut.toLocaleString()} loss.`)}
 if(need>0){delta(p,'emergencyDebt',need);L.push(`${p.name} borrowed $${need.toLocaleString()} in emergency funding at 1% per cycle; the debt remains outstanding.`);need=0}
 return L
}
function specialtyPower(p,t){let n=0;for(const x of t.specialties){if(ROLES[x])n+=p.allocation[x]*1.2;if(x==='digital')n+=p.stats.digital/36+p.upgrades.technology*2;if(x==='people')n+=p.stats.morale/20;if(x==='corporate')n+=p.stats.influence/17}return n}
function pushShare(t,amount){if(t.exited&&t.exited[0]){t.shares=[0,100];return}if(t.exited&&t.exited[1]){t.shares=[100,0];return}const next=Math.round(clamp(t.shares[0]+amount,5,95)*10)/10;t.shares[0]=next;t.shares[1]=Math.round((100-next)*10)/10}
function simulateMarkets(g){const L=[],territories=activeTerritories(g),pressure=campaignAct(g).pressure*competitionScale(g);for(const[k,t]of territories){if(!unlocked(g,t))continue;const strengths=g.players.map((p,i)=>{if(t.exited&&t.exited[i])return-100;const models=marketFacilities(p,k),facilityFit=models.reduce((sum,type)=>sum+(type==='retail'?(t.specialties.includes('service')?2.2:1):type==='commercial'?(t.specialties.some(x=>['business','merchant','wealth'].includes(x))?2.8:.7):(t.specialties.includes('digital')?2.5:1.1)),0);let x=(p.branches[k]||0)*(7.8+strategyLevel(p,'network')*.35)+facilityFit+(p.focus===k?6:0)+p.stats.reputation/16+specialtyPower(p,t)+(p.marketingTurns>0?4:0)+(p.policies.deposit==='aggressive'&&t.specialties.includes('service')?2:0)+(p.doctrine==='community'?2.1:p.doctrine==='commercial'?.5:p.doctrine==='efficiency'?1.1:p.doctrine==='people'?1:0)+(p.upgrades.analytics||0)*.6+strategyLevel(p,'acquisition')*.18-(tierRank(p)>=3?3:0);x*=(p.turnEffects.market||1);if(p.isBot&&g.difficulty==='chairman')x+=1.5;return x}),shift=clamp(((strengths[0]-strengths[1])*.27+(simulationRandom()*2-1))*pressure,-7,7);pushShare(t,shift);if(Math.abs(shift)>=2.5)L.push(`${g.players[shift>0?0:1].name} gained ${Math.abs(shift).toFixed(1)} points of share in ${t.name}.`)}return L}
function resolveMarketExits(g){const L=[];for(const[k,t]of activeTerritories(g)){if(!unlocked(g,t))continue;t.exitStreak=Array.isArray(t.exitStreak)?t.exitStreak:[0,0];t.exited=Array.isArray(t.exited)?t.exited:[false,false];for(let i=0;i<2;i++){if(t.exited[i])continue;t.exitStreak[i]=t.shares[i]<12?t.exitStreak[i]+1:0;if(t.exitStreak[i]>=3){const winner=1-i,loserBank=g.players[i],winnerBank=g.players[winner],closed=loserBank.facilityMarkets[k]||[];for(const type of closed)loserBank.facilities[type]=Math.max(0,(loserBank.facilities[type]||0)-1);loserBank.facilityMarkets[k]=[];t.exited[i]=true;t.shares[i]=0;t.shares[winner]=100;loserBank.branches[k]=0;if(!(winnerBank.branches[k]||0)){winnerBank.branches[k]=1;winnerBank.facilityMarkets[k]=['retail'];winnerBank.facilities.retail=(winnerBank.facilities.retail||0)+1}delta(loserBank,'reputation',-7);delta(winnerBank,'reputation',4);L.push(`${loserBank.name} closed every facility in ${t.name} after three cycles below 12% share. ${winnerBank.name} now owns the market.`)}}}return L}
function franchiseDividends(g){const L=[],cash=[0,0],deposits=[0,0];for(const[,t]of activeTerritories(g)){if(!unlocked(g,t)||!t.exited)continue;for(let loser=0;loser<2;loser++)if(t.exited[loser]){const winner=1-loser;cash[winner]+=t.value*6000;deposits[winner]+=t.value*2500}}for(let i=0;i<2;i++)if(cash[i]){delta(g.players[i],'cash',cash[i]);delta(g.players[i],'deposits',deposits[i]);L.push(`${g.players[i].name} collected $${cash[i].toLocaleString()} from uncontested market franchises.`)}return L}
function updateCampaignAct(g){
 const current=Number(g.act)||0,territories=activeTerritories(g),maxStrategy=Math.max(...g.players.map(strategyTotal)),anyControl=Math.max(controlledCount(g,0),controlledCount(g,1)),exitCount=territories.filter(([,t])=>t.exited&&t.exited.some(Boolean)).length,anyCapstone=g.players.some(p=>!!strategyCapstone(p)),anyStress=g.players.some(p=>tierRank(p)>=2),allUnlocked=territories.every(([,t])=>unlocked(g,t));
 let next=current;
 if(current===0&&(maxStrategy>=5||anyControl>=Math.max(2,Math.ceil(territories.length*.42))||g.players.some(p=>p.stats.deposits>=36000000)))next=1;
 if(next===1&&allUnlocked&&(anyCapstone||exitCount>=2||(anyStress&&maxStrategy>=5)))next=2;
 if(next!==current){g.act=next;const act=campaignAct(g);addLog(g,`${act.roman} // ${act.name} — ${act.text}`,'ACT');return`${act.roman} BEGINS — ${act.name}. ${act.text}`}
 return''
}
function absorbFranchise(g,winner,loser){const w=winner.stats?winner:g.players[winner],l=loser.stats?loser:g.players[loser],wi=g.players.indexOf(w),li=1-wi;delta(w,'deposits',Math.round(l.stats.deposits*.72));delta(w,'loans',Math.round(l.stats.loans*.55));delta(w,'customers',Math.round(l.stats.customers*.65));delta(w,'business',Math.round(l.stats.business*.5));for(const[k,t]of activeTerritories(g)){w.branches[k]=Math.max(w.branches[k]||0,l.branches[k]||0);w.facilityMarkets[k]=[...(w.facilityMarkets[k]||[]),...(l.facilityMarkets[k]||[])].slice(0,w.branches[k]);l.branches[k]=0;l.facilityMarkets[k]=[];t.exited=t.exited||[false,false];t.exitStreak=t.exitStreak||[0,0];t.exited[wi]=false;t.exited[li]=true;t.exitStreak=[0,0];t.shares[wi]=100;t.shares[li]=0}w.facilities={retail:0,commercial:0,digital:0};for(const models of Object.values(w.facilityMarkets))for(const type of models)w.facilities[type]++}
const absorbFranchiseCore=absorbFranchise;absorbFranchise=function(g,winner,loser){absorbFranchiseCore(g,winner,loser);for(const p of g.players){p.facilities={retail:0,commercial:0,digital:0};for(const models of Object.values(p.facilityMarkets||{}))for(const type of models)p.facilities[type]++}};
function evaluateStrategicEnd(g){
 const failed=g.players.filter(p=>(p.distress||0)>=RECEIVERSHIP_CYCLES);
 if(failed.length){g.gameOver=true;g.endReason='receivership';if(failed.length===2)g.winnerId=g.fundingRulesVersion===2?null:capitalRatio(g.players[0])>capitalRatio(g.players[1])?g.players[0].id:capitalRatio(g.players[1])>capitalRatio(g.players[0])?g.players[1].id:null;else{const survivor=g.players.find(p=>p!==failed[0]);g.winnerId=survivor.id;g.failedId=failed[0].id;absorbFranchise(g,survivor,failed[0])}return`RECEIVERSHIP // ${failed.map(p=>p.name).join(' and ')} placed into receivership. ${g.winnerId?g.players.find(p=>p.id===g.winnerId).name+' assumes the deposits and branch network.':'No acquirer was solvent enough to assume the franchise.'}`}
 const territories=activeTerritories(g),open=territories.filter(([,t])=>unlocked(g,t)),allUnlocked=open.length===territories.length;
 for(let loser=0;loser<2;loser++)if(allUnlocked&&open.length&&open.every(([,t])=>t.exited&&t.exited[loser])){const winner=1-loser;g.gameOver=true;g.endReason='domination';g.winnerId=g.players[winner].id;g.failedId=g.players[loser].id;absorbFranchise(g,g.players[winner],g.players[loser]);return`TOTAL MARKET DOMINATION // ${g.players[loser].name} has no operating market left. ${g.players[winner].name} absorbs the franchise.`}
 const actThree=campaignAct(g).key==='consolidation',settled=actThree&&open.length>0&&open.every(([,t])=>t.exited&&t.exited.some(Boolean));
 g.consolidationStalemate=settled?(Number(g.consolidationStalemate)||0)+1:0;
 g.buyoutPressure=Array.isArray(g.buyoutPressure)?g.buyoutPressure:[0,0];
 for(let bidder=0;bidder<2;bidder++){
  const target=1-bidder,a=baseScore(g,bidder),b=Math.max(1,baseScore(g,target)),bidderRank=tierRank(g.players[bidder]),targetRank=tierRank(g.players[target]),targetPlan=g.lastPlans&&g.lastPlans[g.players[target].id],takeoverGuard=targetPlan&&targetPlan.competitiveAction==='takeoverDefense';
  const distressedBuyout=actThree&&a>=b*1.85&&targetRank>=2&&bidderRank<=1&&g.players[bidder].stats.influence>=30;
  const settledBuyout=settled&&a>=b*1.35&&bidderRank<=1&&g.players[bidder].stats.influence>=25;
  const mandatedAuction=settled&&g.consolidationStalemate>=8&&a>b&&bidderRank<=2;
  const eligible=!takeoverGuard&&(distressedBuyout||settledBuyout||mandatedAuction);
  g.buyoutPressure[bidder]=eligible?(g.buyoutPressure[bidder]||0)+1:0;
  if(g.buyoutPressure[bidder]>=2){g.gameOver=true;g.endReason='buyout';g.winnerId=g.players[bidder].id;g.failedId=g.players[target].id;absorbFranchise(g,g.players[bidder],g.players[target]);return mandatedAuction?`MANDATED CONSOLIDATION // With every market divided and no independent path to expansion, ${g.players[bidder].name} won the regulator-supervised franchise auction and acquired ${g.players[target].name}.`:`HOSTILE BUYOUT // ${g.players[bidder].name} sustained a two-cycle takeover position and acquired ${g.players[target].name}.`}
 }
 return''
}
