function activeTerritories(g){return Object.entries(g.territories)}
function campaignAct(g){return CAMPAIGN_ACTS[Math.max(0,Math.min(CAMPAIGN_ACTS.length-1,Number(g.act)||0))]}
function unlocked(g,t){return t.unlock<=g.cycle}
function branchLevels(p){return Object.values(p.branches).reduce((a,b)=>a+b,0)}
function controlledCount(g,index){return activeTerritories(g).filter(([,t])=>unlocked(g,t)&&t.shares[index]>=55).length}
function marketValue(g,index){return Math.round(activeTerritories(g).filter(([,t])=>unlocked(g,t)).reduce((sum,[,t])=>sum+t.value*(t.shares[index]/100)+(t.shares[index]>=55?7:0),0)*10)/10}
function baseScore(g,index){const p=g.players[index],s=p.stats,u=p.upgrades,strategyValue=strategyTotal(p)*18+(strategyCapstone(p)?30:0);return Math.round(((s.deposits/1e6)*5.2+(s.loans/1e6)*5.6+s.customers*.02+s.business*.82+s.merchant*.72+s.wealth*1.15+s.reputation*1.65+s.digital*.55+s.morale*.62+s.staff*2.4+s.cash/135000+s.capital/120000+s.earnings/65000+s.influence*.68+s.momentum*.3+(u.technology+u.training+u.analytics+u.wealth+u.operations)*13+strategyValue-(p.boardConcessions||0)*35+branchLevels(p)*14+(p.achievements||[]).length*25-s.compliance-s.attention*.82-s.chargeoffs/100000+marketValue(g,index)*2.5)*10)/10}
function mandateStatus(g,index){const p=g.players[index],s=p.stats,m={...MANDATES[p.mandate]},total=activeTerritories(g).length;if(p.mandate==='network')m.desc=`Operate at least ${networkGoal(g)} total branch levels across the map.`;let achieved=false,progress='';switch(p.mandate){case'map':achieved=controlledCount(g,index)>total/2;progress=`${controlledCount(g,index)} / ${Math.floor(total/2)+1} markets`;break;case'deposits':achieved=s.deposits>=40000000;progress=`$${(s.deposits/1e6).toFixed(1)}M / $40M`;break;case'commercial':achieved=s.business>=105&&s.merchant>=80;progress=`${s.business}/105 business // ${s.merchant}/80 merchant`;break;case'earnings':achieved=s.earnings>=2200000;progress=`$${(s.earnings/1e6).toFixed(2)}M / $2.2M`;break;case'clean':achieved=s.compliance<=18&&s.attention<30;progress=`risk ${s.compliance}/18 // heat ${s.attention}/30`;break;case'people':achieved=s.morale>=82&&s.staff>=10&&p.upgrades.training>=2;progress=`morale ${s.morale}/82 // staff ${s.staff}/10 // training ${p.upgrades.training}/2`;break;case'digital':achieved=s.digital>=85&&p.upgrades.technology>=2;progress=`digital ${s.digital}/85 // technology ${p.upgrades.technology}/2`;break;case'network':achieved=branchLevels(p)>=networkGoal(g);progress=`${branchLevels(p)} / ${networkGoal(g)} branch levels`}return{key:p.mandate,...m,achieved,progress}}
function finalScore(g,index){const m=mandateStatus(g,index);return Math.round((baseScore(g,index)+(m.achieved?m.bonus:0))*10)/10}
function captureTrend(g,cycle=0){g.trend=g.trend||[];const point={cycle,scores:[baseScore(g,0),baseScore(g,1)],deposits:g.players.map(p=>Math.round(p.stats.deposits)),loans:g.players.map(p=>Math.round(p.stats.loans)),cash:g.players.map(p=>Math.round(p.stats.cash)),profits:g.players.map(p=>Math.round(p.stats.lastProfit)),markets:[controlledCount(g,0),controlledCount(g,1)]};const prior=g.trend[g.trend.length-1];if(prior&&prior.cycle===cycle)g.trend[g.trend.length-1]=point;else g.trend.push(point);return point}
function normalizeAllocation(p){for(const k of Object.keys(ROLES))p.allocation[k]=Math.max(0,Math.round(Number(p.allocation[k])||0));let sum=Object.values(p.allocation).reduce((a,b)=>a+b,0);while(sum>p.stats.staff){const k=Object.keys(p.allocation).sort((a,b)=>p.allocation[b]-p.allocation[a])[0];if(!p.allocation[k])break;p.allocation[k]--;sum--}while(sum<p.stats.staff){p.allocation.service++;sum++}}
function chooseEvent(g){let pool=EVENTS.filter(e=>!g.event||e.key!==g.event.key),fav={rate:['ratewar','downturn'],regulatory:['audit','fraud','cyber'],growth:['closure','viral','board']}[g.scenario]||[];pool=pool.concat(pool.filter(e=>fav.includes(e.key)),pool.filter(e=>fav.includes(e.key)));return pick(pool)}
function makeOpportunities(g){const open=activeTerritories(g).filter(([,t])=>unlocked(g,t)).map(([k])=>k),types=shuffled(Object.keys(OPPORTUNITY_TYPES)).slice(0,3);return types.map((type,i)=>{const t=OPPORTUNITY_TYPES[type],market=pick(open),value=Math.round(t.base*(.78+simulationRandom()*.55)/10000)*10000;return{id:`${g.cycle}-${i}-${rint(100,999)}`,type,market,value,name:t.name,dept:t.dept,desc:t.desc}})}
function chooseEconomy(g,initial=false){const pools={balanced:['steady','steady','expansion','tight','recovery','downturn'],rate:['tight','tight','tight','steady','downturn'],regulatory:['steady','tight','downturn','recovery'],growth:['expansion','expansion','expansion','steady','recovery']},prior=g.economy&&g.economy.key,next=initial?pick(pools[g.scenario]||pools.balanced):pick((pools[g.scenario]||pools.balanced).filter(x=>x!==prior));g.economy={key:next,...MACRO_REGIMES[next]};return g.economy}
