'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),{performance}=require('node:perf_hooks');
const c={console};vm.runInNewContext(require('../tools/build_game').assemble().html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1].replace('root.BWEngine={','root.BWEngine={groupEntities,syncAccounts,settleAgency,settleCorporateCirculation,validateAgencySave,CompanyFinance,'),c);const E=c.BWEngine,copy=x=>JSON.parse(JSON.stringify(x)),start=performance.now();
const options=E.previewFeatureSelection({}, {field:'financialGroupVersion',value:10}).options;
function fresh(seed,scenario='balanced'){return E.createGame({...options,seed,scenario,mode:'hotseat',created:1});}
function funded(g){for(const p of g.players){const amount=240000;p.accounting=E.AccountingPrototype.post(p.accounting,'fixture.priorCapitalReturn',{cash:-amount,equity:-amount});E.syncAccounts(p);p.financialGroup.parent=E.GroupAccounting.post(p.financialGroup.parent,'fixture.priorCapitalReturn',p.id,{cash:amount,investments:-amount});p.financialGroup.investmentBasis.bank-=amount;}E.validatePilot(g);return g;}
function policy(g,i,maintain=true){const p=g.players[i],s=E.defaultAgencyPlan(p);s.maintainCredentials=maintain;s.outreach=1;s.target=i?'benefits':g.cycle%3===0?'liability':'property';s.dividend=0;s.capital=0;if(g.cycle===1){s.launch=true;s.capital=120000;s.outreach=2;s.roles=i?{propertyProducer:0,benefitsProducer:1,servicing:0}:{propertyProducer:1,benefitsProducer:0,servicing:0};}return s;}
function domain(g,maintain=true,demand=1){g.companyEconomy=E.CompanyFinance.step(g.companyEconomy,{demand});const plans=g.players.map((p,i)=>({groupPolicy:E.defaultGroupPlan(p),agencyPolicy:policy(g,i,maintain)}));E.settleAgency(g,plans);E.settleCorporateCirculation(g);g.cycle++;E.validateAgencySave(g);E.CompanyFinance.validate(g.companyEconomy);for(const p of g.players){E.GroupAccounting.consolidate(p.financialGroup.parent,E.groupEntities(p),p.accounting);const owned=g.agencyEconomy.relationships.filter(r=>r.owner===p.id),load=owned.reduce((n,r)=>n+E.AGENCY_PRODUCTS[r.product].load,0);assert(load<=(p.agency.professionals.report?.units||0));if(p.agency.status==='active')assert.equal(owned.length,p.agency.report.clients);}}
const credential=funded(fresh('agency-credential-maintenance')),education=[0,0],registration=[0,0];
for(let month=1;month<=15;month++){
 domain(credential);for(const [i,p]of credential.players.entries()){assert.equal(p.agency.status,'active','Maintenance fixture must stay solvent to test actual renewals');const r=p.agency.professionals.report;education[i]+=r.educationCost;registration[i]+=r.registrationCost;assert.equal(r.educationCost,month===13?900:0);assert.equal(r.registrationCost,month===1?2500:month===15?1500:0);assert.equal(r.renewed.length,month===13?1:0);if(month===13)assert.equal(r.units,i?9:6);}
}
assert.deepEqual(education,[900,900]);assert.deepEqual(registration,[4000,4000]);
const unmaintained=funded(fresh('agency-expired'));for(let n=1;n<=15;n++){domain(unmaintained,false);if(n===13)for(const p of unmaintained.players){assert.equal(p.agency.professionals.report.phase,'no qualified producer');assert.equal(p.agency.report.clients,0);assert.equal(p.agency.professionals.report.educationCost,0);}if(n===15)for(const p of unmaintained.players)assert.equal(p.agency.professionals.report.phase,'registration expired');}
const stress=[];
for(const [name,demand,months]of [['normal',1,120],['regulatory demand stress',.5,480]]){
 const g=funded(fresh('agency-professionals:'+name)),failAt=[null,null];for(let n=1;n<=months;n++){domain(g,true,demand);g.players.forEach((p,i)=>{if(p.agency.status==='failed'&&!failAt[i])failAt[i]=n;});}
 if(name==='normal')assert(g.players.every(p=>p.agency.status==='active'),'Both bounded, uncontested specialist strategies must be capable of covering their normal operating cost.');
 const result={name,months,failAt,cash:g.players.map(p=>p.agency.book.accounts.cash),retained:g.players.map(p=>p.agency.book.retainedEarnings),companyClosures:g.companyEconomy.companies.filter(c=>c.resolution).length,commission:g.agencyEconomy.commissionPaid,paidExpenses:g.agencyEconomy.operatingPaid};stress.push(result);console.log('DOMAIN '+JSON.stringify(result));
}
const outcomes=[];let fullEngineMonths=0;
for(const scenario of (process.argv.includes('--domain-only')?[]:['balanced','rate','regulatory','growth'])){
 const g=fresh('agency-normal-opening',scenario),launchMonths=[null,null];for(let month=1;month<=24&&!g.gameOver;month++){
  const plans=g.players.map((p,i)=>E.chooseBot(g,i));E.submit(g,0,plans[0]);E.submit(g,1,plans[1]);fullEngineMonths++;E.validatePilot(g);E.validateLedger(g);g.players.forEach((p,i)=>{if(p.agency.openedCycle&&!launchMonths[i])launchMonths[i]=p.agency.openedCycle;});if(month===12){const resumed=E.migrateCampaign(copy(g));assert.equal(resumed.version,'9.9');}
 }
 outcomes.push({scenario,months:g.cycle-1,gameOver:g.gameOver,launchMonths,agencyFailures:g.players.map(p=>p.agency.failures),bankCash:g.players.map(p=>Math.round(p.stats.cash)),capitalRatio:g.players.map(p=>E.capitalRatio(p)),agencyCash:g.players.map(p=>p.agency.book.accounts.cash)});console.log('PASS normal opening '+scenario);
}
console.log(JSON.stringify({suite:'agency-professionals-balance',fullEngineMonths,domainMonths:630,seconds:(performance.now()-start)/1000,stress,outcomes,scope:process.argv.includes('--domain-only')?'Domain-only: actual renewal/expiry and 120/480 company/agency accounting stress, using conserved prior-bank-capital-return fixtures. Not whole-game or ordinary-opening balance acceptance.':'Versioned domain renewal and 120/480 accounting stress use conserved prior-bank-capital-return fixtures. Four 24-month whole-engine cases use ordinary unfunded openings and AI, not player enjoyment or final 120/480 whole-game release acceptance.'},null,2));
