'use strict';
const assert=require('node:assert/strict'),{harness}=require('./github_resilience.test.js');
const h=harness();
h.run("const options=E.previewFeatureSelection({}, {field:'financialGroupVersion',value:3}).options;"+
  "game=E.createGame({...options,mode:'hotseat',seed:'agency-ui',created:1});seat=0;workspaceTab='group';"+
  // A UI-only funded fixture; the engine campaign tests prove actual earning and funding paths.
  "game.players[0].financialGroup.parent=E.GroupAccounting.post(game.players[0].financialGroup.parent,'test.parentCapital','external',{cash:240000,equity:240000});"+
  "newDraft(currentView());renderReady=()=>{};toast=t=>lastToast=t;let lastToast='';renderFinancialGroup(currentView());");
const markup=h.elements.get('#financialGroupPanel').innerHTML;
function uniqueRenderedIds(markup){
 const ids=[...markup.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set(ids).size,ids.length,'Actual Financial Group controls must have unique IDs');
 const html=require('node:fs').readFileSync(require('node:path').join(__dirname,'../BRANCH_WARS.html'),'utf8');
 const staticMarkup=html.replace(/(<script\b[^>]*>)[\s\S]*?<\/script>/gi,'$1</script>');
 const staticIds=new Set([...staticMarkup.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]));
 assert(ids.every(id=>!staticIds.has(id)),'Emitted controls cannot duplicate a static document ID');
}
uniqueRenderedIds(markup);
assert.match(markup,/INSURANCE AGENCY/);assert.match(markup,/separate from banking mandates/);
assert.match(markup,/18 independent relationships/);assert.match(markup,/does not insure claims/);
assert.match(markup,/not guaranteed revenue/i);assert.match(markup,/service units/);
assert.match(markup,/\$120,000/);assert.match(markup,/\$30,000/);
assert.match(markup,/employee benefits/i);assert.match(markup,/Corporate cover roster/);
assert.match(markup,/role="tablist" aria-label="Financial Group desks"/);
assert.match(markup,/If launched: recurring operating expense/);
assert.match(markup,/These totals include the operating insurance agency/);
assert.equal(h.run('financialGroupDesk'),'capital');
assert.equal(h.elements.get('#groupDesk-capital').hidden,false);
assert.equal(h.elements.get('#groupDesk-agency').hidden,true);
assert.equal(h.elements.get('#groupDesk-companies').hidden,true);
assert.equal(h.elements.get('#groupTab-capital').ariaSelected,'true');
const navigationState=h.run('JSON.stringify({game,draft})');
h.elements.get('#groupTab-agency').listeners.click();
assert.equal(h.elements.get('#groupDesk-agency').hidden,false);
assert.equal(h.elements.get('#groupDesk-capital').hidden,true);
assert.equal(h.elements.get('#groupTab-agency').tabIndex,0);
assert.equal(h.run('JSON.stringify({game,draft})'),navigationState,'Desk switching changes only presentation.');
let prevented=false;
h.elements.get('#groupTab-agency').listeners.keydown({key:'ArrowRight',preventDefault(){prevented=true;}});
assert(prevented);assert.equal(h.run('financialGroupDesk'),'companies');
h.elements.get('#groupTab-companies').listeners.keydown({key:'Home',preventDefault(){}});
assert.equal(h.run('financialGroupDesk'),'capital');
h.elements.get('#groupTab-capital').listeners.keydown({key:'ArrowLeft',preventDefault(){}});
assert.equal(h.run('financialGroupDesk'),'companies');
h.elements.get('#groupTab-agency').listeners.click();
for(const c of h.run('E.ANCHOR_CLIENTS'))assert(markup.includes(c.name));
assert.doesNotMatch(markup.split('id="agency-staff"')[1].split('</select>')[0],/<option value="0"/);
const before=h.run('JSON.stringify(game)'),draftBefore=h.run('JSON.stringify(draft)');
h.run("for(const [key,value] of Object.entries({capital:120000,staff:1,target:'property',outreach:2,supportCap:10000,dividend:0}))$('#agency-'+key).value=String(value);$('#agency-launch').checked=true;");
h.elements.get('#groupTab-companies').listeners.click();h.elements.get('#groupTab-agency').listeners.click();
assert.equal(h.elements.get('#agency-capital').value,'120000','Switching desks preserves unstaged working-form values.');
h.elements.get('#previewAgency').listeners.click();
assert.equal(h.run('JSON.stringify(game)'),before,'Preview must not mutate authoritative state.');
assert.equal(h.run('JSON.stringify(draft)'),draftBefore,'Preview must not stage a plan.');
assert.match(h.elements.get('#agencyInstructionStatus').textContent,/Preview only/);
assert.match(h.elements.get('#agencyInstructionQuote').innerHTML,/\$120,000/);
h.elements.get('#agency-outreach').listeners.change();
assert.match(h.elements.get('#agencyInstructionQuote').innerHTML,/form changed/i);
assert.equal(h.run('JSON.stringify(draft)'),draftBefore,'Editing the form must not stage its values.');
h.elements.get('#previewAgency').listeners.click();
const firstStage=h.elements.get('#stageAgency').listeners.click;
firstStage();
assert.equal(h.run('JSON.stringify(game)'),before,'Staging must not launch, pay expenses or fund anything.');
assert.equal(h.run('draft.agencyPolicy.launch'),true);
assert.equal(h.run('draft.agencyPolicy.capital'),120000);
assert.equal(h.run('draft.agencyPolicy.supportCap'),10000);
assert.equal(h.run('financialGroupDesk'),'agency','Staging must keep the current desk selected.');
const staged=h.run('JSON.stringify(draft)');
firstStage();
assert.equal(h.run('JSON.stringify(draft)'),staged,'Old controls cannot overwrite a staged plan.');
assert.match(h.run('lastToast'),/plan changed/);
assert.equal(h.run('stageAgencyPolicy(currentView(),{...draft.agencyPolicy,capital:999999})'),false);
assert.equal(h.run('JSON.stringify(draft)'),staged,'Invalid funding must reject atomically.');
assert.equal(h.run('stageAgencyPolicy(currentView(),{...draft.agencyPolicy,staff:0})'),false);
assert.equal(h.run('JSON.stringify(draft)'),staged,'Invalid staff must not partially stage.');
// Competing parent commitments are validated together, without spending a planned dividend.
h.run('draft.groupPolicy.bankSupport=130000');
const conflict=h.run('JSON.stringify(draft)');
assert.equal(h.run('stageAgencyPolicy(currentView(),{...draft.agencyPolicy})'),false);
assert.equal(h.run('JSON.stringify(draft)'),conflict);
h.run('draft.groupPolicy.bankSupport=0;renderFinancialGroup(currentView());');
const savedStage=h.elements.get('#stageAgency').listeners.click;
h.run("draft.decision='a';E.submit(game,0,draft);renderFinancialGroup(currentView());");
assert.match(h.elements.get('#financialGroupPanel').innerHTML,/id="stageAgency"[^>]*disabled/);
const sealed=h.run('JSON.stringify(draft)');savedStage();
assert.equal(h.run('JSON.stringify(draft)'),sealed,'Sealed plans cannot be changed by old controls.');
h.run('E.submit(game,1,E.chooseBot(game,1));newDraft(currentView());renderFinancialGroup(currentView());');
assert.equal(h.run('game.players[0].agency.status'),'active');
assert.equal(h.run('financialGroupDesk'),'agency','Same-owner settlement must keep the current desk.');
assert.equal(h.run('draft.agencyPolicy.launch'),false);
assert.equal(h.run('draft.agencyPolicy.capital'),0);
assert.match(h.elements.get('#financialGroupPanel').innerHTML,/LAST SETTLED MONTH · 1/);
uniqueRenderedIds(h.elements.get('#financialGroupPanel').innerHTML);
assert.match(h.elements.get('#financialGroupPanel').innerHTML,/Expenses invoiced/);
const settled=h.run('JSON.stringify(game)');
h.run('agencyPanel(currentView());agencyResultsMarkup(currentView());');
assert.equal(h.run('JSON.stringify(game)'),settled,'Settled statements and roster rendering are pure.');
const currentStage=h.elements.get('#stageAgency').listeners.click;
h.run('seat=1;newDraft(currentView());');
const guestDraft=h.run('JSON.stringify(draft)');currentStage();
assert.equal(h.run('JSON.stringify(draft)'),guestDraft,'An owner switch invalidates all old controls.');
h.run('seat=0;newDraft(currentView());renderFinancialGroup(currentView());');
const preReloadStage=h.elements.get('#stageAgency').listeners.click;
h.run('game=JSON.parse(JSON.stringify(game));');
const restoredDraft=h.run('JSON.stringify(draft)');preReloadStage();
assert.equal(h.run('JSON.stringify(draft)'),restoredDraft,'Replacement campaigns invalidate controls even at the same owner and month.');
// Rival display strings are escaped. No hidden rival agency book enters markup.
h.run("const safeView=currentView();safeView.rival.name='<script>bad</script>';safeView.me.agencySnapshot.relationships[0].owner=safeView.rival.id;const escaped=agencyPanel(safeView);");
assert.match(h.run('escaped'),/&lt;script&gt;bad&lt;\/script&gt;/);
assert(!h.run('escaped').includes('<script>bad</script>'));
assert.equal(h.run('currentView().rival.agency'),undefined);
// Failure is a funded relaunch decision, never a silent restoration of the lost investment.
h.run("const failedView=currentView();failedView.me.agency.status='failed';failedView.me.agency.failedCycle=1;failedView.me.agency.failures=1;const failedHtml=agencyPanel(failedView);");
assert.match(h.run('failedHtml'),/Relaunch agency/);assert.match(h.run('failedHtml'),/prior loss remains/);
uniqueRenderedIds(h.run('failedHtml'));
const legacy=harness();
legacy.run("game=E.createGame({mode:'hotseat',seed:1,created:1});seat=0;newDraft(currentView());");
assert.equal(legacy.run('agencyPanel(currentView())'),'');
assert.equal(legacy.run('draft.agencyPolicy'),undefined);
legacy.run("workspaceTab='group';game=E.createGame({...E.previewFeatureSelection({}, {field:'financialGroupVersion',value:2}).options,mode:'hotseat',seed:1,created:1});seat=0;newDraft(currentView());renderFinancialGroup(currentView());");
assert.doesNotMatch(legacy.elements.get('#financialGroupPanel').innerHTML,/Financial Group desks|groupDesk-capital/,'Legacy Group 2 retains its existing layout.');
assert.match(legacy.elements.get('#financialGroupPanel').innerHTML,/CORPORATE CLIENTS/);
console.log('Agency UI PASS: funded/atomic staging, pure previews, service units, independent client roster, report, sealed/stale/reloaded controls, privacy, funded relaunch and legacy hiding. Browser acceptance is separate.');
