'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'BRANCH_WARS.html'), 'utf8');
// Frozen pre-refactor implementation, never regenerated by this test.
const reference = fs.readFileSync(path.join(root, 'reports/reference-builds/BRANCH_WARS_goodwill_0ae290e.html'), 'utf8');
const copy = x => JSON.parse(JSON.stringify(x));
const same = (a, b, label) => assert.equal(JSON.stringify(a), JSON.stringify(b), label);
function runtime(html) {
  let randomCalls = 0;
  const math = Object.create(Math);
  math.random = () => {randomCalls++; return 0.314159;};
  class Clock extends Date {static now() {return 123456789;}}
  const context = {console, Math: math, Date: Clock};
  vm.runInNewContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1], context);
  const E = context.BWEngine, client = {E};
  vm.runInNewContext(html.slice(html.indexOf('function repairGame'), html.indexOf('function saveLocal')) +
    ';globalThis.importSave=migrateGame;globalThis.repair=repairGame;globalThis.rivalry=repairOpenEnded;', client);
  return {E, client, randomCalls: () => randomCalls};
}
const current = runtime(source), old = runtime(reference), E = current.E;
function outcome(fn) {
  try {return {value: fn()};}
  catch (error) {return {error: error.name + ': ' + error.message};}
}
let creations = 0, migrations = 0;
function creation(options) {
  const before = JSON.stringify(options), aCount = current.randomCalls(), bCount = old.randomCalls();
  const actual = outcome(() => E.createGame(options)), expected = outcome(() => old.E.createGame(options));
  same(actual, expected, 'Creation drift: ' + before);
  assert.equal(current.randomCalls() - aCount, old.randomCalls() - bCount, 'Ambient random consumption changed');
  assert.equal(JSON.stringify(options), before, 'Creation mutated caller options');
  creations++;
  return actual.value;
}
const core = {seed: 'lifecycle', created: 1, mode: 'hotseat', name1: 'Oak Bank', name2: 'Cedar Bank'};
for (const scope of ['town', 'regional', 'state', 'national'])
  for (const scenario of ['balanced', 'rate', 'regulatory', 'growth'])
    for (const mode of ['ai', 'hotseat', 'lan', 'p2p'])
      for (const fundingRulesVersion of [1, 2])
        creation({...core, scope, scenario, mode, fundingRulesVersion, color1: '#ab9321', color2: '#317ca9'});

// All combinations of optional pilot stages: disabled dependencies must not
// silently activate later stages or change defaults.
const flags = ['regionalEconomyVersion', 'marketEconomyVersion', 'creditLifecycleVersion',
  'fundingCovenantVersion', 'depositProductsVersion', 'termFundingVersion',
  'retailLifecycleVersion', 'productDeploymentVersion', 'contractRulesVersion', 'serviceExpansionVersion'];
for (let mask = 0; mask < 2 ** flags.length; mask++)
  creation({...core, campaignRulesVersion: 1, ...Object.fromEntries(flags.map((key, i) => [key, (mask >> i) & 1]))});
for (const managementVersion of [undefined, 0, 1, 2])
  for (const customerDemandVersion of [undefined, 0, 1, 2])
    for (const serviceExpansionVersion of [0, 1])
      creation({...core, campaignRulesVersion: 1, managementVersion, customerDemandVersion, serviceExpansionVersion});
// Validate even unused feature flags; preserve precedence of multiply-invalid inputs.
for (const key of ['campaignRulesVersion', 'fundingRulesVersion', ...flags, 'managementVersion', 'customerDemandVersion'])
  for (const value of [null, -1, 2, 3, '1', true, NaN])
    for (const pilot of [false, true])
      creation({...core, ...(pilot ? {campaignRulesVersion: 1} : {}), [key]: value});
creation({...core, campaignRulesVersion: 9, fundingRulesVersion: 9, managementVersion: 9, customerDemandVersion: 9});
creation({...core, campaignRulesVersion: 1, fundingRulesVersion: 9});
creation({}); creation({mode: 'hotseat'}); creation(undefined); creation(null);
creation({...core, seed: undefined, created: undefined});

function migration(input) {
  const before = JSON.stringify(input);
  const actual = outcome(() => E.migrateCampaign(input));
  const expected = outcome(() => old.client.importSave(input));
  // v8.6 intentionally widens the supported save range. Keep every other
  // result/error comparison exact; this changes no preserved save fixture.
  if (expected.error === 'Error: Only v6.0 through v8.4 saves are supported.')
    expected.error = 'Error: Only v6.0 through v8.6 saves are supported.';
  same(actual, expected, 'Migration differs from frozen importer');
  same(outcome(() => current.client.importSave(input)), actual, 'Browser import adapter disagrees with engine');
  assert.equal(JSON.stringify(input), before, 'Import/rejection mutated caller-owned save');
  if (actual.value) {
    same(E.migrateCampaign(actual.value), actual.value, 'Import is not idempotent');
    same(actual.value.players.map(p => p.submitted), input.players.map(p => p.submitted), 'Import changed a sealed plan');
  }
  migrations++;
  return actual.value;
}
for (const file of ['legacy-half-ready.json', 'pilot-half-ready.json', 'goodwill-half-ready.json'])
  migration(JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', file), 'utf8')).game);
for (const options of [{fundingRulesVersion: 1}, {fundingRulesVersion: 2},
  {campaignRulesVersion: 1, regionalEconomyVersion: 0},
  {campaignRulesVersion: 1, serviceExpansionVersion: 0},
  {campaignRulesVersion: 1}, {campaignRulesVersion: 1, managementVersion: 1},
  {campaignRulesVersion: 1, managementVersion: 2, customerDemandVersion: 1},
  {campaignRulesVersion: 1, managementVersion: 2, customerDemandVersion: 2}]) {
  const g = E.createGame({...core, ...options});
  migration(g);
  E.submit(g, 1, E.chooseBot(g, 1));
  migration(g); // The other seat may be ready at import time too.
  for (const clientMethod of ['repair', 'rivalry'])
    same(current.client[clientMethod](copy(g)), old.client[clientMethod](copy(g)), 'Legacy repair adapter drift');
}
const legacy = E.createGame({...core, fundingRulesVersion: 1});
delete legacy.simulationVersion; delete legacy.rng;
delete legacy.fundingRulesVersion; legacy.players.forEach(p => delete p.fundingRulesVersion);
for (const version of ['6.0', '7.0', '7.1', '8.0', '8.1', '8.2', '8.3', '8.4'])
  migration({...copy(legacy), version});
const damaged = copy(legacy);
damaged.mode = 'missing'; damaged.event = null; damaged.trend = null;
delete damaged.players[0].capability; damaged.players[0].strategy = {network: 2};
damaged.players[0].projects = [{key: 'missing', progress: 0, total: 1}];
damaged.players[0].products = {retail: 'missing'};
damaged.players[0].stats.capital = 0;
const repaired = migration(damaged);
assert.equal(repaired.players[0].stats.capital, 0, 'Import must not recapitalize a failing bank');
const modern = E.createGame({...core, campaignRulesVersion: 1, managementVersion: 2, customerDemandVersion: 2});
for (const corrupt of [
  g => {g.version = '5.0';}, g => {g.rng = null;}, g => {g.ledgerVersion = 99;},
  g => {g.fundingRulesVersion = 1;}, g => {g.players[1].fundingRulesVersion = 1;},
  g => {g.players[0].stats.emergencyDebt = -1;}, g => {g.players[0].stats.capital += 1;},
  g => {g.regions = null;}, g => {g.managementVersion = 99;}, g => {g.customerDemandVersion = 99;}
]) {
  const bad = copy(modern); corrupt(bad);
  assert(outcome(() => E.migrateCampaign(bad)).error, 'Corrupt save was accepted');
  migration(bad);
}
for (const input of [null, {}, {version: '8.1', players: [{}], territories: {}}]) migration(input);
assert.equal((source.match(/\bcreateGame\s*=(?!=)/g) || []).length, 0, 'Creation overrides returned');
assert(!/\brepairGame\s*=(?!=)/.test(source), 'Browser repair override returned');
console.log('Campaign lifecycle passed: ' + creations + ' independent creation comparisons, ' + migrations +
  ' migration comparisons, optional-stage matrix, random consumption, sealed plans, corruption rejection and browser adapters.');
