'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=require('../tools/build_game').assemble().html,ctx={console};
vm.createContext(ctx);vm.runInContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1],ctx);
const E=ctx.BWEngine,copy=x=>JSON.parse(JSON.stringify(x));
const options=E.previewFeatureSelection({}, {field:'financialGroupVersion',value:4}).options;
const game=E.createGame({...options,mode:'hotseat',seed:'department-workforce-ui',created:1});
const p=game.players[0];p.workforce.departments.business.count=2;p.workforce.departments.business.skill=20;
p.allocation={service:3,business:3,lending:1,operations:1};E.validatePilot(game);
const plans=game.players.map((p,i)=>E.chooseBot(game,i));
for(const plan of plans){plan.investments={};plan.newProjects=[];plan.newProject=null;plan.hires=0;
 for(const role of Object.keys(plan.specialistHires))plan.specialistHires[role]=0;
 plan.facilityPolicy={convert:null,cancel:null};plan.competitiveAction='none';plan.groupPolicy.bankDividend=0;plan.groupPolicy.bankSupport=0;}
Object.assign(plans[0],{allocation:copy(p.allocation),contractBid:null,opportunity:null});
plans[0].leaderOrders.business='mentor';plans[0].workforcePolicy.training.business=20000;
const nodes=new Map();ctx.$=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',value:'',classList:{toggle(){}},addEventListener(){}});return nodes.get(selector);};
ctx.E=E;ctx.game=game;ctx.view=E.publicState(game,0);ctx.draft=copy(plans[0]);ctx.workspaceTab='workforce';
ctx.esc=x=>String(x);ctx.money=x=>'$'+Math.round(x).toLocaleString('en-US');
for(const name of ['renderDepartments','renderHouseholds','renderCollections','renderFinancialGroup','setWorkspaceTab','renderReady','renderProjects','toast'])ctx[name]=()=>{};
vm.runInContext(fs.readFileSync(path.join(root,'src/ui/workforce.js'),'utf8'),ctx);
const draw=()=>{vm.runInContext("selectedWorkforceRole='business';renderWorkforce(view)",ctx);return nodes.get('#workforcePanel').innerHTML;};
let checks=0;
const original=JSON.stringify({view:ctx.view,draft:ctx.draft,game});
const budget=E.planBudget(ctx.view.me,ctx.draft),quote=E.departmentBudgetQuote(ctx.view.me,ctx.draft);
assert.equal(budget.departmentLeadership,37000);assert.equal(budget.training,12000);assert.equal(budget.training,quote.training.total);
assert.equal(budget.total,49000);assert.equal(quote.productiveAllocation.business,2);
assert.equal(quote.rows.find(r=>r.role==='business').productiveSpecialists,1);
assert.equal(quote.rows.find(r=>r.role==='business').bonus,.16);checks++;
const output=draw();assert.match(output,/Qualified \/ assigned \/ productive staff/);
assert.match(output,/3 assigned · 1 reserved for paid teaching · 2 productive bankers/);
assert.match(output,/1 of 2 qualified bankers producing/);assert.match(output,/>2 \+ 0\.16</);
assert.equal(JSON.stringify({view:ctx.view,draft:ctx.draft,game}),original);checks++;
const review=E.servicePlanReview(ctx.view.me,ctx.draft,game.economy);
assert.equal(review.includedOperatingSpend,49000);assert.equal(review.nonOperatingSpend,0);
assert.equal(review.netAfterSpend,review.netOperating);checks++;
E.submit(game,0,plans[0]);E.submit(game,1,plans[1]);E.validatePilot(game);E.validateLedger(game);
ctx.view=E.publicState(game,0);ctx.draft=E.chooseBot(game,0);
ctx.draft.investments={};ctx.draft.newProjects=[];ctx.draft.newProject=null;ctx.draft.hires=0;
for(const role of Object.keys(ctx.draft.specialistHires))ctx.draft.specialistHires[role]=0;
ctx.draft.facilityPolicy={convert:null,cancel:null};ctx.draft.competitiveAction='none';
ctx.draft.workforcePolicy.training.business=20000;ctx.draft.allocation=copy(p.allocation);
ctx.draft.groupPolicy.bankSupport=0;ctx.draft.groupPolicy.bankDividend=0;
assert.equal(E.planBudget(ctx.view.me,ctx.draft).departmentLeadership,7000);
assert.equal(E.planBudget(ctx.view.me,ctx.draft).training,12000);
assert.equal(E.planBudget(ctx.view.me,ctx.draft).training,E.departmentBudgetQuote(ctx.view.me,ctx.draft).training.total);checks++;
ctx.draft.departmentPolicy.reserve=10000000;
const paused=E.departmentBudgetQuote(ctx.view.me,ctx.draft);
assert.equal(paused.training.total,0);assert.equal(E.planBudget(ctx.view.me,ctx.draft).training,0);
assert.equal(paused.productiveAllocation.business,3);
assert.match(draw(),/3 assigned · 0 reserved for teaching · 3 productive bankers/);checks++;
console.log(JSON.stringify({suite:'department-workforce-ui',checks,source:'actual assembled engine and workforce UI',months:1}));
