'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const html=process.argv.includes('--portable')?fs.readFileSync(require('path').join(__dirname,'../BRANCH_WARS.html'),'utf8'):require('../tools/build_game').assemble().html;
const context={};vm.runInNewContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1].replace('root.BWEngine={','root.BWEngine={__validatePlan:validatePlan,'),context);const E=context.BWEngine,D=E.DigitalCommercial,copy=x=>JSON.parse(JSON.stringify(x));
const flags={currentReporting:true,currentEconomics:true,currentRivalry:true,currentResearch:true,currentLending:true,currentMonetaryPolicy:true,currentBusiness:true,currentDigitalCommercial:true};
const create=(current=true)=>E.createGame({...E.previewCampaignEdition({},'expanded',{...flags,currentDigitalCommercial:current}).options,mode:'hotseat',seed:'digital-commercial',created:1,startingWorkforce:'covered'});
function plan(g,i=0){const p=g.players[i],q=E.chooseBot(g,i);return {...q,newProjects:[],newProject:null,projectTargets:{},nodeFunding:{},investments:{},hires:0,specialistHires:E.emptySpecialistOrders(),opportunity:null,contractBid:null,contractExit:null,competitiveAction:'none',capitalAction:false,decision:'b',departmentPolicy:{...q.departmentPolicy,envelopes:{...q.departmentPolicy.envelopes,research:250000}}};}
test('9.37 opt-in has five private nodes; 9.36 imports and setup keep original books',()=>{const g=create();assert.equal(g.version,'9.37');assert.equal(Object.keys(D.NODES).length,5);E.validatePilot(g);assert.deepEqual(copy(E.migrateCampaign(copy(g))),copy(g));const old=create(false);assert.equal(old.version,'9.36');assert.equal(old.players[0].digitalCommercial,undefined);const v=E.publicState(g,0);D.validate(v,'view');assert.equal(v.rival.digitalCommercial,undefined);const invalid=copy(g);invalid.players[0].digitalCommercial.nodes.paymentsIntegration.funded=1000;assert.throws(()=>E.validatePilot(invalid));});
test('prerequisites, shared funding cap, quote purity, resources and exactly-once completion',()=>{const g=create(),p=g.players[0],q=plan(g),before=JSON.stringify(g),quote=D.quote(g,p,q,'digitalArchitecture');assert.equal(quote.maximum,100000);assert.equal(JSON.stringify(g),before);assert.throws(()=>D.validatePlan(p,{nodeFunding:{workflowAutomation:1000}}),/earlier month/);assert.throws(()=>D.validatePlan(p,{nodeFunding:{digitalArchitecture:100000,relationshipPlanning:1000}}),/monthly funding cap/);const cash=p.stats.cash,capital=p.stats.capital;D.settle(g,p,{nodeFunding:{digitalArchitecture:100000}});assert.equal(p.stats.cash,cash-100000);assert.equal(p.stats.capital,capital-100000);assert.equal(p.digitalCommercial.nodes.digitalArchitecture.completed,1);assert.throws(()=>D.settle(g,p,{nodeFunding:{digitalArchitecture:1000}}),/already completed/);assert.equal(D.technology(p,20),16);assert.equal(D.technology(create(false).players[0],20),20);});
test('funded partial research survives real monthly settlement and half-ready reload',()=>{let g=create(),q=plan(g);q.nodeFunding={relationshipPlanning:25000};E.submit(g,0,q);g=E.migrateCampaign(copy(g));E.submit(g,1,plan(g,1));assert.equal(g.players[0].digitalCommercial.nodes.relationshipPlanning.funded,25000);assert.equal(D.has(g.players[0],'relationshipPlanning'),false);q=plan(g);q.nodeFunding={relationshipPlanning:25000};E.submit(g,0,q);E.submit(g,1,plan(g,1));assert.equal(g.players[0].digitalCommercial.nodes.relationshipPlanning.completed,2);E.validatePilot(g);E.validateLedger(g);const restored=E.migrateCampaign(copy(g));assert.deepEqual(copy(restored),copy(g));});
test('real consumers stack once on active platforms; internal and partner routes keep costs',()=>{const g=create(),p=g.players[0];for(const key of Object.keys(D.NODES))p.digitalCommercial.nodes[key]={funded:D.NODES[key].cost,completed:1};assert.equal(D.combined(p),true);p.serviceDesk.applications.treasury='build';p.serviceDesk.policy.treasury=true;assert(Math.abs(D.load(p,'treasury')-3*.85*.9)<1e-9);assert.equal(D.cost(p,'treasury',9000),8100);assert.equal(D.bid(p),1);assert.equal(D.technology(p,20),16);p.serviceDesk.policy.treasury=false;assert.equal(D.cost(p,'treasury',9000),9000);assert.equal(D.load(p,'treasury'),2.7);for(const [key,cost,cycles]of [['buildTreasuryDesk',220000,3],['partnerTreasuryDesk',60000,1]]){assert.equal(E.SERVICE_APPLICATIONS[key].cost,cost);assert.equal(E.SERVICE_APPLICATIONS[key].cycles,cycles);}assert.equal(D.platformIssue(p,'buildTreasuryDesk'),'');});
test('complete paid internal journey: research, deployment reloads, empty cost, lost bid, win and collection',()=>{
 let g=E.createGame({...E.previewCampaignEdition({},'expanded',flags).options,mode:'hotseat',seed:'digital-journey',created:1,startingWorkforce:'covered',name1:'Burgen Bank',name2:'Rival Bank'});
 const authored=require('./fixtures/digital-commercial-plans.json').plansByMonth,history=[];
 for(const row of authored){assert.equal(g.cycle,row.month);E.submit(g,0,copy(row.plans[0]));g=E.migrateCampaign(copy(g));E.submit(g,1,copy(row.plans[1]));E.validatePilot(g);E.validateLedger(g);assert.deepEqual(copy(E.migrateCampaign(copy(g))),copy(g));const p=g.players[0];history.push({month:row.month,p:copy(p)});}
 assert.equal(history[4].p.digitalCommercial.nodes.paymentsIntegration.funded,100000);assert.equal(history[4].p.digitalCommercial.nodes.paymentsIntegration.completed,0);assert.equal(history[5].p.digitalCommercial.nodes.paymentsIntegration.completed,6);
 assert(history[6].p.projects.some(p=>p.key==='buildTreasuryDesk'));assert(history[7].p.projects.some(p=>p.key==='buildTreasuryDesk'));assert.equal(history[8].p.serviceDesk.applications.treasury,'build');
 assert.equal(history[11].p.serviceDesk.contracts.length,0);assert.equal(history[11].p.operatingReport.contractFees,0);assert.equal(history[11].p.operatingReport.contractServicing,12000);
 assert.equal(history[14].p.operatingReport.contractFees,0);assert.equal(history[14].p.serviceDesk.contracts.length,1);
 const p=g.players[0],r=p.operatingReport;assert.equal(r.corporateFeesPaid,50000);assert.equal(r.serviceDirect,8100);assert.equal(r.servicePlatform,6000);assert.equal(r.serviceOutsourcing,6000);assert.equal(r.contractServicing,20100);
 const short=copy(p);short.serviceDesk.policy.staff=0;short.serviceDesk.policy.outsourcing=0;const load=E.serviceLoad(short);assert.equal(load.served,0);assert.equal(load.fees,0);assert(load.platform>0,'Empty or uncovered delivery still pays active platform upkeep');
});
test('custom funding cannot strand a final amount below the usual minimum',()=>{const g=create(),p=g.players[0];D.settle(g,p,{nodeFunding:{relationshipPlanning:49999}});const q=plan(g);assert.equal(D.quote(g,p,q,'relationshipPlanning').maximum,1);D.validatePlan(p,{nodeFunding:{relationshipPlanning:1}});g.cycle++;D.settle(g,p,{nodeFunding:{relationshipPlanning:1}});assert(D.has(p,'relationshipPlanning'));});
