'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const copy=x=>JSON.parse(JSON.stringify(x));
function load(html){const c={};vm.runInNewContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1].replace('root.BWEngine={','root.BWEngine={__validatePlan:validatePlan,__settleCompanies:settleCompanyShareAuction,__companyState:companyShareState,__groupSummary:companyConsolidatedSummary,'),c);return c.BWEngine;}
const html=process.argv.includes('--portable')?fs.readFileSync(path.join(__dirname,'../BRANCH_WARS.html'),'utf8'):require('../tools/build_game').assemble().html,E=load(html),H=E.HoldingCapital;
const flags={currentReporting:true,currentEconomics:true,currentRivalry:true,currentResearch:true,currentLending:true,currentMonetaryPolicy:true};
function create(current=true){return E.createGame({...E.previewCampaignEdition({},'expanded',{...flags,currentBusiness:current}).options,seed:'holding-capital',created:1,mode:'hotseat',startingWorkforce:'covered'});}
function fund(g,amount=500000){for(const p of g.players)p.financialGroup.parent=E.GroupAccounting.post(p.financialGroup.parent,'fixture.externalCapital','fixture',{cash:amount,equity:amount});H.finish(g);return g;}
function plan(g,i=0){const p=g.players[i],q=E.chooseBot(g,i);return {...q,newProject:null,newProjects:[],projectTargets:{},investments:{},hires:0,specialistHires:Object.fromEntries(Object.keys(q.specialistHires||{}).map(k=>[k,0])),opportunity:null,contractBid:null,contractExit:null,capitalAction:false,competitiveAction:'none',decision:'b',companyShareOrders:[],companyControlPolicy:{...q.companyControlPolicy,diligence:null,defend:null,offer:null,cancel:null,consents:[]},groupPolicy:E.defaultGroupPlan(p),agencyPolicy:E.defaultAgencyPlan(p),holdingCapitalOrders:H.defaults(p)};}
function orders(g){return g.players.map((_,i)=>plan(g,i));}
function capital(q,action,shares,limitCents){q.holdingCapitalOrders.capital={action,shares,limitCents};}
function rival(q,side,shares,limitCents){q.holdingCapitalOrders.rival={side,shares,limitCents};}
const issuer=(g,i)=>g.holdingCapitalMarket.issuers.find(r=>r.id===g.players[i].id);
const cash=g=>g.players.reduce((n,p)=>n+p.financialGroup.parent.accounts.cash,0)+g.companyShareMarket.outside.book.accounts.cash;
function checkBooks(g){for(const p of g.players){E.GroupAccounting.validate(p.financialGroup.parent);assert.equal(p.financialGroup.parent.accounts.businessAssets,H.basis(p)+Object.values(p.companyShares.positions).reduce((n,x)=>n+x.basis,0));}E.GroupAccounting.validate(g.companyShareMarket.outside.book);assert.equal(g.companyShareMarket.outside.book.accounts.businessAssets,H.outsideBasis(g)+Object.values(g.companyShareMarket.outside.positions).reduce((n,x)=>n+x.basis,0));}
function step(g,plans=orders(g)){E.submit(g,0,plans[0]);const restored=E.migrateCampaign(copy(g));E.submit(restored,1,plans[1]);E.validatePilot(restored);E.validateLedger(restored);for(let i=0;i<2;i++)E.validateFinancialGroupView(E.publicState(restored,i));return restored;}

test('nonzero issuance dilutes founders, transfers existing buyer cash and recognizes capital rather than income',()=>{
 const g=fund(create()),q=orders(g),p=g.players[0],quote=H.quotes(issuer(g,0));capital(q[0],'issue',20000,quote.issue);rival(q[1],'buy',5000,quote.issue);const before=copy(g),opening=cash(g),bank=JSON.stringify(g.players.map(p=>p.accounting));
 H.settle(g,q);assert.equal(cash(g),opening);assert.equal(issuer(g,0).issued,115000);assert.equal(issuer(g,0).outside.shares,10000);assert.equal(g.players[1].holdingShares.shares,5000);assert.equal(p.financialGroup.parent.retainedEarnings,before.players[0].financialGroup.parent.retainedEarnings);assert.equal(p.financialGroup.parent.accounts.equity-before.players[0].financialGroup.parent.accounts.equity,Math.ceil(15000*quote.issue/100));assert.equal(JSON.stringify(g.players.map(p=>p.accounting)),bank);checkBooks(g);
});
test('holding subscriptions and company purchases share one opening envelope without reserving paid holding cash twice',()=>{
 const g=fund(create(),200000),q=orders(g),price=H.quotes(issuer(g,0)).issue,shares=Math.min(20000,Math.floor(140000*100/price));capital(q[0],'issue',shares,price);rival(q[1],'buy',shares,price);q[1].companyShareOrders=[{issuer:'company:0',side:'buy',shares:100,limitCents:1500}];for(let i=0;i<2;i++)H.quote(g,g.players[i],q[i]);
 H.settle(g,q);assert(g.players[1].holdingShares.shares>0);assert.doesNotThrow(()=>E.__settleCompanies(g,q));checkBooks(g);
});
test('pure public quotes preserve simulation RNG and reject malformed, unfunded and unsupported instructions',()=>{
 const g=fund(create()),q=orders(g),before=JSON.stringify([g,q]),p=g.players[0];
 for(let n=0;n<4;n++){H.quote(g,p,q[0]);H.quote(E.publicState(g,0),E.publicState(g,0).me,q[0]);}assert.equal(JSON.stringify([g,q]),before);
 for(const bad of [null,0,false,{},[],{...H.defaults(p),extra:1},{capital:{action:'issue',shares:0,limitCents:1},rival:H.defaults(p).rival},{capital:{action:'issue',shares:20001,limitCents:1},rival:H.defaults(p).rival},{capital:H.defaults(p).capital,rival:{side:'sell',shares:1,limitCents:1}}])assert.throws(()=>H.quote(g,p,{...q[0],holdingCapitalOrders:bad}));
 const dry=create(),dryPlan=plan(dry);rival(dryPlan,'buy',1,100);assert.throws(()=>H.quote(dry,dry.players[0],dryPlan),/unreserved parent cash/);dryPlan.groupPolicy.bankDividend=100000;assert.throws(()=>H.quote(dry,dry.players[0],dryPlan),/unreserved parent cash/);
 const old=create(false);assert.throws(()=>H.normalize(old,old.players[0],{holdingCapitalOrders:H.defaults(old.players[0])}),/not enabled/);assert.equal(JSON.stringify([g,q]),before);
});
test('noncrossing limits show zero conditional effects; executable full-fill effects use cash and cost basis',()=>{
 const g=fund(create()),q=orders(g),p=g.players[0],own=H.quotes(issuer(g,0)),other=H.quotes(issuer(g,1));capital(q[0],'issue',1000,own.issue+1);rival(q[0],'buy',1000,1);let r=H.quote(g,p,q[0]);assert.equal(r.maximumProceeds,0);assert.equal(r.issuedAfter,issuer(g,0).issued);assert.equal(r.parentCashAfter,p.financialGroup.parent.accounts.cash);assert.equal(r.parentEquityAfter,p.financialGroup.parent.accounts.equity);assert.equal(r.conditionalEffects.ownCrosses,false);assert.equal(r.conditionalEffects.rivalCrosses,false);
 capital(q[0],'issue',1000,own.issue);rival(q[0],'buy',1000,other.buy);r=H.quote(g,p,q[0]);assert.equal(r.parentCashAfter,p.financialGroup.parent.accounts.cash+10*own.issue-10*other.buy);assert.equal(r.parentEquityAfter,p.financialGroup.parent.accounts.equity+10*own.issue);assert.equal(r.rivalSharesAfter,1000);assert.equal(r.rivalOwnershipAfter,1);
 rival(q[0],'buy',1000,other.issue);r=H.quote(g,p,q[0]);assert.equal(r.conditionalEffects.rivalPrimaryOnly,true);assert.match(r.conditionalEffects.note,/voluntary rival/);
});
test('repurchase retires only outside or voluntarily tendered human shares, and sales realize released cost basis',()=>{
 const g=fund(create()),q=orders(g),pr=H.quotes(issuer(g,0));capital(q[0],'issue',15000,pr.issue);rival(q[1],'buy',5000,pr.issue);H.settle(g,q);const human=copy(g.players[1].holdingShares);
 g.cycle++;H.finish(g);let next=q.map((p,i)=>({...copy(p),holdingCapitalOrders:H.defaults(g.players[i])}));capital(next[0],'repurchase',15000,H.quotes(issuer(g,0)).buy);let opening=cash(g);H.settle(g,next);assert.equal(issuer(g,0).issued,105000);assert.deepEqual(copy(g.players[1].holdingShares),human,'An issuer cannot compel a rival tender');assert.equal(cash(g),opening);checkBooks(g);
 g.cycle++;H.finish(g);next=next.map((p,i)=>({...copy(p),holdingCapitalOrders:H.defaults(g.players[i])}));const price=H.quotes(issuer(g,0)).buy;capital(next[0],'repurchase',5000,price);rival(next[1],'sell',5000,price);const seller=g.players[1],before=copy(seller.financialGroup.parent),quote=H.quote(g,seller,next[1]);opening=cash(g);H.settle(g,next);assert.equal(issuer(g,0).issued,100000);assert.equal(seller.holdingShares.shares,0);assert.equal(seller.holdingShares.basis,0);assert.equal(seller.financialGroup.parent.accounts.cash,quote.parentCashAfter);assert.equal(seller.financialGroup.parent.accounts.equity,quote.parentEquityAfter);assert.equal(seller.financialGroup.parent.retainedEarnings-before.retainedEarnings,5000*price/100-human.basis);assert.equal(cash(g),opening);checkBooks(g);
});
test('secondary dealer fills respect existing shares, current quotes, liquidity and exact partial basis release',()=>{
 const g=fund(create()),q=orders(g);capital(q[0],'issue',20000,H.quotes(issuer(g,0)).issue);H.settle(g,q);assert.equal(issuer(g,0).issued,110000,'Outside subscription capped at10000');
 g.cycle++;H.finish(g);let next=q.map((p,i)=>({...copy(p),holdingCapitalOrders:H.defaults(g.players[i])})),price=H.quotes(issuer(g,0)).buy;rival(next[1],'buy',15000,price);const before=copy(g.players[1].financialGroup.parent);H.settle(g,next);assert.equal(g.players[1].holdingShares.shares,10000);assert.equal(g.players[1].financialGroup.parent.accounts.cash,before.accounts.cash-10000*price/100);assert.equal(issuer(g,0).outside.shares,0);
 g.cycle++;H.finish(g);next=next.map((p,i)=>({...copy(p),holdingCapitalOrders:H.defaults(g.players[i])}));price=H.quotes(issuer(g,0)).sell;rival(next[1],'sell',1234,price);const basis=g.players[1].holdingShares.basis,quote=H.quote(g,g.players[1],next[1]),opening=cash(g);H.settle(g,next);assert.equal(g.players[1].holdingShares.basis,basis-Math.floor(basis*1234/10000));assert.equal(g.players[1].financialGroup.parent.accounts.cash,quote.parentCashAfter);assert.equal(g.players[1].financialGroup.parent.accounts.equity,quote.parentEquityAfter);assert.equal(cash(g),opening);checkBooks(g);
});
test('issuance reaches but cannot cross founder control floor and never creates an unfunded subscription',()=>{
 const g=create(),buyer=g.players[1];buyer.financialGroup.parent=E.GroupAccounting.post(buyer.financialGroup.parent,'fixture.capital','fixture',{cash:2000000,equity:2000000});H.finish(g);let q=orders(g);
 while(issuer(g,0).issued<196078){const max=H.quote(g,g.players[0],q[0]).maxIssue;assert(max>0);const price=H.quotes(issuer(g,0)).issue;capital(q[0],'issue',max,price);rival(q[1],'buy',max,price);const opening=cash(g);H.settle(g,q);assert.equal(cash(g),opening);g.cycle++;H.finish(g);q=q.map((p,i)=>({...copy(p),holdingCapitalOrders:H.defaults(g.players[i])}));}
 assert(100*issuer(g,0).founderShares/issuer(g,0).issued>=51);assert.equal(H.quote(g,g.players[0],q[0]).maxIssue,0);capital(q[0],'issue',1,1);assert.throws(()=>H.quote(g,g.players[0],q[0]),/51%/);checkBooks(g);
 const constrained=create(),empty=orders(constrained),market=constrained.companyShareMarket,withdraw=market.outside.book.accounts.cash-13;market.outside.book=E.GroupAccounting.post(market.outside.book,'fixture.cashWithdrawal','fixture',{cash:-withdraw,equity:-withdraw});capital(empty[0],'issue',20000,H.quotes(issuer(constrained,0)).issue);const opening=cash(constrained);H.settle(constrained,empty);assert(issuer(constrained,0).outside.shares<20000);assert(market.outside.book.accounts.cash>=0);assert.equal(cash(constrained),opening);checkBooks(constrained);
});
test('full real settlement, half-ready reload and both private views reconcile nonzero ownership plus company orders',()=>{
 let g=fund(create(),200000),q=orders(g),price=H.quotes(issuer(g,0)).issue,shares=Math.min(20000,Math.floor(130000*100/price));capital(q[0],'issue',shares,price);rival(q[1],'buy',shares,price);q[1].companyShareOrders=[{issuer:'company:0',side:'buy',shares:100,limitCents:1500}];
 E.submit(g,0,q[0]);const first=E.publicState(g,0),other=E.publicState(g,1);assert.deepEqual(copy(first.me.pendingHoldingCapitalOrders),copy(q[0].holdingCapitalOrders));assert.equal(other.rival.pendingHoldingCapitalOrders,undefined);assert.equal(other.rival.holdingShares,undefined);assert.equal(other.me.pendingHoldingCapitalOrders,undefined);const restored=E.migrateCampaign(copy(g));E.submit(g,1,q[1]);E.submit(restored,1,copy(q[1]));assert.deepEqual(copy(restored),copy(g));E.validatePilot(g);E.validateLedger(g);checkBooks(g);assert(g.players[1].holdingShares.shares>0);
 for(let i=0;i<2;i++){const v=E.publicState(g,i);E.validateFinancialGroupView(v);assert.equal(v.rival.holdingShares,undefined);assert.equal(v.lastPlans?.[v.rival.id]?.holdingCapitalOrders,undefined);assert.equal(v.holdingCapitalSnapshot.receipts.length,g.holdingCapitalMarket.receipts.length);}
 g=step(g);checkBooks(g);assert.equal(g.holdingCapitalMarket.month,2);
});
test('saved ownership and public receipts reject stale prices, malformed counts, fake trades and private rival orders',()=>{
 const g=create();for(const mutate of [x=>x.holdingCapitalMarket.issuers[0].referenceCents++,x=>x.holdingCapitalMarket.issuers[0].issued++,x=>x.players[0].holdingShares.issuer=x.players[0].id,x=>x.holdingCapitalMarket.issuers[0].outside.basis=1,x=>x.holdingCapitalMarket.extra=1]){const bad=copy(g);mutate(bad);assert.throws(()=>E.migrateCampaign(bad));}
 const v=E.publicState(g,0);for(const mutate of [x=>x.holdingCapitalSnapshot.issuers.find(i=>i.id===x.me.id).referenceCents++,x=>x.rival.holdingShares=copy(x.me.holdingShares),x=>x.rival.submitted={holdingCapitalOrders:H.defaults(x.me)},x=>x.holdingCapitalSnapshot.issuers[0].rivalShares++,x=>x.holdingCapitalSnapshot.receipts.push({cycle:0,issuer:x.me.id,kind:'issue',buyer:'outside',seller:x.me.id,shares:1,priceCents:100,cash:1})]){const bad=copy(v);mutate(bad);assert.throws(()=>H.validate(bad,'view'));}
 const q=orders(g);capital(q[0],'issue',1000,H.quotes(issuer(g,0)).issue);H.settle(g,q);g.cycle++;H.finish(g);H.validate(g);for(const mutate of [x=>x.holdingCapitalMarket.receipts[0].seller='outside',x=>x.holdingCapitalMarket.receipts.push(copy(x.holdingCapitalMarket.receipts[0])),x=>x.holdingCapitalMarket.receipts[0].cash++]){const bad=copy(g);mutate(bad);assert.throws(()=>H.validate(bad));}
});
test('combined Group commitments and parent reserve constrain buys and repurchases before any receipt exists',()=>{
 const g=fund(create(),200000),q=orders(g),p=g.players[0];rival(q[0],'buy',1000,10000);q[0].agencyPolicy.capital=60000;assert.throws(()=>H.quote(g,p,q[0]),/unreserved parent cash/);q[0].agencyPolicy.capital=0;q[0].investmentPolicy.institution.capital=60000;assert.throws(()=>H.quote(g,p,q[0]),/unreserved parent cash/);q[0].investmentPolicy.institution.capital=0;q[0].groupPolicy.bankSupport=60000;assert.throws(()=>H.quote(g,p,q[0]),/unreserved parent cash/);q[0].groupPolicy.bankSupport=0;q[0].companyShareOrders=[{issuer:'company:0',side:'buy',shares:5000,limitCents:1000}];assert.throws(()=>H.quote(g,p,q[0]),/unreserved parent cash/);q[0].companyShareOrders=[];assert.equal(H.quote(g,p,q[0]).remaining,50000);
});
test('historical creation, funded company orders, half-ready reload and private views replay the preserved engine exactly',()=>{
 const baseline=path.join(__dirname,process.argv.includes('--local-baseline')?'../reports/local/expanded-consolidation-20260927/before-BRANCH_WARS.html':'../../releases/v4-rc4/BRANCH_WARS.html'),old=load(fs.readFileSync(baseline,'utf8'));
 const options={...old.previewCampaignEdition({},'expanded',flags).options,seed:'holding-legacy',mode:'hotseat',created:1,startingWorkforce:'covered'},a=old.createGame(options),b=E.createGame(options);assert.deepEqual(copy(b),copy(a));
 for(const [engine,g]of [[old,a],[E,b]])for(const p of g.players)p.financialGroup.parent=engine.GroupAccounting.post(p.financialGroup.parent,'fixture.capital','fixture',{cash:200000,equity:200000});
 const x=a.players.map((_,i)=>old.chooseBot(a,i)),y=b.players.map((_,i)=>E.chooseBot(b,i));assert.deepEqual(copy(y),copy(x));for(const q of [x[0],y[0]])q.companyShareOrders=[{issuer:'company:0',side:'buy',shares:100,limitCents:1500}];
 old.submit(a,0,x[0]);E.submit(b,0,y[0]);assert.deepEqual(copy(E.migrateCampaign(copy(b))),copy(old.migrateCampaign(copy(a))));old.submit(a,1,x[1]);E.submit(b,1,y[1]);assert.deepEqual(copy(b),copy(a));for(const seat of [0,1])assert.deepEqual(copy(E.publicState(b,seat)),copy(old.publicState(a,seat)));assert.equal(b.holdingCapitalMarket,undefined);
});
module.exports={E,H,create,fund,plan,orders,capital,rival,issuer,cash,checkBooks,step,load};
