'use strict';
if(!process.argv.includes('--portable')&&!process.argv.includes('--source'))process.argv.push('--source');
const assert=require('node:assert/strict'),{test}=require('node:test');
const {harness}=require('./github_resilience.test');
function fresh(options=''){
 const h=harness(),original=h.c.document.querySelector;
 h.c.document.querySelector=selector=>{const node=original(selector);if(node.financeReady)return node;node.financeReady=true;node.addEventListener=function(event,fn){this.listeners[event]=fn;};node.insertAdjacentHTML=function(where,html){this.adjacentHTML=(this.adjacentHTML||'')+html;parse(html);};let content='';
 Object.defineProperty(node,'innerHTML',{configurable:true,get:()=>content,set:html=>{content=html;parse(html);}});return node;};
 function parse(html){for(const match of String(html).matchAll(/<(?:button|input|select|div|h2)[^>]*\bid="([^"]+)"[^>]*>/g)){const el=h.c.document.querySelector('#'+match[1]);el.listeners={};el.onclick=null;el.disabled=/\sdisabled(?:\s|>)/.test(match[0]);if(match[0].startsWith('<input'))el.value=match[0].match(/\bvalue="([^"]*)"/)?.[1]||'';}}
 h.run(`game=E.createGame({...E.previewCampaignEdition({},'expanded',{currentReporting:true,currentEconomics:true,currentResearch:true,currentRivalry:true,currentLending:true,currentMonetaryPolicy:true}).options,seed:9,created:1,mode:'hotseat'${options}});seat=0;gh.active=false;p2pRole='';newDraft(currentView());draft.decision='b';errors=[];toast=x=>errors.push(x);interfaceSetLocation=()=>{};renderReady=()=>{};`);
 h.render=(workspace,view,context={})=>h.run(`interfaceState.route=${JSON.stringify({workspace,view,context})};${workspace==='banking'?'renderInterfaceBanking':'renderInterfaceGroup'}(currentView(),interfaceState.route,$('#testMount'));`);
 h.click=id=>{const e=h.elements.get('#'+id);assert(e,'control '+id);if(!e.disabled)(e.listeners.click||e.onclick)?.();};
 h.input=(id,value)=>{const e=h.elements.get('#'+id);e.value=value;e.listeners.input({target:e});};
 return h;
}
// Explicit engine-settled funded test fixture, not earned campaign progress.
test('partner Cards keeps launch locked behind research and preserves working edits and other draft fields',()=>{
 const h=fresh(',expandedBusinessVersion:1,digitalCommercialVersion:1,partnerCardsVersion:1'),before=h.run('JSON.stringify([game,draft])');
 h.render('banking','cards',{objectId:'program'});assert(h.elements.get('#financeDetail').innerHTML.includes('Cedar Reserve'));
 h.click('financeField0Choice1');assert.equal(h.elements.get('#financeStage').disabled,true);assert(h.elements.get('#financeQuote').innerHTML.includes('Complete Digital Architecture'));
 assert.equal(h.run('JSON.stringify([game,draft])'),before);h.render('banking','cards',{objectId:'customers'});h.render('banking','cards',{objectId:'program'});assert.equal(h.elements.get('#financeStage').disabled,true,'Unstaged launch choice persists');
 h.click('financeDiscard');h.render('banking','cards',{objectId:'program'});assert.equal(h.elements.get('#financeStage').disabled,false);
 h.render('banking','cards',{objectId:'terms'});assert(h.elements.get('#financeEditorMount').innerHTML.includes('No annual fee'));
 h.render('banking','cards',{objectId:'results'});assert(h.elements.get('#financeEditorMount').innerHTML.includes('Cedar Reserve'));
 assert.equal(h.run('JSON.stringify([game,draft])'),before);
});

// Funding exists only here to reach active-company presentation contracts.
function fundedCompany(h,kind){h.c.fixtureKind=kind;h.run(`
 game.players[0].financialGroup.parent=E.GroupAccounting.post(game.players[0].financialGroup.parent,'test.endowment','fixture',{cash:500000,equity:500000});
 fixturePlans=[];for(seat=0;seat<2;seat++){newDraft(currentView());draft.decision='b';if(seat===0){if(fixtureKind==='agency'){draft.agencyPolicy.launch=true;draft.agencyPolicy.capital=120000;}else{draft.investmentPolicy.institution.launch=true;draft.investmentPolicy.institution.capital=300000;draft.investmentPolicy.institution.roles={adviser:1,broker:0,principal:0,operations:1};}}fixturePlans.push(JSON.parse(JSON.stringify(draft)));}
 E.submit(game,0,fixturePlans[0]);E.submit(game,1,fixturePlans[1]);seat=0;newDraft(currentView());draft.decision='b';`);}
function financeNavigation(h){h.run(`openInterfaceWorkspace=(workspace,view,context)=>{interfaceState.route={workspace,view,context};if(workspace==='group')renderInterfaceGroup(currentView(),interfaceState.route,$('#testMount'));else renderInterfaceEmployerPeople(currentView(),interfaceState.route,$('#testMount'));return true;};interfaceNavigate=item=>openInterfaceWorkspace(item.workspace,item.view,item.context);`);}
test('every opening Banking and Group inspector renders against current engine without changing simulation or draft',()=>{
 const h=fresh(),before=h.run('JSON.stringify([game,draft])'),failures=[];
 const routes=[['banking','deposits',{objectId:'essential'}],['banking','deposits',{objectId:'base'}],['banking','deposits',{objectId:'term'}],['banking','deposits',{objectId:'households'}],['banking','deposits',{objectId:'offers'}],['banking','deposits',{objectId:'applications'}],['banking','deposits',{objectId:'rewards',mode:'delivery'}],['banking','lending',{objectId:'portfolio'}],['banking','lending',{objectId:'standards'}],['banking','lending',{objectId:'collections'}],['banking','lending',{objectId:'acquisition'}],['banking','services',{objectId:'delivery'}],['banking','services',{objectId:'pricing'}],['banking','services',{objectId:'product'}],['banking','treasury',{objectId:'liquidity'}],['banking','treasury',{objectId:'rates'}],['banking','treasury',{objectId:'investments'}],['banking','treasury',{objectId:'board'}],['banking','treasury',{objectId:'recovery'}],['group','parent',{}],['group','parent',{objectId:'statements'}],['group','agency',{objectId:'operations'}],['group','agency',{objectId:'funding'}],['group','agency',{objectId:'covers'}],['group','agency',{objectId:'results'}],...['operations','funding','development','securities','results','close'].map(objectId=>['group','investment',{objectId}]),...['statements','shares','control'].map(mode=>['group','companies',{companyId:'company:0',mode}])];
 for(const r of routes)try{h.render(...r);}catch(e){failures.push(r.join(' / ')+': '+e.stack);}
 for(const a of JSON.parse(h.run('JSON.stringify(currentView().serviceAgreements)')))for(const mode of ['agreement','account'])try{h.render('banking','services',{agreementId:a.id,mode});}catch(e){failures.push('agreement '+a.id+' '+mode+': '+e.stack);}
 assert.deepEqual(failures,[]);assert.equal(h.run('JSON.stringify([game,draft])'),before);
});
test('deposit pricing uses engine monthly units, stages explicitly, and old callbacks cannot mutate after route replacement',()=>{
 const h=fresh();h.render('banking','deposits',{objectId:'essential'});const before=h.run('JSON.stringify(draft)'),html=h.elements.get('#financeDetail').innerHTML,expected=h.run('(E.productPricingQuote(currentView().me,currentView(),draft).rows.essential.rate*12/10000).toFixed(3)+"%"');assert(html.includes(expected));h.click('financeField0Choice2');assert.equal(h.run('JSON.stringify(draft)'),before);const stale=h.elements.get('#financeStage').listeners.click;h.render('banking','lending',{objectId:'standards'});stale();assert.equal(h.run('JSON.stringify(draft)'),before);h.render('banking','deposits',{objectId:'essential'});h.click('financeStage');assert.equal(h.run('draft.productProgramPolicy.pricingBp.essential'),25);
});
test('empty numeric input persists across navigation and cannot become zero or alter the monthly draft',()=>{
 const h=fresh();h.render('group','parent',{});h.input('financeField0','');const before=h.run('JSON.stringify(draft)');assert.equal(h.elements.get('#financeStage').disabled,true);h.render('banking','treasury',{});h.render('group','parent',{});assert.equal(h.elements.get('#financeField0').value,'');h.click('financeStage');assert.equal(h.run('JSON.stringify(draft)'),before);assert.equal(h.run('pendingInterfaceFinanceEdits(currentView()).length'),1);
});
test('employer shared forms patch owned fields only and retain other workspace edits',()=>{
 const h=fresh();fundedCompany(h,'agency');h.render('group','agency',{objectId:'operations'});h.click('financeField1Choice2');assert.equal(h.run('draft.agencyPolicy.outreach'),0);
 h.run(`interfaceState.route={workspace:'people',view:'staff',context:{employer:'agency'}};renderInterfaceEmployerPeople(currentView(),interfaceState.route,$('#testMount'));`);const role=h.run('Object.keys(E.AGENCY_PROFESSIONAL_ROLES)[0]');h.input('financeField0','2');h.click('financeStage');assert.equal(h.run('draft.agencyPolicy.roles['+JSON.stringify(role)+']'),2);assert.equal(h.run('draft.agencyPolicy.outreach'),0);assert(h.run('pendingInterfaceFinanceEdits(currentView()).length')>0);h.render('group','agency',{objectId:'operations'});h.click('financeStage');assert.equal(h.run('draft.agencyPolicy.outreach'),2);assert.equal(h.run('draft.agencyPolicy.roles['+JSON.stringify(role)+']'),2);
});
test('guest replacement retains working forms while reconnect and owner changes clear them',()=>{
 const h=fresh();h.run('view=E.publicState(game,0);game=null;');h.render('group','parent',{});h.input('financeField0','123');h.run('view=JSON.parse(JSON.stringify(view));');h.render('group','parent',{});assert.equal(h.elements.get('#financeField0').value,'123');h.run('connectionAttempt++');h.render('group','parent',{});assert.equal(h.elements.get('#financeField0').value,'0');
});
test('versioned Expanded campaigns retain supported banking and group views without gaining unsupported client features',()=>{
 const h=fresh();for(const version of [1,3,6,9,10]){
  h.run(`game=E.createGame({...E.previewFeatureSelection({}, {field:'financialGroupVersion',value:${version}}).options,seed:7,created:1,mode:'hotseat'});newDraft(currentView());draft.decision='b';`);
  for(const view of ['deposits','lending','services','treasury'])assert.doesNotThrow(()=>h.render('banking',view,{}),'Group rules '+version+' '+view);
  h.render('group','parent',{});if(version>=3)h.render('group','agency',{});
 }
});
test('selected investment client orders stage independently, remove one order, and keep all customer and bank books unchanged',()=>{
 const h=fresh();fundedCompany(h,'investment');h.run(`fixtureView=currentView();sources=fixtureView.me.investmentSnapshot.funding.slice(0,2);fixtureView.me.investmentSnapshot.clients=sources.map(a=>({id:a.clientId,market:a.market,service:'advice',owner:fixtureView.me.id,custodian:'atlas',cash:2000,units:0,acquired:0,missed:0}));fixtureView.me.investmentSnapshot.cashPositions=sources.map(a=>({clientId:a.clientId,mode:'hold',buffer:1000,affiliate:null,bankId:null,deposit:0,shares:0,value:0}));fixtureView.me.investmentSnapshot.income.accounts=sources.map(a=>({clientId:a.clientId,totalPaid:0,lastPaid:0,lastDue:0,fundIncome:0}));currentView=()=>fixtureView;`);
 const ids=JSON.parse(h.run('JSON.stringify(sources.map(x=>x.clientId))')),before=h.run('JSON.stringify([game,fixtureView])');assert.equal(ids.length,2);
 for(const id of ids){h.render('group','investment',{clientId:id,mode:'cash'});h.input('financeField1','250');h.click('financeField0Choice2');assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');}
 assert.equal(h.run('draft.investmentPolicy.cashOrders.length'),2);h.render('group','investment',{clientId:ids[0],mode:'cash'});h.click('financeRemove');assert.equal(h.run('draft.investmentPolicy.cashOrders.length'),1);assert.equal(h.run('draft.investmentPolicy.cashOrders[0].clientId'),ids[1]);
 h.render('group','investment',{clientId:ids[0],mode:'notes'});assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('draft.investmentPolicy.notes[0].product'),'short');assert.equal(h.run('JSON.stringify([game,fixtureView])'),before);
 for(const mode of ['funding','trades','details'])assert.doesNotThrow(()=>h.render('group','investment',{clientId:ids[0],mode}));
});
test('all monthly opportunities have a canonical banking record and exact inspector',()=>{
 const h=fresh(),items=JSON.parse(h.run('JSON.stringify(currentView().opportunities)'));for(const item of items){h.render('banking',['deposit','wealth'].includes(item.type)?'deposits':item.type==='loan'?'lending':'services',{opportunityId:item.id});assert(h.elements.get('#financeDetail').innerHTML.includes(item.name));assert(h.run('interfaceFinanceState.forms.has('+JSON.stringify('opportunity:'+item.id)+')'));}
});
test('leaving Finance for another workspace invalidates captured edit and stage callbacks immediately',()=>{
 const h=fresh();h.render('banking','deposits',{objectId:'essential'});const edit=h.elements.get('#financeField0Choice2').listeners.click,stage=h.elements.get('#financeStage').listeners.click,before=h.run('JSON.stringify(draft)');h.run("interfaceState.route={workspace:'month',view:'summary',context:{}};");edit();stage();assert.equal(h.run('JSON.stringify(draft)'),before);assert.equal(h.run('interfaceFinanceState.forms.get("deposit-price:essential").dirty'),false);
});
test('comparison modes quote authoritative scenarios without altering books or accepted instructions',()=>{
 const h=fresh(),before=h.run('JSON.stringify([game,draft])');for(const [view,context]of [['deposits',{objectId:'essential',mode:'comparison'}],['deposits',{objectId:'effects'}],['lending',{objectId:'portfolio',mode:'compare'}]]){h.render('banking',view,context);assert(!h.elements.get('#financeEditorMount').innerHTML.includes('Comparison unavailable:'),h.elements.get('#financeEditorMount').innerHTML);}assert.equal(h.run('JSON.stringify([game,draft])'),before);
});
test('re-rendering a planned delivery project does not toggle it off or change its selected target',()=>{
 const h=fresh();h.run(`draft.newProjects=['licenseRewards'];draft.newProject='licenseRewards';`);h.render('banking','deposits',{objectId:'rewards',mode:'delivery',projectId:'licenseRewards'});assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('draft.newProjects.includes("licenseRewards")'),true);
});
test('explicit finance navigation restores visible keyboard focus while ordinary redraw leaves focus alone',()=>{
 const h=fresh(),focused=[];h.c.document.querySelector('#financeInspectorTitle').focus=()=>focused.push('inspector');h.c.document.querySelector('#financeRecord0').focus=()=>focused.push('records');
 h.run(`openInterfaceWorkspace=(workspace,view,context)=>{interfaceState.route={workspace,view,context};renderInterfaceBanking(currentView(),interfaceState.route,$('#testMount'));return true;};`);
 h.render('banking','deposits',{});assert.deepEqual(focused,[]);h.click('financeRecord1');assert.deepEqual(focused,['inspector']);h.render('banking','deposits',{objectId:'rewards'});assert.deepEqual(focused,['inspector']);h.click('financeBackToRecords');assert.deepEqual(focused,['inspector','records']);
});
test('unopened businesses remain locked and Trust has no invented purchase or state',()=>{
 const h=fresh(),before=h.run('JSON.stringify([game,draft])');for(const kind of ['agency','investment'])for(const objectId of [undefined,'operations','development','covers','close']){h.render('group',kind,objectId?{objectId}:{});const html=h.elements.get('#financeWorkspaceContent').innerHTML;assert.match(html,/Locked - this company has not been formed/);assert(!html.includes('finance-record'));assert(!html.includes('id="financeField'));assert(h.elements.get('#financePrepareExpansion'));}h.render('group','trust',{});assert.match(h.elements.get('#financeEditorMount').innerHTML,/Not yet available/);assert.match(h.elements.get('#financeEditorMount').innerHTML,/<button class="btn" disabled>/);assert(!h.run('Object.hasOwn(game.players[0],"trust")'));assert.equal(h.run('JSON.stringify([game,draft])'),before);
});
test('expansion preparation quotes funding, preserves raw input and stays out of the draft',()=>{
 const h=fresh();financeNavigation(h);h.render('group','agency',{});const before=h.run('JSON.stringify([game,draft])');h.click('financePrepareExpansion');assert.equal(h.elements.get('#financeField1').value,'120000');assert.equal(h.elements.get('#financeStage').disabled,true,'Opening parent cannot fund launch');assert.match(h.elements.get('#financeQuote').innerHTML,/120,000/);assert.match(h.elements.get('#financeQuote').innerHTML,/2 months/);h.input('financeField1','');h.render('group','parent',{});h.render('group','agency',{objectId:'funding'});assert.equal(h.elements.get('#financeField1').value,'');assert.equal(h.elements.get('#financeStage').disabled,true);assert.equal(h.run('JSON.stringify([game,draft])'),before);h.render('group','investment',{});h.click('financePrepareExpansion');assert.equal(h.elements.get('#financeStage').disabled,true);assert.match(h.elements.get('#financeQuote').innerHTML,/Combined expansion funding exceeds parent cash/);assert.doesNotMatch(h.elements.get('#financeQuote').innerHTML,/Agency funding exceeds/);
});
test('People preparation and Group funding stage one atomic agency launch without unlocking it',()=>{
 const h=fresh();financeNavigation(h);h.run(`game.players[0].financialGroup.parent=E.GroupAccounting.post(game.players[0].financialGroup.parent,'test.endowment','fixture',{cash:500000,equity:500000});`);h.render('group','agency',{});const before=h.run('JSON.stringify(game)'),draftBefore=h.run('JSON.stringify(draft)');h.click('financePrepareExpansion');h.click('financeAgencyPeople');h.input('financeField0','2');h.click('financeStage');assert.equal(h.run('JSON.stringify(draft)'),draftBefore,'People Review only preserves working choices');assert.equal(h.run('interfaceCurrentRoute().workspace'),'group');assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('draft.agencyPolicy.launch'),true);assert.equal(h.run('draft.agencyPolicy.capital'),120000);assert.equal(h.run('draft.agencyPolicy.roles.propertyProducer'),2);assert.equal(h.run('game.players[0].agency.status'),'unopened');assert.equal(h.run('JSON.stringify(game)'),before);h.render('group','agency',{});assert.match(h.elements.get('#financeWorkspaceContent').innerHTML,/locked until funded settlement/);assert.equal(h.run('pendingInterfaceFinanceEdits(currentView()).length'),0);
});
test('investment expansion combines brokerage permission with People roles and keeps the real delay',()=>{
 const h=fresh();financeNavigation(h);h.run(`game.players[0].financialGroup.parent=E.GroupAccounting.post(game.players[0].financialGroup.parent,'test.endowment','fixture',{cash:600000,equity:600000});`);h.render('group','investment',{});h.click('financePrepareExpansion');h.click('financeField2Choice0');h.click('financeField3Choice1');h.input('financeField1','400000');h.click('financeInvestmentPeople');h.input('financeField1','1');h.input('financeField2','1');h.input('financeField3','1');const before=h.run('JSON.stringify(game)');h.click('financeStage');assert.equal(h.run('draft.investmentPolicy.institution.launch'),false);assert.match(h.elements.get('#financeQuote').innerHTML,/brokerage permission: 3 months/);assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('draft.investmentPolicy.institution.launch'),true);assert.equal(h.run('draft.investmentPolicy.institution.brokerage'),true);assert.equal(h.run('draft.investmentPolicy.institution.roles.broker'),1);assert.equal(h.run('draft.investmentPolicy.institution.roles.principal'),1);assert.equal(h.run('JSON.stringify(game)'),before);h.run(`const expansionQuote=E.InvestmentInstitution.quote(currentView().me.investmentBusiness,draft.investmentPolicy.institution,currentView().me.investmentBusiness.month+1);`);assert.equal(h.run('expansionQuote.permissions.brokerage'),false);assert.equal(h.run('expansionQuote.entity.permissions.brokerage.ready-expansionQuote.entity.permissions.brokerage.applied'),3);
});
test('settled active companies retain operating editors and unopened callbacks respect owner locks',()=>{
 const active=fresh();fundedCompany(active,'agency');active.render('group','agency',{objectId:'operations'});assert.match(active.elements.get('#financeWorkspaceContent').innerHTML,/finance-directory/);assert.equal(active.run('game.players[0].agency.status'),'active');assert.equal(active.run('E.agencyProfessionalStatus(game.players[0].agency,game.cycle).phase'),'registration pending');
 const h=fresh();financeNavigation(h);h.render('group','investment',{});const stale=h.elements.get('#financePrepareExpansion').listeners.click;h.run('seat=1;newDraft(currentView());');const before=h.run('JSON.stringify([game,draft])');stale();assert.equal(h.run('JSON.stringify([game,draft])'),before);h.render('group','investment',{});h.run('game.players[1].submitted=JSON.parse(JSON.stringify(draft));');h.render('group','investment',{});assert.equal(h.elements.get('#financePrepareExpansion').disabled,true);
});
test('closed investment saves expose funded restart and sealed launch review stays read-only',()=>{
 const h=fresh();fundedCompany(h,'investment');h.run(`closurePlans=[];for(seat=0;seat<2;seat++){newDraft(currentView());draft.decision='b';if(!seat)draft.investmentPolicy.close=true;closurePlans.push(JSON.parse(JSON.stringify(draft)));}E.submit(game,0,closurePlans[0]);E.submit(game,1,closurePlans[1]);seat=0;newDraft(currentView());draft.decision='b';`);assert.equal(h.run('game.players[0].investmentBusiness.status'),'closed');financeNavigation(h);h.render('group','investment',{});assert.match(h.elements.get('#financeWorkspaceContent').innerHTML,/funded restart required/);assert.match(h.elements.get('#financeEditorMount').innerHTML,/Prepare funded restart/);h.click('financePrepareExpansion');assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');h.run('game.players[0].submitted=JSON.parse(JSON.stringify(draft));');h.render('group','investment',{});assert.equal(h.elements.get('#financePrepareExpansion').disabled,false,'Own sealed expansion can be inspected');const before=h.run('JSON.stringify([game,draft])');h.click('financePrepareExpansion');assert.equal(h.elements.get('#financeStage').disabled,true);assert.equal(h.run('JSON.stringify([game,draft])'),before);
});
test('bank Treasury retains liquid securities offers independently of subsidiary expansion',()=>{
 const h=fresh(),world=h.run('JSON.stringify(game)');h.render('banking','treasury',{objectId:'securities-offer'});assert.match(h.elements.get('#financeDetail').innerHTML,/Sell securities from bank portfolio/);h.input('financeField0','100');assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('draft.investmentPolicy.inventorySale'),100);assert.equal(h.run('draft.investmentPolicy.institution.launch'),false);h.render('group','investment',{});assert.match(h.elements.get('#financeWorkspaceContent').innerHTML,/Locked - this company/);assert(h.elements.get('#financeExpansionTreasury'));assert.equal(h.run('JSON.stringify(game)'),world);
 const active=fresh();fundedCompany(active,'investment');active.render('group','investment',{objectId:'securities'});assert.match(active.elements.get('#financeEditorMount').innerHTML,/Sell securities from bank portfolio/);assert(!active.elements.get('#financeEditorMount').innerHTML.includes('financeField'));
});
test('Business services has three canonical records and service-specific pricing patches only the selected tariff',()=>{
 const h=fresh(),world=h.run('JSON.stringify(game)');h.render('banking','services',{});
 const html=h.elements.get('#financeWorkspaceContent').innerHTML;
 assert.equal((html.match(/id="financeRecord\d+"/g)||[]).length,3);assert.match(html,/Payroll/);assert.match(html,/Merchant services/);assert.match(html,/Corporate treasury/);
 h.render('banking','services',{objectId:'merchant',mode:'pricing'});const before=JSON.parse(h.run('JSON.stringify(draft)'));h.click('financeField0Choice2');assert.equal(h.run('JSON.stringify(draft)'),JSON.stringify(before));assert.match(h.elements.get('#financeEditorMount').innerHTML,/Set merchant services price/);h.click('financeStage');
 const after=JSON.parse(h.run('JSON.stringify(draft)'));before.servicePolicy.pricing.merchant='premium';assert.deepEqual(after,before);assert.equal(h.run('JSON.stringify(game)'),world);
});
test('service setup compares real Build and Partner quotes without activating or staging either route',()=>{
 const h=fresh(),before=h.run('JSON.stringify([game,draft])');h.render('banking','services',{objectId:'treasury',mode:'setup'});const html=h.elements.get('#financeEditorMount').innerHTML;
 assert.match(html,/Build in-house/);assert.match(html,/Partner/);for(const key of ['buildTreasuryDesk','partnerTreasuryDesk'])assert(html.includes(h.run('financeMoney(E.projectStartTerms(currentView(),currentView().me,'+JSON.stringify(key)+',draft.focus).cost)')));
 assert.equal(h.run('JSON.stringify([game,draft])'),before);assert.match(html,/planned project does not unlock/);
});

test('settled service statement distinguishes current payments, earlier collections and invoice losses',()=>{
 const h=fresh();
 // Presentation fixture: report values are authoritative inputs, not simulated earnings.
 h.run(`game.players[0].operatingReport={cycle:game.cycle-1,contractFees:50000,corporateFeesPaid:0,corporateInvoiceRecovery:42000,corporateFeesReceivable:50000,corporateInvoiceLoss:8000,serviceDirect:8100,serviceOutsourcing:6000,servicePlatform:6000,contractServicing:20100};`);
 const before=h.run('JSON.stringify([game,draft])');h.render('banking','services',{objectId:'treasury'});
 const html=h.elements.get('#financeEditorMount').innerHTML;
 for(const [label,value]of [['Current invoices paid',0],['Earlier invoices collected',42000],['New unpaid invoices',50000],['Invoices written off',8000]])assert.match(html,new RegExp(label+'</dt><dd>\\$'+value.toLocaleString('en-US')+'</dd>'));
 assert.match(html,/do not earn the same fees again/);assert.doesNotMatch(html,/Cash received<\/dt>/);
 assert.equal(h.run('JSON.stringify([game,draft])'),before,'Reading invoice results cannot repost cash or income');
});
test('searchable service client list replaces the service inspector, filters ownership, and preserves search on return',()=>{
 const h=fresh();h.run(`const payrollRows=game.serviceAgreements.filter(a=>a.kind==='payroll');payrollRows[0].owner=game.players[0].id;payrollRows[0].due=game.cycle;fixtureClient=payrollRows[0].id;openInterfaceWorkspace=(workspace,view,context)=>{interfaceState.route={workspace,view,context};renderInterfaceBanking(currentView(),interfaceState.route,$('#testMount'));return true;};`);
 const before=h.run('JSON.stringify([game,draft])');h.render('banking','services',{objectId:'payroll',mode:'clients'});assert.match(h.elements.get('#financeDetail').innerHTML,/Payroll clients/);assert.doesNotMatch(h.elements.get('#financeEditorMount').innerHTML,/financeStage/);
 h.click('financeClientFilter1');const client=h.run('serviceClientPresentation(currentView(),currentView().serviceAgreements.find(a=>a.id===fixtureClient)).name');assert(h.elements.get('#financeClientRows').innerHTML.includes(client));h.input('financeClientSearch',client);h.click('financeClientRow0');assert.equal(h.run('interfaceCurrentRoute().context.agreementId'),h.run('fixtureClient'));h.click('financeServiceClients');assert.equal(h.elements.get('#financeClientSearch').value,client);assert.equal(h.elements.get('#financeClientFilter1').attributes['aria-pressed'],'true');
 h.click('financeClientFilter2');assert(h.elements.get('#financeClientRows').innerHTML.includes(client));h.input('financeClientSearch','no-client-matches-this');assert.match(h.elements.get('#financeClientRows').innerHTML,/No clients match/);assert.equal(h.run('JSON.stringify([game,draft])'),before);
});
test('opportunity semantics route households to Deposits and show need and balance before finite delivery choices',()=>{
 const h=fresh();h.run(`game.opportunities=[{id:'fixture-household',type:'deposit',name:'A household',dept:'service',value:900000,market:Object.keys(game.territories)[0],desc:'A family seeks savings.'},{id:'fixture-wealth',type:'wealth',name:'Private household',dept:'service',value:1200000,market:Object.keys(game.territories)[0]},{id:'fixture-business',type:'business',name:'Company',dept:'business',value:750000,market:Object.keys(game.territories)[0]}];`);
 assert.equal(h.run('financeOpportunityRoute(currentView(),"fixture-household").view'),'deposits');assert.equal(h.run('financeOpportunityRoute(currentView(),"fixture-wealth").view'),'deposits');assert.equal(h.run('financeOpportunityRoute(currentView(),"fixture-business").view'),'services');
 h.render('banking','deposits',{opportunityId:'fixture-household'});const detail=h.elements.get('#financeEditorMount').adjacentHTML;assert.match(detail,/Customer need/);assert.match(detail,/900,000/);assert.match(detail,/customer liabilities, not revenue/);assert(detail.indexOf('Customer need')<detail.indexOf('Capability and delivery'));
 assert.equal(h.run('financeEmployeeTime(7)'),'1 full employee-month + 75% of another');assert.equal(h.run('financeEmployeeTime(1)'),'25% of one employee’s month');
});
test('service results never present quotes as settled income or invent unavailable receipt fields',()=>{
 const h=fresh();h.render('banking','services',{objectId:'payroll'});assert.match(h.elements.get('#financeEditorMount').innerHTML,/No settled service report/);
 h.run(`game.players[0].operatingReport={cycle:game.cycle-1,contractFees:12345,contractServicing:678};`);h.render('banking','services',{objectId:'payroll'});const html=h.elements.get('#financeEditorMount').innerHTML;assert.match(html,/12,345/);assert.match(html,/Unavailable/);assert.match(html,/whole service book/);assert.match(html,/not earned income/);
});
test('working service prices survive unrelated draft changes and stale service controls cannot stage',()=>{
 const h=fresh();h.render('banking','services',{objectId:'payroll',mode:'pricing'});h.click('financeField0Choice0');const stale=h.elements.get('#financeStage').listeners.click;h.run(`draft.focus=Object.keys(currentView().territories).find(k=>k!==draft.focus);`);h.render('banking','services',{objectId:'merchant',mode:'pricing'});const before=h.run('JSON.stringify(draft)');stale();assert.equal(h.run('JSON.stringify(draft)'),before);h.render('banking','services',{objectId:'payroll',mode:'pricing'});assert.equal(h.elements.get('#financeField0Choice0').attributes['aria-pressed'],'true');h.click('financeStage');assert.equal(h.run('draft.servicePolicy.pricing.payroll'),'discount');assert.equal(h.run('draft.servicePolicy.pricing.merchant'),'standard');
 h.render('banking','services',{objectId:'payroll',mode:'pricing'});const readyCallback=h.elements.get('#financeStage').listeners.click;h.run('game.players[0].submitted=JSON.parse(JSON.stringify(draft));');const locked=h.run('JSON.stringify(draft)');readyCallback();assert.equal(h.run('JSON.stringify(draft)'),locked);
});
test('new Expanded rules expose bank-wide digital setup and stage one authoritative platform project without activation',()=>{
 const h=fresh(',expandedBusinessVersion:1'),world=h.run('JSON.stringify(game)');assert.equal(h.run('currentView().me.expandedBusinessVersion'),1);h.render('banking','services',{objectId:'digital-platform'});const html=h.elements.get('#financeEditorMount').innerHTML;assert.match(html,/90,000/);assert.match(html,/220,000/);assert.match(html,/12,000/);assert.match(html,/does not create customers/);
 h.render('banking','services',{objectId:'digital-platform',projectId:'licenseDigitalPlatform'});assert.equal(h.elements.get('#financeStage').disabled,false,h.elements.get('#financeQuote').innerHTML);h.click('financeStage');assert.equal(h.run('E.planInitiatives(draft).filter(k=>k==="licenseDigitalPlatform").length'),1);assert.equal(h.run('currentView().me.expandedBusiness.digital.route'),'none');assert.equal(h.run('JSON.stringify(game)'),world);
 const historical=fresh();historical.render('banking','services',{objectId:'digital-platform'});assert.match(historical.elements.get('#financeEditorMount').innerHTML,/original digital delivery model/);assert.doesNotMatch(historical.elements.get('#financeEditorMount').innerHTML,/financeDigitalRoute/);
});
test('current Group ownership is distinct from company investments and legacy ownership remains the old company route',()=>{
 const h=fresh(',expandedBusinessVersion:1');h.run('holdingCalls=[];renderHoldingCapital=(v,route,mount)=>holdingCalls.push(route.view);');h.render('group','ownership',{});assert.equal(h.run('holdingCalls.join()'),'ownership');assert.match(h.elements.get('#testMount').innerHTML,/Holding-company ownership/);
 const historical=fresh();historical.run('holdingCalls=[];renderHoldingCapital=()=>holdingCalls.push(1);');historical.render('group','ownership',{});assert.equal(historical.run('holdingCalls.length'),0);assert.match(historical.elements.get('#testMount').innerHTML,/Companies/);
});
test('modern corrective action is reachable in Treasury and rejects stale captured project actions',()=>{
 const h=fresh(',expandedBusinessVersion:1');h.render('banking','treasury',{objectId:'recovery',mode:'corrective'});assert.match(h.elements.get('#financeEditorMount').innerHTML,/Corrective risk action/);assert.match(h.elements.get('#financeQuote').innerHTML,/170,000/);const stale=h.elements.get('#financeStage').listeners.click,before=h.run('JSON.stringify(draft)');h.run('connectionAttempt++');stale();assert.equal(h.run('JSON.stringify(draft)'),before);
});
module.exports={fresh};

test('card economics shows recorded payback separately from shared costs and preserves legacy history limits',()=>{
 const h=fresh(',expandedBusinessVersion:1,digitalCommercialVersion:1,partnerCardsVersion:1,cardEconomicsVersion:1');
 h.render('banking','cards',{objectId:'program'});assert.match(h.elements.get('#financeDetail').adjacentHTML||h.elements.get('#financeEditorMount').adjacentHTML||'',/2,500/);assert.match(h.elements.get('#financeEditorMount').innerHTML,/max="1000"/);assert.match(h.elements.get('#financeEditorMount').innerHTML,/step="100"/);
 // Rendering fixture only: earned books are exercised through engine/campaign tests.
 h.run(`game.players[0].cardProgram.ready=1;game.players[0].cardProgram.totals={feesPaid:600,setup:2500,costs:200,marketing:1000};game.players[0].cardProgram.history=[{month:1,feesPaid:600,setup:0,costs:100,marketing:0,contribution:500,acquired:0,coverageBp:10000}];`);
 h.render('banking','cards',{objectId:'results'});const html=h.elements.get('#financeEditorMount').innerHTML;assert.match(html,/Cumulative contribution/);assert.match(html,/3,100/);assert.match(html,/7 more months/);assert.match(html,/scenario, not a forecast/);assert.match(html,/150,000/);
 const old=fresh(',expandedBusinessVersion:1,digitalCommercialVersion:1,partnerCardsVersion:1');old.run('game.players[0].cardProgram.history=[{month:1,feesPaid:0,setup:0,costs:500,marketing:0,contribution:-500,acquired:0,coverageBp:10000}];');old.render('banking','cards',{objectId:'results'});assert.match(old.elements.get('#financeEditorMount').innerHTML,/Lifetime payback is unavailable/);
});

test('twenty-client service book keeps three service records and a bounded overview while search reaches every client',()=>{
 const h=fresh();h.run(`const base=game.serviceAgreements.find(a=>a.kind==='payroll');game.serviceAgreements=Array.from({length:20},(_,i)=>({...base,id:'mature-'+i,owner:game.players[0].id,due:game.cycle+1,clientIndex:i%6}));game.players[0].serviceDesk.contracts=game.serviceAgreements.map(a=>({...a}));`);
 h.render('banking','services',{objectId:'payroll'});const directory=h.elements.get('#financeWorkspaceContent').innerHTML,overview=h.elements.get('#financeEditorMount').innerHTML;
 assert.equal((directory.match(/id="financeRecord\d+"/g)||[]).length,3);assert.match(directory,/20 active clients/);assert.match(overview,/Showing three of 20 signed clients/);assert.equal((overview.match(/<tr>/g)||[]).length,4,'Header and three client preview rows');
 h.render('banking','services',{objectId:'payroll',mode:'clients'});h.click('financeClientFilter1');assert.equal((h.elements.get('#financeClientRows').innerHTML.match(/id="financeClientRow\d+"/g)||[]).length,20);h.input('financeClientSearch','no-such-customer');assert.match(h.elements.get('#financeClientRows').innerHTML,/No clients match/);
});
