'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const html=process.argv.includes('--portable')?fs.readFileSync(path.join(__dirname,'../BRANCH_WARS.html'),'utf8'):require('../tools/build_game').assemble().html,c={};vm.runInNewContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1],c);const E=c.BWEngine,F=E.OutsideFunding,copy=x=>JSON.parse(JSON.stringify(x));
const flags={currentReporting:true,currentEconomics:true,currentRivalry:true,currentResearch:true,currentLending:true,currentMonetaryPolicy:true,currentBusiness:true,currentDigitalCommercial:true};
const create=()=>E.createGame({...E.previewCampaignEdition({},'expanded',flags).options,mode:'hotseat',seed:'outside-funding',created:1,startingWorkforce:'covered'});
function plan(g,i){const p=g.players[i],q=E.chooseBot(g,i);return {...q,newProjects:[],newProject:null,projectTargets:{},investments:{},nodeFunding:{},hires:0,specialistHires:E.emptySpecialistOrders(),opportunity:null,contractBid:null,competitiveAction:'none',capitalAction:false,decision:'b',outsideAdvanceAmount:0};}
test('funding quote does not mutate, consume cash, grant ownership or disclose rival records',()=>{const g=create(),p=g.players[0],before=JSON.stringify(g),q=F.quote(g,p,{outsideAdvanceAmount:200000});assert.equal(JSON.stringify(g),before);assert.equal(q.interest,Math.ceil(200000*(g.monetaryPolicy.upperBp+100)/120000));assert.equal(q.book.entityId,F.ID);assert.equal(g.companyControlMarket.lender.accounts.equity,g.companyControlMarket.capital);const v=E.publicState(g,0);F.validate(v,'view');assert.equal(v.outsideFundingSnapshot.book.journal,undefined);assert.equal(v.rival.outsideAdvance,undefined);assert.equal(q.maturity,2);});
test('actual funded advance, reload, interest and cash repayment reconcile with existing lender',()=>{let g=create(),q=plan(g,0);q.outsideAdvanceAmount=200000;const lender=g.companyControlMarket.lender.accounts.cash;E.submit(g,0,q);g=E.migrateCampaign(copy(g));E.submit(g,1,plan(g,1));assert.equal(g.players[0].outsideAdvance.principal,200000);assert.equal(g.companyControlMarket.lender.accounts.cash,lender-200000);assert.equal(g.players[0].accounting.accounts.payables,200000);E.validatePilot(g);E.validateLedger(g);g=E.migrateCampaign(copy(g));const rate=g.players[0].outsideAdvance.rateBp;E.submit(g,0,plan(g,0));E.submit(g,1,plan(g,1));assert.equal(g.players[0].outsideAdvance,null);const interest=Math.ceil(200000*rate/120000);assert.equal(g.companyControlMarket.lender.accounts.cash,lender+interest);assert.equal(g.companyControlMarket.lender.retainedEarnings,interest);assert.equal(g.outsideFunding.netCashToBanks,-interest);E.validatePilot(g);E.validateLedger(g);});
test('unpaid amounts survive without invented cash, additional interest and explicit consequences',()=>{const g=create(),p=g.players[0];F.settle(g,[{outsideAdvanceAmount:200000},{}]);g.cycle=2;const spent=p.stats.cash;p.accounting=E.AccountingPrototype.post(p.accounting,'test.spend',{cash:-spent,equity:-spent},-spent);p.stats.cash=0;p.stats.capital=p.accounting.accounts.equity;const cash=g.companyControlMarket.lender.accounts.cash;F.settle(g,[{},{}]);assert.equal(g.companyControlMarket.lender.accounts.cash,cash);assert.equal(p.outsideAdvance.principal,200000);assert(p.outsideAdvance.interestDue>0);assert.equal(p.outsideAdvance.misses,1);assert.equal(p.stats.cash,0);assert.match(F.quote(g,p,{outsideAdvanceAmount:1000}).reason,/Repay/);assert.throws(()=>F.settle(g,[{},{}]),/already settled/);const prior=p.outsideAdvance.interestDue;g.cycle++;F.settle(g,[{},{}]);assert.equal(p.outsideAdvance.interestDue-prior,Math.ceil(200000*(p.outsideAdvance.rateBp+200)/120000));E.AccountingPrototype.check(p.accounting);E.GroupAccounting.validate(g.companyControlMarket.lender);});
test('competing applications and acquisition spending share a finite lender balance',()=>{const g=create(),book=g.companyControlMarket.lender,spend=book.accounts.cash-250000;g.companyControlMarket.lender=E.GroupAccounting.post(book,'test.otherCommitment','test',{cash:-spend,equity:-spend},-spend);assert.equal(F.quote(g,g.players[0],{outsideAdvanceAmount:250000}).eligible,true);assert.equal(F.quote(g,g.players[1],{outsideAdvanceAmount:250000}).eligible,true);F.settle(g,[{outsideAdvanceAmount:250000},{outsideAdvanceAmount:250000}]);assert.equal(g.players.filter(p=>p.outsideAdvance).length,1);assert.equal(g.companyControlMarket.lender.accounts.cash,0);assert.equal(g.outsideFunding.report.filter(r=>r.kind==='cancelled').length,1);assert.match(F.quote(g,g.players.find(p=>!p.outsideAdvance),{outsideAdvanceAmount:1000}).reason,/lacks cash/);});
test('public funding validation rejects rival reports and orphan pending requests',()=>{const g=create(),v=copy(E.publicState(g,0));v.outsideFundingSnapshot.report=[{bankId:g.players[1].id,kind:'advance',principal:1000,interestAccrued:0,interestPaid:0,unpaid:1000}];assert.throws(()=>F.validate(v,'view'));const w=copy(E.publicState(g,0));w.me.pendingOutsideAdvanceAmount=1000;assert.throws(()=>F.validate(w,'view'));});
