'use strict';
const assert=require('node:assert/strict');
const {harness}=require('./github_resilience.test.js');
const h=harness();
h.run("game=E.createGame({mode:'hotseat',seed:19,created:1});seat=0;view=E.publicState(game,0);newDraft(view);draft.decision='a';");
const world=h.run('JSON.stringify(game)'),initial=h.run('JSON.stringify(draft)');
h.run('renderStrategy(view)');
let markup=h.elements.get('#strategyTree').innerHTML;
assert.equal((markup.match(/class="strategy-lane /g)||[]).length,5);
assert.equal((markup.match(/Full roadmap/g)||[]).length,5);
assert.equal((markup.match(/class="capability-milestone /g)||[]).length,20,'all existing milestones remain available');
assert(markup.includes('Stage monthly maximum · $250K'),'monthly cap is not represented as guaranteed milestone completion');
assert(!markup.includes('data-strategy-details="network" open'),'roadmaps begin collapsed, current milestone is visible');
assert.equal(h.run('JSON.stringify(game)'),world,'render is world/RNG pure');
assert.equal(h.run('JSON.stringify(draft)'),initial,'render does not stage spending');
assert.equal(h.run("proposeStrategyModel(view,'network','retailDensity')"),false,'tier-zero models cannot stage before tier 1 is funded');
assert.equal(h.run("proposeStrategyModel(view,'unknown','x')"),false);
const exact=h.run("E.fundingStep(view.me,draft,'network',250000)");
assert(h.run("stageStrategyFunding(view,'network',250000)"));
assert.equal(h.run('draft.investments.network'),exact);
assert.equal(h.run("proposeStrategyModel(view,'network','retailDensity')"),false,'partial first tier cannot adopt a model');
h.run("game.players[0].capability.network=260000;view=E.publicState(game,0);newDraft(view);draft.decision='a';stageStrategyFunding(view,'network',250000);renderStrategy(view)");
assert.equal(h.run('draft.investments.network'),20000);
assert(h.elements.get('#strategyTree').innerHTML.includes('Stage to milestone · $20K'));
assert(h.run("proposeStrategyModel(view,'network','retailDensity')"));
assert.equal(h.run('draft.specializations.network'),undefined,'proposal changes no plan');
h.run('strategyModelProposal=null');
assert.equal(h.run('draft.specializations.network'),undefined,'cancellation changes no plan');
h.run("proposeStrategyModel(view,'network','retailDensity');draft.depositPolicy='margin'");
assert.equal(h.run('confirmStrategyModel(view)'),false,'confirmation rejects a changed draft');
assert(h.run("proposeStrategyModel(view,'network','retailDensity')"));
assert(h.run('confirmStrategyModel(view)'));
assert.equal(h.run('draft.specializations.network'),'retailDensity');
h.run('renderStrategy(view)');
assert(h.elements.get('#strategyTree').innerHTML.includes('STAGED · NOT YET ADOPTED'));
assert.equal(h.run('game.players[0].specializations.network'),undefined,'stage does not adopt in authoritative state');
const staged=h.run('JSON.stringify(draft)');
h.run('view.me.submitted=true');
assert.equal(h.run("stageStrategyFunding(view,'network',50000)"),false);
assert.equal(h.run("proposeStrategyModel(view,'network','regionalHub')"),false);
assert.equal(h.run('JSON.stringify(draft)'),staged,'sealed plan handlers preserve draft');
h.run("game.players[0].capability.network=E.CAPABILITY_TIERS.network.at(-1);view=E.publicState(game,0);newDraft(view);renderStrategy(view)");
assert(h.elements.get('#strategyTree').innerHTML.includes('even without further research spending'));
assert(h.run("proposeStrategyModel(view,'network','retailDensity')"),'maxed capabilities retain late model adoption');
assert(h.run('confirmStrategyModel(view)'));
assert.equal(h.run('draft.investments.network'),undefined,'late adoption requires no invented research charge');
// Capability details are local UI state and must survive funding re-renders.
h.elements.get('#strategyTree').querySelectorAll=()=>[{dataset:{strategyDetails:'digital'}}];
h.run('renderStrategy(view)');
assert(h.elements.get('#strategyTree').innerHTML.includes('data-strategy-details="digital" open'));
// Cash/capital bounds come from the engine, not a separately invented UI budget.
h.run("view.me.stats.cash=1500;draft.investments={};renderStrategy(view)");
assert.equal(h.run("strategyFundingStatus(view,'digital').maximum"),h.run("E.fundingStep(view.me,draft,'digital',250000)"));
// Expanded campaigns describe only enabled applications and retain multi-capability requirements.
h.run("game=E.createGame({mode:'hotseat',seed:3,created:1,campaignRulesVersion:1,serviceExpansionVersion:1,managementVersion:2,customerDemandVersion:2,workforceVersion:1,customerOwnershipVersion:1,creditPerformanceVersion:1,segmentDepositsVersion:1,productProgramsVersion:1});view=E.publicState(game,0);newDraft(view);renderStrategy(view)");
markup=h.elements.get('#strategyTree').innerHTML;
assert(markup.includes('Rewards Checking')&&markup.includes('High-Yield Savings'));
assert(markup.includes('COMMERCIAL BANK tier 1 + DIGITAL PLATFORM tier 1'));
assert(markup.includes('licensed route is also available without research'));
assert(markup.includes('Research eligibility is not deployment, activation, new balances or guaranteed profit'));
// Follow the complete monthly resolution, including its late-specialization pass.
// applyInvestments alone is not the complete operating-model rule.
const E=h.c.BWEngine,copy=x=>JSON.parse(JSON.stringify(x));let resolved=0;
for(const branch of Object.keys(E.STRATEGY_BRANCHES))for(const owner of [0,1])for(const scenario of ['reach-tier-one','tier-one-no-spend','maxed-no-spend','permanent-choice']){
 const g=E.createGame({mode:'hotseat',seed:71,created:1}),bank=g.players[owner],first=E.CAPABILITY_TIERS[branch][0],models=Object.keys(E.STRATEGY_SPECIALIZATIONS[branch]);
 bank.capability[branch]=scenario==='reach-tier-one'?first-20000:scenario==='maxed-no-spend'?E.CAPABILITY_TIERS[branch].at(-1):first;
 if(scenario==='permanent-choice')bank.specializations[branch]=models[0];
 const plans=g.players.map((_,seat)=>({...copy(E.chooseBot(g,seat)),investments:{},specializations:{},newProjects:[],newProject:null,hires:0}));
 plans[owner].specializations[branch]=scenario==='permanent-choice'?models[1]:models[0];
 if(scenario==='reach-tier-one')plans[owner].investments[branch]=20000;
 const before=JSON.stringify(g);
 h.c.caseView=E.publicState(g,owner);h.c.casePlan=copy(plans[owner]);h.run('view=caseView;draft=casePlan');
 assert.equal(h.run(`proposeStrategyModel(view,${JSON.stringify(branch)},${JSON.stringify(models[0])})`),scenario!=='permanent-choice',scenario+' UI eligibility');
 assert.equal(JSON.stringify(g),before,'selection preview does not mutate whole engine');
 for(const seat of [1-owner,owner])E.submit(g,seat,copy(plans[seat]));
 assert.equal(g.cycle,2,'both plans completed full monthly settlement');
 assert.equal(bank.specializations[branch],models[0],scenario+' final model');
 assert.equal(bank.capability[branch],scenario==='maxed-no-spend'?E.CAPABILITY_TIERS[branch].at(-1):first,scenario+' exact research spending');
 assert.equal(g.lastPlans[bank.id].investments[branch]||0,scenario==='reach-tier-one'?20000:0,'no fabricated investment needed for late adoption');
 resolved++;
}
// Focus survives controls becoming disabled after a funding re-render.
h.run("$('#fund-network-max');$('#fund-network-less');$('#model-network-retailDensity')");
const maxButton=h.elements.get('#fund-network-max'),lessButton=h.elements.get('#fund-network-less'),modelButton=h.elements.get('#model-network-retailDensity');
let maxFocused=0,lessFocused=0,modelFocused=0;maxButton.focus=()=>maxFocused++;lessButton.focus=()=>lessFocused++;modelButton.focus=()=>modelFocused++;
maxButton.disabled=true;lessButton.disabled=false;
h.run("restoreStrategyFocus('fund-network-max')");assert.equal(lessFocused,1);assert.equal(maxFocused,0,'disabled button cannot swallow keyboard focus');
modelButton.disabled=false;h.run("restoreStrategyFocus('model-network-retailDensity')");assert.equal(modelFocused,1,'confirmed staged model remains reachable');
// Presentation corrections are supported by whole exposed engine consumers.
const effectsGame=E.createGame({mode:'hotseat',seed:42,created:1}),base=copy(effectsGame.players[0]);
const plan={...copy(E.chooseBot(effectsGame,0)),products:{...base.products},investments:{},newProjects:[],newProject:null,hires:0};
const withTier=(branch,tier,p=base)=>{const out=copy(p);out.capability[branch]=E.CAPABILITY_TIERS[branch][tier-1];return out};
const withModel=(branch,key,p=base)=>{const out=copy(p);out.specializations[branch]=key;return out};
const forecast=p=>E.operatingPreview(p,plan,effectsGame.economy);
assert.equal(forecast(withTier('digital',1)).expense,forecast(withTier('digital',2)).expense,'digital tier2 does not reduce expense');
assert(forecast(withModel('digital','automation')).expense<forecast(base).expense,'automation model does reduce base expense');
assert.equal(E.projectCost(withModel('digital','automation'),E.PROJECTS.branch),E.projectCost(base,E.PROJECTS.branch),'automation has no direct project discount');
assert.equal(E.projectCycles(withModel('digital','automation'),E.PROJECTS.branch),E.projectCycles(base,E.PROJECTS.branch),'automation has no project work reduction');
assert(forecast(withTier('commercial',3)).loanGrowth>forecast(withTier('commercial',2)).loanGrowth,'commercial tier3 increases loan production');
const lean=withModel('operations','lean');
assert.equal(E.executionCapacity(lean),E.executionCapacity(base),'lean adds no executive capacity');
assert.equal(E.projectCost(lean,E.PROJECTS.branch),Math.round(E.projectCost(base,E.PROJECTS.branch)*.85));
assert.equal(E.projectCost(withModel('operations','lean',withTier('operations',3)),E.PROJECTS.branch),E.projectCost(withTier('operations',3),E.PROJECTS.branch),'lean project discount does not stack');
assert.equal(E.projectCycles(withTier('network',2),E.PROJECTS.branch),E.projectCycles(withModel('network','regionalHub',withTier('network',2)),E.PROJECTS.branch),'regionalHub work reduction does not stack');
assert.equal(E.projectCycles(withTier('operations',1),E.PROJECTS.remediation),E.projectCycles(base,E.PROJECTS.remediation),'short project work is not reduced');
assert.equal(E.projectCycles(withTier('operations',1),E.PROJECTS.branch),E.projectCycles(base,E.PROJECTS.branch)-1);
assert.equal(E.projectCycles(withTier('acquisition',2),E.PROJECTS.acquisition),E.projectCycles(base,E.PROJECTS.acquisition)-1);
const regional=E.createGame({mode:'hotseat',seed:43,created:1,campaignRulesVersion:1}),regionalBank=regional.players[0];
assert.deepEqual(copy(E.regionalBranchMetrics(withModel('network','regionalHub',regionalBank))),copy(E.regionalBranchMetrics(regionalBank)),'regionalHub adds no outside-book or branch capacity');
const freshTarget=Object.keys(regional.territories).find(k=>!regionalBank.branches[k]);
regionalBank.capability.network=E.CAPABILITY_TIERS.network.at(-1);const entryShare=[...regional.territories[freshTarget].shares];
E.finishProject(regional,regionalBank,{key:'branch',target:freshTarget});
assert.deepEqual(copy(regional.territories[freshTarget].shares),copy(entryShare),'complete regional settlement restores entry influence despite capstone');
assert.equal(regional.territories[freshTarget].reentryUntil[0],regional.cycle+8);
const legacy=E.createGame({mode:'hotseat',seed:43,created:1});legacy.players[0].capability.network=E.CAPABILITY_TIERS.network.at(-1);
const legacyTarget=Object.keys(legacy.territories).find(k=>!legacy.players[0].branches[k]),priorShare=legacy.territories[legacyTarget].shares[0];
E.finishProject(legacy,legacy.players[0],{key:'branch',target:legacyTarget});assert(legacy.territories[legacyTarget].shares[0]>priorShare,'legacy capstone share behavior is retained');
h.c.descriptionView=E.publicState(regional,0);
assert(h.run("strategyMilestoneDescription(descriptionView,'network',3)").includes('preserves its existing share'));
h.c.descriptionView=E.publicState(legacy,0);
assert.equal(h.run("strategyMilestoneDescription(descriptionView,'network',3)"),E.STRATEGY_BRANCHES.network.nodes[3].desc,'legacy wording remains distinct');
assert(h.run("strategyMilestoneDescription(descriptionView,'commercial',2)").includes('does not reduce underwriting risk'));
assert(h.run("strategyModelDescription(descriptionView,'operations','resilience')").includes('modeled credit-loss multiplier'));
h.run('descriptionView.me.creditPerformance={version:1}');assert(h.run("strategyModelDescription(descriptionView,'operations','resilience')").includes('existing loan cohorts retain their risk'));
console.log('Strategy release UI passed: all existing milestones, exact bounded funding, confirmation/cancel/stale/sealed guards, optional application dependencies, retained roadmap/focus, engine-backed description corrections and '+resolved+' full monthly model-adoption resolutions across all five capabilities and both seats.');
