'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),zlib=require('node:zlib'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const copy=x=>JSON.parse(JSON.stringify(x)),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const source=require('../tools/build_game').assemble().html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1];
const make=code=>{const c={console};vm.runInNewContext(code.replace('root.BWEngine={','root.BWEngine={withCorporateForecast,facilityInvestmentDraft,facilityInvestmentReview,planFacilityInvestment,'),c);return c.BWEngine;};
const E=make(source),bytes=fs.readFileSync(path.join(__dirname,'fixtures/v31-group7-growth283.json.gz'));
assert.equal(hash(bytes),'e0886c332a22cffd3d455f4b3e48b6d7b8020b518cd706ef6114ac2d53c685b9');
const saved=JSON.parse(zlib.gunzipSync(bytes)).game;E.validatePilot(saved);E.validateLedger(saved);assert.equal(saved.cycle,284);
const guard=' if(!draftAuthorized.status.eligible)return input;\n';assert(source.includes(guard));
const B=make(source.replace(guard,''));
assert.throws(()=>B.chooseBot(copy(saved),1),/Function quotas exceed remaining service staff/,'The actual late-game failure must reproduce without the guard');
const boundary='return [7,8].includes(g.financialGroupVersion)?planFacilityInvestment(g,index,plan):plan;';assert(source.includes(boundary));
const P=make(source.replace(boundary,'return plan;')),world=copy(saved),plan=P.chooseBot(world,1),p=world.players[1],deferred=E.facilityInvestmentDraft(plan);
const ordinary=E.departmentFunctionsQuote(world,p,plan),afterDeferral=E.departmentFunctionsQuote(world,p,deferred);
assert(ordinary.status.eligible,ordinary.status.reason);assert.equal(afterDeferral.status.eligible,false);
assert.match(afterDeferral.status.reason,/remaining service staff/);
assert.equal(E.departmentBudgetQuote(p,plan).training.paused,true);
assert.equal(E.departmentBudgetQuote(p,deferred).training.paused,false);
assert(afterDeferral.attribution.paidTeacherQuarters.service>ordinary.attribution.paidTeacherQuarters.service,'Funded teaching reserves a real service banker');
assert.deepEqual(copy(deferred.departmentFunctionsPolicy),copy(plan.departmentFunctionsPolicy));
const before=JSON.stringify(world),instructions=JSON.stringify(plan);
const returned=E.withCorporateForecast(world,()=>E.planFacilityInvestment(world,1,plan));
assert.equal(returned,plan,'Keep the legal complete plan, not an invented staffing or training repair');
const office=p.facilityNetwork.offices.find(o=>o.closedCycle===null);
const review=E.withCorporateForecast(world,()=>E.facilityInvestmentReview(world,1,plan,{officeId:office.id,model:'commercial'}));
assert.equal(review.eligible,false);assert.match(review.reason,/deferred: Function quotas/);
assert.equal(JSON.stringify(world),before);assert.equal(JSON.stringify(plan),instructions);
const g=copy(saved),twin=copy(saved),plans=g.players.map((_,i)=>E.chooseBot(g,i)),again=twin.players.map((_,i)=>E.chooseBot(twin,i));
assert.deepEqual(copy(plans),copy(again));assert.deepEqual(copy(g.rng),copy(twin.rng));
for(const [i,draft]of plans.entries())assert(E.departmentFunctionsQuote(g,g.players[i],draft).status.eligible);
E.submit(g,0,plans[0]);const restored=E.migrateCampaign(copy(g));E.submit(g,1,plans[1]);E.submit(restored,1,copy(plans[1]));
E.validatePilot(g);E.validateLedger(g);assert.equal(g.cycle,285);
assert.deepEqual(copy(E.migrateCampaign(g)),copy(E.migrateCampaign(restored)));
console.log(JSON.stringify({suite:'v31-training-deferral',status:'PASS',engineSha256:hash(source),fixtureSha256:hash(bytes),scope:'Real month284 failure, research deferral unpauses paid teaching, unchanged staffing/training/vendors, pure rejected counterfactual, complete legal AI month and exact half-ready replay. Not a480-month pass.'}));
