'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),zlib=require('node:zlib'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const copy=x=>JSON.parse(JSON.stringify(x)),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const source=require('../tools/build_game').assemble().html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1];
const make=code=>{const c={console};vm.runInNewContext(code.replace('root.BWEngine={','root.BWEngine={withCorporateForecast,projectPlanStatus,planExecutionReserve,'),c);return c.BWEngine;};
const E=make(source),bytes=fs.readFileSync(path.join(__dirname,'fixtures/v31-group7-balanced317.json.gz'));
assert.equal(hash(bytes),'135cd0a1b51ce4592cb21b8ae7e249acf8328bbe75adac6d4739325d97463efd');
const saved=JSON.parse(zlib.gunzipSync(bytes)),g=copy(saved.game),input=copy(saved.pending[1]);
E.validatePilot(g);E.validateLedger(g);assert.equal(g.cycle,318);
assert.throws(()=>E.submit(copy(g),1,copy(input)),/needs 2.5 execution capacity but staffs only 1.5/,'Never silently repair submitted human/network instructions');
const boundary='    if([7,8].includes(g.financialGroupVersion))plan=planExecutionReserve(g,index,plan);\n';assert(source.includes(boundary));
const old=make(source.replace(boundary,'')),oldWorld=copy(g),oldPlan=old.chooseBot(oldWorld,1);
assert.equal(old.projectPlanStatus(oldWorld.players[1],oldPlan).code,'capacity','Unrepaired complete AI reproduces the actual capacity failure');
const before=JSON.stringify(g),instructions=JSON.stringify(input),fixed=E.withCorporateForecast(g,()=>E.planExecutionReserve(g,1,input));
assert.equal(JSON.stringify(g),before);assert.equal(JSON.stringify(input),instructions);
assert.equal(fixed.newProjects.length,0);assert.equal(fixed.newProject,null);
for(const key of ['allocation','investments','workforcePolicy','departmentPolicy','leaderOrders','hires','specialistHires','facilityPolicy','collectionsPolicy','groupPolicy'])assert.deepEqual(copy(fixed[key]),copy(input[key]),key+' must not be invented or cancelled');
assert.equal(E.planBudget(g.players[1],fixed).capacity,1.5);
assert.equal(E.planBudget(g.players[1],fixed).load,1.5,'Existing paid branch retains its execution demand');
assert(E.projectPlanStatus(g.players[1],fixed).eligible);
const a=E.departmentFunctionsQuote(g,g.players[1],input),b=E.departmentFunctionsQuote(g,g.players[1],fixed);
assert(b.status.eligible,b.status.reason);assert.deepEqual(copy(a.attribution.paidTeacherQuarters),copy(b.attribution.paidTeacherQuarters));
for(const row of a.delivery.rows){const next=b.delivery.rows.find(r=>r.id===row.id);assert(next.delivered.served+1e-8>=row.delivered.served,'Protected '+row.id+' work reduced');}
assert(E.planBudget(g.players[1],fixed).remaining>=0);
assert.equal(E.planExecutionReserve(g,1,fixed),fixed,'Already feasible plans preserve identity without extra planning');
assert.equal(E.planExecutionReserve({...g,financialGroupVersion:6},1,input),input,'Legacy rule boundary');
const half=E.migrateCampaign(copy(g));E.submit(g,1,fixed);E.submit(half,1,copy(fixed));
E.validatePilot(g);E.validateLedger(g);assert.equal(g.cycle,319);assert.deepEqual(copy(E.migrateCampaign(g)),copy(E.migrateCampaign(half)));
const fresh=copy(saved.game),twin=copy(saved.game),plan=E.chooseBot(fresh,1),again=E.chooseBot(twin,1);
assert.deepEqual(copy(plan),copy(again));assert.deepEqual(copy(fresh.rng),copy(twin.rng));
E.submit(fresh,1,plan);E.submit(twin,1,again);E.validatePilot(fresh);E.validateLedger(fresh);assert.deepEqual(copy(fresh),copy(twin));
console.log(JSON.stringify({suite:'v31-execution-reserve',status:'PASS',engineSha256:hash(source),fixtureSha256:hash(bytes),scope:'Actual month318 half-ready failure, full AI reproduction, funded training retained, only unstarted initiatives deferred, protected delivery, no resource mutation, legacy/no-op boundary, legal settlement and exact replay. Not a480-month pass.'}));
